-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- CREATE THE 1 VIEW FOR THE PII TABLE. CREATE A READ ROLE FOR IT
-- ADD THE NO_PII GROUP ROLE TO DBT ROLES

--RAW.DIRECT_MAIL_RECIPIENTS.DIRECT_MAIL_2_23_17

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA DIRECT_MAIL_RECIPIENTS;

CREATE OR REPLACE VIEW VW_DIRECT_MAIL_2_23_17  COPY GRANTS  AS
(
  SELECT
      CASE WHEN PII_ACCESS = TRUE THEN FULL_NAME_ ELSE  sha2(FULL_NAME_,512) END AS FULL_NAME_,
      CASE WHEN PII_ACCESS = TRUE THEN DELIVERY_ADDRESS_ ELSE  sha2(DELIVERY_ADDRESS_,512) END AS DELIVERY_ADDRESS_,
      CITY_	,
      ST	,
      ZIP_4_	,
      DE	,
      CRRT	,
      B	,
      WALK_SE	,
      LIST_CODE_

  FROM DIRECT_MAIL_2_23_17
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLE
CREATE ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role";

GRANT USAGE ON DATABASE RAW TO ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.DIRECT_MAIL_RECIPIENTS TO ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role";

-- CREATE THE INDIVIDUAL TABLE ROLES AND VIEW ROLEs
CREATE ROLE "RAW.DIRECT_MAIL_RECIPIENTS.DIRECT_MAIL_2_23_17.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."DIRECT_MAIL_RECIPIENTS"."VW_DIRECT_MAIL_2_23_17" TO ROLE "RAW.DIRECT_MAIL_RECIPIENTS.DIRECT_MAIL_2_23_17.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.DIRECT_MAIL_RECIPIENTS.DIRECT_MAIL_2_23_17.no_pii.view.reader" TO ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role";

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "RAW.DIRECT_MAIL_RECIPIENTS.no_pii.reader.role" TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################
USE DATABASE RAW;
USE SCHEMA DIRECT_MAIL_RECIPIENTS;
USE ROLE AIRFLOW_SERVICE_ROLE;
USE WAREHOUSE TRANSFORMING_WAREHOUSE;

-- TRANSFORMER ROLE HERE HAS ALL RIGHTS ON THE SCHEMA
show grants on schema DIRECT_MAIL_RECIPIENTS;

show grants on table "RAW"."DIRECT_MAIL_RECIPIENTS"."DIRECT_MAIL_2_23_17" ;
TRANSFORMER