-- UPDATE PLAN
-- 5 TABLES ARE BEING USED BY DBT
-- 5 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- NO VIEWS NEEDED
-- ADD THE 5 read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.FIVETRAN_BING_ADS.ACCOUNT_HISTORY
--RAW.FIVETRAN_BING_ADS.AD_GROUP_HISTORY
--RAW.FIVETRAN_BING_ADS.CAMPAIGN_HISTORY
--RAW.FIVETRAN_BING_ADS.USER_LOCATION_PERFORMANCE_DAILY_REPORT

-- CANNOT FIND THIS SCHEMA OF TABLE
--RAW.FIVETRAN_BING.BING_ADS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_BING_ADS;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.FIVETRAN_BING_ADS TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.FIVETRAN_BING_ADS.ACCOUNT_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_BING_ADS.AD_GROUP_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_BING_ADS.CAMPAIGN_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_BING_ADS.USER_LOCATION_PERFORMANCE_DAILY_REPORT.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."FIVETRAN_BING_ADS"."ACCOUNT_HISTORY" TO ROLE "RAW.FIVETRAN_BING_ADS.ACCOUNT_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_BING_ADS"."AD_GROUP_HISTORY" TO ROLE "RAW.FIVETRAN_BING_ADS.AD_GROUP_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_BING_ADS"."CAMPAIGN_HISTORY" TO ROLE "RAW.FIVETRAN_BING_ADS.CAMPAIGN_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_BING_ADS"."USER_LOCATION_PERFORMANCE_DAILY_REPORT" TO ROLE "RAW.FIVETRAN_BING_ADS.USER_LOCATION_PERFORMANCE_DAILY_REPORT.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE  "RAW.FIVETRAN_BING_ADS.ACCOUNT_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_BING_ADS.AD_GROUP_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_BING_ADS.CAMPAIGN_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_BING_ADS.USER_LOCATION_PERFORMANCE_DAILY_REPORT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role"  TO ROLE DBT_DEV;
GRANT ROLE "RAW.FIVETRAN_BING_ADS.no_pii.reader.role"  TO ROLE DBT_PROD;



-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_BING_ADS;

show grants on schema FIVETRAN_BING_ADS;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;


SHOW GRANTS ON TABLE
RAW.FIVETRAN_BING_ADS.ACCOUNT_HISTORY
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLES