-- UPDATE PLAN
-- 19 TABLES ARE BEING USED BY DBT
-- 16 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 3 PII TABLE-- 3 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_MESSAGE
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_NOTE
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_ELIGIBILITY
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_PREFERENCE
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_STATUS_LOG
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CUSTOMER_FACTS
--RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_MCC_REFINEMENT_REQUEST
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ADJUSTMENTS
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ITEM
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT_REFUND
--RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_PRODUCT_KIND
--RAW.FIVETRAN_TESSERACT_PUBLIC.DISCOUNTS_DISCOUNTUSAGELOG
--RAW.FIVETRAN_TESSERACT_PUBLIC.LOCATIONS_STORE_SERVICE_AREA
-- pii
--RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER
--RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_ADDRESS
--RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_HISTORY

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_TESSERACT_PUBLIC;

CREATE OR REPLACE VIEW VW_PROFILES_USER  COPY GRANTS  AS
(
  SELECT
        ID	,
        PASSWORD	,
        LAST_LOGIN	,
        IS_SUPERUSER	,
        CREATED_BY	,
        UPDATED_BY	,
        UUID	,
        DATE_CREATED	,
        DATE_UPDATED	,
        DATE_REMOVED	,
        PROFILES_USER.ROLE	,
        CASE WHEN PII_ACCESS = TRUE THEN USERNAME ELSE sha2(USERNAME,512) END AS USERNAME,
        CASE WHEN PII_ACCESS = TRUE THEN FIRST_NAME ELSE sha2(FIRST_NAME,512) END AS FIRST_NAME,
        CASE WHEN PII_ACCESS = TRUE THEN LAST_NAME ELSE sha2(LAST_NAME,512) END AS LAST_NAME,
        DATE_JOINED	,
        DATE_PASSWORD	,
        REQUIRE_PASSWORD_CHANGE	,
        IS_ACTIVE	,
        IS_SUSPENDED	,
        IS_STAFF	,
        IS_COMPLETE	,
        SMS_OPTOUT_ON	,
        KLARNA_HARD_CHECK	,
        KLARNA_SOFT_CHECK	,
        SURVEY_SOURCE	,
        CONTACT_KEY	,
        CASE WHEN PII_ACCESS = TRUE THEN DATE_OF_BIRTH ELSE '2099-01-01' END AS  DATE_OF_BIRTH	,
        _FIVETRAN_SYNCED	,
        _FIVETRAN_DELETED	,
        COUNTRY_ID	,
        EXT_PROFILE_ID	,
        EXT_PROFILE_EMAIL_ID

  FROM PROFILES_USER
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

CREATE OR REPLACE VIEW VW_PROFILES_USER_ADDRESS COPY GRANTS  AS
(
  SELECT
        ID	,
        CASE WHEN PII_ACCESS = TRUE THEN CREATED_BY ELSE sha2(CREATED_BY,512) END AS CREATED_BY,
        CASE WHEN PII_ACCESS = TRUE THEN UPDATED_BY ELSE sha2(UPDATED_BY,512) END AS UPDATED_BY,
        UUID	,
        DATE_CREATED	,
        DATE_UPDATED	,
        DATE_REMOVED	,
        RESOURCE_ID	,
        CASE WHEN PII_ACCESS = TRUE THEN CONTACT_NAME ELSE sha2(CONTACT_NAME,512) END AS CONTACT_NAME,
        COMPANY	,
        CASE WHEN PII_ACCESS = TRUE THEN STREET1 ELSE sha2(STREET1,512) END AS STREET1,
        CASE WHEN PII_ACCESS = TRUE THEN STREET2 ELSE sha2(STREET2,512) END AS STREET2,
        LOCALITY,
        REGION	,
        POSTAL_CODE	,
        RESIDENTIAL ,
        LATITUDE	,
        LONGITUDE	,
        TIMEZONE	,
        CASE WHEN PII_ACCESS = TRUE THEN PHONE ELSE sha2(PHONE,512) END AS PHONE,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL,
        KIND	,
        COUNTRY_ID	,
        USER_ID	,
        _FIVETRAN_SYNCED	,
        _FIVETRAN_DELETED	,
        EXT_PROFILE_ADDRESS_ID	,
        EXT_PROFILE_EMAIL_ID	,
        EXT_PROFILE_PHONE_ID	,
        SUBLOCALITY

  FROM PROFILES_USER_ADDRESS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


CREATE OR REPLACE VIEW VW_PROFILES_USER_HISTORY  COPY GRANTS  AS
(
  SELECT
        ID	,
        DATE_CHANGE	,
        LABEL_DISPLAY	,
        CASE WHEN PII_ACCESS = TRUE THEN OLD_VALUE ELSE sha2(OLD_VALUE,512) END AS OLD_VALUE,
        CASE WHEN PII_ACCESS = TRUE THEN NEW_VALUE ELSE sha2(NEW_VALUE,512) END AS NEW_VALUE,
        CREATED_BY	,
        DATE_CREATED	,
        DATE_UPDATED	,
        DATE_REMOVED	,
        USER_ID	,
        _FIVETRAN_SYNCED	,
        _FIVETRAN_DELETED

  FROM PROFILES_USER_HISTORY
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.FIVETRAN_TESSERACT_PUBLIC TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND THREE VIEW ROLES
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_MESSAGE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_NOTE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_ELIGIBILITY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_PREFERENCE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_STATUS_LOG.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CUSTOMER_FACTS.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_MCC_REFINEMENT_REQUEST.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ADJUSTMENTS.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ITEM.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT_REFUND.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_PRODUCT_KIND.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.DISCOUNTS_DISCOUNTUSAGELOG.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.LOCATIONS_STORE_SERVICE_AREA.no_pii.table.reader";

CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER.no_pii.view.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_ADDRESS.no_pii.view.reader";
CREATE ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_HISTORY.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE_MESSAGE" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_MESSAGE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE_NOTE" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_NOTE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE_PRODUCT_ELIGIBILITY" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_ELIGIBILITY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE_PRODUCT_PREFERENCE" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_PREFERENCE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CASE_STATUS_LOG" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_STATUS_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_CUSTOMER_FACTS" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CUSTOMER_FACTS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."CASES_MCC_REFINEMENT_REQUEST" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_MCC_REFINEMENT_REQUEST.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_ORDER" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_ORDER_ADJUSTMENTS" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ADJUSTMENTS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_ORDER_ITEM" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ITEM.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_ORDER_PAYMENT" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_ORDER_PAYMENT_REFUND" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT_REFUND.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."COMMERCE_PRODUCT_KIND" TO ROLE  "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_PRODUCT_KIND.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."DISCOUNTS_DISCOUNTUSAGELOG" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.DISCOUNTS_DISCOUNTUSAGELOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_TESSERACT_PUBLIC"."LOCATIONS_STORE_SERVICE_AREA" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.LOCATIONS_STORE_SERVICE_AREA.no_pii.table.reader";

GRANT SELECT ON VIEW "RAW"."FIVETRAN_TESSERACT_PUBLIC"."VW_PROFILES_USER" TO ROLE  "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."FIVETRAN_TESSERACT_PUBLIC"."VW_PROFILES_USER_ADDRESS" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_ADDRESS.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."FIVETRAN_TESSERACT_PUBLIC"."VW_PROFILES_USER_HISTORY" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_HISTORY.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_MESSAGE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_NOTE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_ELIGIBILITY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_PRODUCT_PREFERENCE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CASE_STATUS_LOG.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_CUSTOMER_FACTS.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.CASES_MCC_REFINEMENT_REQUEST.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ADJUSTMENTS.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_ITEM.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_ORDER_PAYMENT_REFUND.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.COMMERCE_PRODUCT_KIND.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.DISCOUNTS_DISCOUNTUSAGELOG.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.LOCATIONS_STORE_SERVICE_AREA.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;

GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER.no_pii.view.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_ADDRESS.no_pii.view.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.PROFILES_USER_HISTORY.no_pii.view.reader" TO ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.FIVETRAN_TESSERACT_PUBLIC.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_TESSERACT_PUBLIC;

show grants on schema FIVETRAN_TESSERACT_PUBLIC;
FIVETRAN_ROLE
TRANSFORMER
BUSINESS_INTELLIGENCE
FIVETRAN_WAREHOUSE.RAW.FIVETRAN_TESSERACT_PUBLIC.pii.reader.role


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

show grants to ROLE BUSINESS_INTELLIGENCE ;
show grants ON ROLE BUSINESS_INTELLIGENCE;

show grants to ROLE "FIVETRAN_WAREHOUSE.RAW.FIVETRAN_TESSERACT_PUBLIC.pii.reader.role";
-- HAS SELECT ON ALL THE TABLES
show grants ON ROLE "FIVETRAN_WAREHOUSE.RAW.FIVETRAN_TESSERACT_PUBLIC.pii.reader.role";
TEAMTHANOS
FIVETRAN_WAREHOUSE.RAW.FIVETRAN_TESSERACT_PUBLIC.pii.service.role
SHOW GRANTS ON TABLE
"RAW"."FIVETRAN_TESSERACT_PUBLIC"."PROFILES_USER"
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs