-- UPDATE PLAN
-- 11 TABLES ARE BEING USED BY DBT
-- 10 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 1 PII TABLE-- 1 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.MYSQLCOMMON.AUTOBAGGER_BAGS

--RAW.MYSQLCOMMON.AUTOBAGGER_BOX_LABELS
--RAW.MYSQLCOMMON.BOX_TO_PRODUCT_CODE_MAPPINGS
--RAW.MYSQLCOMMON.BOXES
--RAW.MYSQLCOMMON.CARRIER_CODE_MAPPINGS
--RAW.MYSQLCOMMON.JOBS
--RAW.MYSQLCOMMON.PRINT_ASSETS
--RAW.MYSQLCOMMON.PRINT_ORDERS
--RAW.MYSQLCOMMON.PRINT_ORDERS_TAGS
--RAW.MYSQLCOMMON.TAGS
--RAW.MYSQLCOMMON.TRACKING_TOKENS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA MYSQLCOMMON;


CREATE OR REPLACE VIEW VW_AUTOBAGGER_BAGS  COPY GRANTS  AS
(
  SELECT
        AUTOBAGGER_BOX_LABEL_ID	,
        CREATED_AT	,
         CASE WHEN PII_ACCESS = TRUE THEN DESCRIPTION ELSE sha2(DESCRIPTION,512) END AS DESCRIPTION,
        ID	,
        TESSERACT_ORDER_NUMBER	,
        UPDATED_AT	,
        UUID	,
        _SDC_BATCHED_AT	,
        _SDC_EXTRACTED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION

  FROM AUTOBAGGER_BAGS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.MYSQLCOMMON TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BAGS.no_pii.view.reader";

CREATE ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BOX_LABELS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.BOX_TO_PRODUCT_CODE_MAPPINGS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.BOXES.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.CARRIER_CODE_MAPPINGS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.JOBS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.PRINT_ASSETS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS_TAGS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.TAGS.no_pii.table.reader";
CREATE ROLE "RAW.MYSQLCOMMON.TRACKING_TOKENS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."MYSQLCOMMON"."VW_AUTOBAGGER_BAGS" TO ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BAGS.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."AUTOBAGGER_BOX_LABELS" TO ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BOX_LABELS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."BOX_TO_PRODUCT_CODE_MAPPINGS" TO ROLE "RAW.MYSQLCOMMON.BOX_TO_PRODUCT_CODE_MAPPINGS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."BOXES" TO ROLE "RAW.MYSQLCOMMON.BOXES.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."CARRIER_CODE_MAPPINGS" TO ROLE "RAW.MYSQLCOMMON.CARRIER_CODE_MAPPINGS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."JOBS" TO ROLE "RAW.MYSQLCOMMON.JOBS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."PRINT_ASSETS" TO ROLE "RAW.MYSQLCOMMON.PRINT_ASSETS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."PRINT_ORDERS" TO ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."PRINT_ORDERS_TAGS" TO ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS_TAGS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."TAGS" TO ROLE "RAW.MYSQLCOMMON.TAGS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MYSQLCOMMON"."TRACKING_TOKENS" TO ROLE "RAW.MYSQLCOMMON.TRACKING_TOKENS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BAGS.no_pii.view.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;

GRANT ROLE "RAW.MYSQLCOMMON.AUTOBAGGER_BOX_LABELS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.BOX_TO_PRODUCT_CODE_MAPPINGS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.BOXES.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.CARRIER_CODE_MAPPINGS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.JOBS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.PRINT_ASSETS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.PRINT_ORDERS_TAGS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.TAGS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;
GRANT ROLE "RAW.MYSQLCOMMON.TRACKING_TOKENS.no_pii.table.reader" TO ROLE "RAW.MYSQLCOMMON.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.MYSQLCOMMON.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.MYSQLCOMMON.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA MYSQLCOMMON;

show grants on schema MYSQLCOMMON;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs