-- UPDATE PLAN
-- 8 TABLES ARE BEING USED BY DBT
-- 8 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- NO VIEWS NEEDED
-- ADD THE 8 read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.GEO_PERFORMANCE_REPORT
--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_SEARCH_PERFORMANCE
--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_YOUTUBE_PERFORMANCE
--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.KEYWORDS_PERFORMANCE_REPORT
--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_SEARCH_PERFORMANCE
--RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_YOUTUBE_PERFORMANCE

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_ADWORDS_SMILEDIRECTCLUB;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.GEO_PERFORMANCE_REPORT.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_SEARCH_PERFORMANCE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.KEYWORDS_PERFORMANCE_REPORT.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_SEARCH_PERFORMANCE.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."GEO_PERFORMANCE_REPORT" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.GEO_PERFORMANCE_REPORT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."INTERNATIONAL_GEO_SEARCH_PERFORMANCE" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_SEARCH_PERFORMANCE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."INTERNATIONAL_GEO_YOUTUBE_PERFORMANCE" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."KEYWORDS_PERFORMANCE_REPORT" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.KEYWORDS_PERFORMANCE_REPORT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."US_GEO_SEARCH_PERFORMANCE" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_SEARCH_PERFORMANCE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."US_GEO_YOUTUBE_PERFORMANCE" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.GEO_PERFORMANCE_REPORT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_SEARCH_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.INTERNATIONAL_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.KEYWORDS_PERFORMANCE_REPORT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_SEARCH_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.US_GEO_YOUTUBE_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "RAW.FIVETRAN_ADWORDS_SMILEDIRECTCLUB.no_pii.reader.role" TO ROLE DBT_PROD;

--########################

--RAW.FIVETRAN_ADWORDS.LOVEYOURSMILES_ADWORDS
--RAW.FIVETRAN_ADWORDS.SHARPER_IMAGE_ADWORDS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_ADWORDS;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.FIVETRAN_ADWORDS TO ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.FIVETRAN_ADWORDS.LOVEYOURSMILES_ADWORDS.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_ADWORDS.SHARPER_IMAGE_ADWORDS.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."LOVEYOURSMILES_ADWORDS" TO ROLE "RAW.FIVETRAN_ADWORDS.LOVEYOURSMILES_ADWORDS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_ADWORDS_SMILEDIRECTCLUB"."SHARPER_IMAGE_ADWORDS" TO ROLE "RAW.FIVETRAN_ADWORDS.SHARPER_IMAGE_ADWORDS.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE  "RAW.FIVETRAN_ADWORDS.LOVEYOURSMILES_ADWORDS.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" ;
GRANT ROLE  "RAW.FIVETRAN_ADWORDS.SHARPER_IMAGE_ADWORDS.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "RAW.FIVETRAN_ADWORDS.no_pii.reader.role" TO ROLE DBT_PROD;

-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_ADWORDS;

show grants on schema FIVETRAN_ADWORDS;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;


SHOW GRANTS ON TABLE RAW.FIVETRAN_ADWORDS.SHARPER_IMAGE_ADWORDS
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLES