-- UPDATE PLAN
-- 4 TABLES ARE BEING USED BY DBT
-- 3 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 1 PII TABLE - CREATE THE INDIVIDUAL READ ROLE FOR THIS
-- CREATE THE 1 VIEW FOR THE PII TABLE. CREATE A READ ROLE FOR IT
-- ADD THE 3 TABLES AND 1 VIEW ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.ADHOC_TABLES.ALIGNER_SALES_PUSH_CODES_20190911
--RAW.ADHOC_TABLES.DATETABLE
--RAW.ADHOC_TABLES.TA_OPENREQS_JOB_EXPORT
--RAW.ADHOC_TABLES.TERM_HIST

--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA ADHOC_TABLES;

CREATE OR REPLACE VIEW VW_ALIGNER_SALES_PUSH_CODES_20190911 COPY GRANTS AS
(
  SELECT
      _FILE,
      _LINE,
      CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS EMAIL_ADDRESS,
      CONTACT_KEY	,
      UNIQUE_CODES	,
      LEAD_AGE	,
      _FIVETRAN_SYNCED

  FROM ALIGNER_SALES_PUSH_CODES_20190911
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
--CREATE ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.ADHOC_TABLES TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.ADHOC_TABLES.ALIGNER_SALES_PUSH_CODES_20190911.pii.view.reader";

CREATE ROLE "RAW.ADHOC_TABLES.DATETABLE.no_pii.table.reader";
CREATE ROLE "RAW.ADHOC_TABLES.TA_OPENREQS_JOB_EXPORT.no_pii.table.reader";
CREATE ROLE "RAW.ADHOC_TABLES.TERM_HIST.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."ADHOC_TABLES"."VW_ALIGNER_SALES_PUSH_CODES_20190911" TO ROLE "RAW.ADHOC_TABLES.ALIGNER_SALES_PUSH_CODES_20190911.pii.view.reader";
GRANT SELECT ON TABLE "RAW"."ADHOC_TABLES"."DATETABLE" TO ROLE  "RAW.ADHOC_TABLES.DATETABLE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."ADHOC_TABLES"."TA_OPENREQS_JOB_EXPORT" TO ROLE "RAW.ADHOC_TABLES.TA_OPENREQS_JOB_EXPORT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."ADHOC_TABLES"."TERM_HIST" TO ROLE "RAW.ADHOC_TABLES.TERM_HIST.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.ADHOC_TABLES.DATETABLE.no_pii.table.reader" TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;
GRANT ROLE "RAW.ADHOC_TABLES.TA_OPENREQS_JOB_EXPORT.no_pii.table.reader" TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;
GRANT ROLE "RAW.ADHOC_TABLES.TERM_HIST.no_pii.table.reader" TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;
GRANT ROLE "RAW.ADHOC_TABLES.ALIGNER_SALES_PUSH_CODES_20190911.pii.view.reader" TO ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "RAW.ADHOC_TABLES.no_pii.reader.role" TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################


show grants on schema adhoc_tables;
USE WAREHOUSE TRANSFORMING_WAREHOUSE

show grants to ROLE "RAW.ADHOC_TABLES.no_pii.reader.role";
