-- UPDATE PLAN
-- 2 TABLES ARE BEING USED BY DBT
-- 0 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 2 PII TABLE-- 2 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.INGRAM.ACCESSORIAL_CHARGES
-- RAW.INGRAM.FREIGHT_CHARGES

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA INGRAM;


CREATE OR REPLACE VIEW VW_ACCESSORIAL_CHARGES  COPY GRANTS  AS
(
  SELECT
        STR_INVOICE_NUMBER	,
        DT_INVOICE_DATE	,
        STR_PARENT_ACCT_NAME	,
        STR_PARENT_ACCT_NBR	,
        STR_ACCOUNT_NBR	,
        STR_CUST_ACCT_NAME	,
        DAT_TRAN_DT	,
        STR_CUST_NAME	,
        STR_PRO_NBR	,
        STR_SERVICE_LVL,
        DAT_SHIP_DATE	,
        STR_REF	,
        STR_REF_1	,
        STR_REF_2	,
        STR_CHRG_CODE	,
        STR_SPCDESC	,
        CUR_SPCCHARGE	,
        STR_SHPR_CO	,
        STR_SHPR_ST ,
        STR_SHPR_ADDR_LINE_2	,
        STR_CITY_FR ,
        STR_SHP_FR	,
        STR_ZIP_FR	,
        STR_ORG_COUNTRY	,
        STR_RCPNT_NAME	,
        CASE WHEN PII_ACCESS = TRUE THEN STR_CONSIGNEE ELSE sha2(STR_CONSIGNEE,512) END AS  STR_CONSIGNEE,
        CASE WHEN PII_ACCESS = TRUE THEN STR_CONSIGNEE_ST ELSE sha2(STR_CONSIGNEE_ST,512) END AS  STR_CONSIGNEE_ST,
        CASE WHEN PII_ACCESS = TRUE THEN STR_RCPNT_ADDR_LINE_2 ELSE sha2(STR_RCPNT_ADDR_LINE_2,512) END AS  STR_RCPNT_ADDR_LINE_2,
        STR_CITY_TO,
        STR_SHP_TO	,
        STR_ZIP_TO	,
        STR_BUNDLE	,
        STR_DEST_COUNTRY	,
        DAT_DATE_ADDED	,
        _FILE	,
        _LINE	,
        _FIVETRAN_SYNCED

  FROM ACCESSORIAL_CHARGES
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


CREATE OR REPLACE VIEW VW_FREIGHT_CHARGES  COPY GRANTS  AS
(
  SELECT
        STR_INVOICE_NUMBER	,
        DT_INVOICE_DATE,
        STR_PARENT_ACCT_NAME	,
        STR_PARENT_ACCT_NBR	,
        STR_ACCT_NBR	,
        STR_CUST_ACCT_NAME	,
        DAT_TRAN_DT	,
        STR_INV_NBR	,
        DAT_INV_DATE	,
        STR_CARRIER_NAME	,
        STR_PRO_NBR	,
        DAT_SHIP_DATE	,
        STR_SERVICE_LVL,
        STR_COMMODITY_DESC	,
        STR_REF_1	,
        STR_REF_2	,
        CUR_FREIGHT_FEE	,
        STR_BUNDLE	,
        INT_QTY	,
        DEC_REWEIGH	,
        DEC_DIM_WT	,
        DEC_WEIGHT	,
        DEC_GRND_MULTI_WT_PKG_WT	,
        DEC_LENGTH	,
        DEC_WIDTH	,
        DEC_HEIGHT ,
        DEC_DIM_DIVISOR	,
        STR_SHPR_CO	,
        STR_SHPR_ST	,
        STR_SHPR_ADDR_LINE_1	,
        STR_CITY_FR ,
        STR_SHP_FR	,
        STR_ZIP_FR	,
        STR_ORG_COUNTRY	,
        STR_RCPNT_NAME	,
        CASE WHEN PII_ACCESS = TRUE THEN STR_CONSIGNEE ELSE sha2(STR_CONSIGNEE,512) END AS  STR_CONSIGNEE,
        CASE WHEN PII_ACCESS = TRUE THEN STR_CONSIGNEE_ST ELSE sha2(STR_CONSIGNEE_ST,512) END AS  STR_CONSIGNEE_ST,
        CASE WHEN PII_ACCESS = TRUE THEN STR_RCPNT_ADDR_LINE_2 ELSE sha2(STR_RCPNT_ADDR_LINE_2,512) END AS  STR_RCPNT_ADDR_LINE_2,
        STR_CITY_TO,
        STR_SHP_TO	,
        STR_ZIP_TO	,
        STR_DEST_COUNTRY	,
        STR_IN_TRANSIT	,
        DAT_DELIVERED	,
        DAT_TIME_RCVD	,
        STR_PODSIGNATURE	,
        STR_ZONE	,
        STR_CARTON	,
        STR_PONBR	,
        STR_BILL_OF_LADING	,
        STR_RESI_FLAG	,
        DAT_DATE_ADDED	,
        _FILE	,
        _LINE	,
        _FIVETRAN_SYNCED	,
        STR_AMAZON_ORDER_NBR

  FROM FREIGHT_CHARGES
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.INGRAM.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.INGRAM.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.INGRAM TO ROLE "RAW.INGRAM.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.INGRAM.ACCESSORIAL_CHARGES.no_pii.view.reader";
CREATE ROLE "RAW.INGRAM.FREIGHT_CHARGES.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."INGRAM"."VW_ACCESSORIAL_CHARGES" TO ROLE "RAW.INGRAM.ACCESSORIAL_CHARGES.no_pii.view.reader";
GRANT SELECT ON TABLE "RAW"."INGRAM"."VW_FREIGHT_CHARGES" TO ROLE "RAW.INGRAM.FREIGHT_CHARGES.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.INGRAM.ACCESSORIAL_CHARGES.no_pii.view.reader" TO ROLE "RAW.INGRAM.no_pii.reader.role" ;
GRANT ROLE "RAW.INGRAM.FREIGHT_CHARGES.no_pii.view.reader" TO ROLE "RAW.INGRAM.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.INGRAM.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.INGRAM.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA INGRAM;

show grants on schema INGRAM;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."INGRAM"."FREIGHT_CHARGES"
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs