-- UPDATE PLAN
-- 12 TABLES ARE BEING USED BY DBT
-- 11 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 1 PII TABLE-- 1 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.STITCH_GOOGLE_ANALYTICS.REPORT

--RAW.STITCH_GOOGLE_SHEETS.LIVENATION

--RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS
--RAW.STITCH_GOOGLE_SHEETS.BBB
--RAW.STITCH_GOOGLE_SHEETS.BRANDED_CAMPAIGNS
--RAW.STITCH_GOOGLE_SHEETS.CVS_POS_DATA
--RAW.STITCH_GOOGLE_SHEETS.INFLUENCERS
--RAW.STITCH_GOOGLE_SHEETS.LIVENATION_CODES
--RAW.STITCH_GOOGLE_SHEETS.MACYS_POS
--RAW.STITCH_GOOGLE_SHEETS.MONTHLY_BUDGET
--RAW.STITCH_GOOGLE_SHEETS.SDC_DMA_LOOKUP
--RAW.STITCH_GOOGLE_SHEETS.VENDING

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_GOOGLE_ANALYTICS;



USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_GOOGLE_ANALYTICS TO ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_GOOGLE_ANALYTICS.REPORT.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_ANALYTICS"."REPORT" TO ROLE "RAW.STITCH_GOOGLE_ANALYTICS.REPORT.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_GOOGLE_ANALYTICS.REPORT.no_pii.view.reader"TO ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role";

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role"  TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_GOOGLE_ANALYTICS.no_pii.reader.role"  TO ROLE DBT_PROD;

---##################################################

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_GOOGLE_SHEETS;


CREATE OR REPLACE VIEW VW_LIVENATION COPY GRANTS  AS
(

  SELECT
        DATE_LEAD	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS  EMAIL,
        ID	,
        LEAD_SOURCE	,
        LEAD_SOURCE_DETAIL ,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION

  FROM LIVENATION
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_GOOGLE_SHEETS TO ROLE "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION.no_pii.view.reader";

CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.BBB.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.BRANDED_CAMPAIGNS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.CVS_POS_DATA.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.INFLUENCERS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION_CODES.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.MACYS_POS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.MONTHLY_BUDGET.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.SDC_DMA_LOOKUP.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_GOOGLE_SHEETS.VENDING.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_GOOGLE_SHEETS"."VW_LIVENATION" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."AMAZON_POS" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."BBB" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.BBB.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."BRANDED_CAMPAIGNS" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.BRANDED_CAMPAIGNS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."CVS_POS_DATA" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."INFLUENCERS" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.INFLUENCERS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."LIVENATION_CODES" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION_CODES.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."MACYS_POS" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.MACYS_POS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."MONTHLY_BUDGET" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.MONTHLY_BUDGET.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."SDC_DMA_LOOKUP" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.SDC_DMA_LOOKUP.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_GOOGLE_SHEETS"."VENDING" TO ROLE "RAW.STITCH_GOOGLE_SHEETS.VENDING.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION.no_pii.view.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.BBB.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.BRANDED_CAMPAIGNS.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.AMAZON_POS.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.INFLUENCERS.no_pii.table.reader"TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.LIVENATION_CODES.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.MACYS_POS.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.MONTHLY_BUDGET.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.SDC_DMA_LOOKUP.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.VENDING.no_pii.table.reader" TO ROLE  "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_GOOGLE_SHEETS.no_pii.reader.role"    TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_GOOGLE_SHEETS;

show grants on schema STITCH_GOOGLE_SHEETS;
STITCH_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."STITCH_GOOGLE_SHEETS"."LIVENATION"
-- TRANSFORMER HAS OWNE