-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- 1 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.NEWRELIC.USERAGENT_BROWSER_PERFORMANCE

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA NEWRELIC;


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.NEWRELIC.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.NEWRELIC.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.NEWRELIC TO ROLE "RAW.NEWRELIC.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.NEWRELIC.USERAGENT_BROWSER_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."NEWRELIC"."USERAGENT_BROWSER_PERFORMANCE" TO ROLE "RAW.NEWRELIC.USERAGENT_BROWSER_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.NEWRELIC.USERAGENT_BROWSER_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.NEWRELIC.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.NEWRELIC.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.NEWRELIC.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA NEWRELIC;

show grants on schema NEWRELIC;
FIVETRAN_ROLE
TRANSFORMER
AD_HOC


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs