-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- 1 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.R2C.AD_INSTANCE

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA R2C;

USE ROLE SECURITYADMIN;
-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.R2C.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.R2C.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW."R2C" TO ROLE "RAW.R2C.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.R2C.AD_INSTANCE_.no_pii.table.reader";
CREATE ROLE "RAW.R2C.AD_INSTANCE.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."R2C"."AD_INSTANCE_" TO ROLE "RAW.R2C.AD_INSTANCE_.no_pii.table.reader";
GRANT SELECT ON VIEW "RAW"."R2C"."AD_INSTANCE" TO ROLE "RAW.R2C.AD_INSTANCE.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.R2C.AD_INSTANCE.no_pii.view.reader" TO ROLE "RAW.R2C.no_pii.reader.role" ;
GRANT ROLE "RAW.R2C.AD_INSTANCE_.no_pii.table.reader" TO ROLE "RAW.R2C.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.R2C.no_pii.reader.role"   TO USE ROLE DBT_PROD
GRANT ROLE "RAW.R2C.no_pii.reader.role"   TO ROLE DBT_PROD;

-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA R2C;

show grants on schema R2C;
FIVETRAN_ROLE
TRANSFORMER
AD_HOC

show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs