-- UPDATE PLAN
-- 8 TABLES ARE BEING USED BY DBT
-- 8 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.FIVETRAN_PINTEREST_ADS.AD_GROUP_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_REPORT
--RAW.FIVETRAN_PINTEREST_ADS.AUDIENCE_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.CAMPAIGN_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.PIN_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.PIN_PROMOTION_HISTORY
--RAW.FIVETRAN_PINTEREST_ADS.PIN_PROMOTION_REPORT

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_PINTEREST_ADS;


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.FIVETRAN_PINTEREST_ADS TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.AD_GROUP_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_REPORT.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.AUDIENCE_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.CAMPAIGN_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_PROMOTION_HISTORY.no_pii.table.reader";
CREATE ROLE "RAW.FIVETRAN_GOOGLE_SHEETS.PIN_PROMOTION_REPORT.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."AD_GROUP_HISTORY" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.AD_GROUP_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."ADVERTISER_HISTORY" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."ADVERTISER_REPORT" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_REPORT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."AUDIENCE_HISTORY" TO ROLE  "RAW.FIVETRAN_PINTEREST_ADS.AUDIENCE_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."CAMPAIGN_HISTORY" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.CAMPAIGN_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."PIN_HISTORY" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."PIN_PROMOTION_HISTORY" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_PROMOTION_HISTORY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."FIVETRAN_PINTEREST_ADS"."PIN_PROMOTION_REPORT" TO ROLE "RAW.FIVETRAN_GOOGLE_SHEETS.PIN_PROMOTION_REPORT.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.AD_GROUP_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.ADVERTISER_REPORT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.AUDIENCE_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.CAMPAIGN_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_PINTEREST_ADS.PIN_PROMOTION_HISTORY.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;
GRANT ROLE "RAW.FIVETRAN_GOOGLE_SHEETS.PIN_PROMOTION_REPORT.no_pii.table.reader" TO ROLE "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE  "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role"  TO ROLE DBT_DEV;
GRANT ROLE  "RAW.FIVETRAN_PINTEREST_ADS.no_pii.reader.role"  TO ROLE DBT_PROD;




-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA FIVETRAN_PINTEREST_ADS;

show grants on schema FIVETRAN_PINTEREST_ADS;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."FIVETRAN_PINTEREST_ADS"."AD_GROUP_HISTORY"
-- TRANSFORMER HAS SELECTS update and delete DIRECTLY ON THE TABLEs