-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- 0 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 1 PII TABLE-- 1 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.SILVERPOP_HISTORICAL.STG_SILVERPOP_EVENTS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA SILVERPOP_HISTORICAL;


CREATE OR REPLACE VIEW VW_STG_SILVERPOP_EVENTS  COPY GRANTS  AS
(

  SELECT
        EVENT_ID	,
        RECIPIENT_ID	,
        MAILING_ID	,
        REPORT_ID	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS  EMAIL_ADDRESS,
        EVENT_TYPE	,
        EVENT_TIMESTAMP	,
        BODY_TYPE	,
        CLICK_NAME	,
        CLICK_URL	,
        SUPPRESSION_REASON	,
        MAILING_NAME	,
        MAILING_SUBJECT

  FROM STG_SILVERPOP_EVENTS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.SILVERPOP_HISTORICAL TO ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.SILVERPOP_HISTORICAL.STG_SILVERPOP_EVENTS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."SILVERPOP_HISTORICAL"."VW_STG_SILVERPOP_EVENTS" TO ROLE "RAW.SILVERPOP_HISTORICAL.STG_SILVERPOP_EVENTS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.SILVERPOP_HISTORICAL.STG_SILVERPOP_EVENTS.no_pii.view.reader" TO ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.SILVERPOP_HISTORICAL.no_pii.reader.role"    TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA SILVERPOP_HISTORICAL;

show grants on schema SILVERPOP_HISTORICAL;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."SILVERPOP_HISTORICAL"."STG_SILVERPOP_EVENTS"
-- TRANSFORMER HAS OWNERSHIP DIRECTLY ON THE TABLE