-- UPDATE PLAN
-- 10 TABLES ARE BEING USED BY DBT
-- 8 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 2 PII TABLE-- CREATE THE 2 VIEWS FOR THE PII TABLE. CREATE A READ ROLE FOR IT
-- ADD THE 8 TABLES AND 2 VIEW ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.DYNAMODB.PROD_CONCIERGE_EVENTS
--RAW.DYNAMODB.PROD_LEADS_LEAD_ERROR_LOG
--RAW.DYNAMODB.PROD_LOCATION_REVIEWS_LOCATIONS
--RAW.DYNAMODB.PROD_LOCATION_REVIEWS_REVIEWS
--RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG
--RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG
--RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG
--RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG
--RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG
--RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA DYNAMODB;

CREATE OR REPLACE VIEW VW_PROD_LOCATION_REVIEWS_REVIEWS  COPY GRANTS  AS
(
  SELECT
      COMMENT	,
      CREATE_TIME ,
      _FIVETRAN_DELETED	,
      UPDATE_TIME	,
      REVIEW_REPLY	,
      STAR_RATING	,
      REVIEW_ID	,
      STORE_CODE	,
      CASE WHEN PII_ACCESS = TRUE THEN REVIEWER
           ELSE
                PARSE_JSON(
                            REPLACE(
                                    REVIEWER, REVIEWER:DisplayName, sha2(REVIEWER:DisplayName,512)
                                   )
                          )
      END AS REVIEWER,
      STAR_RATING_AS_INT,
      NAME	,
      _FIVETRAN_SYNCED

  FROM PROD_LOCATION_REVIEWS_REVIEWS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

CREATE OR REPLACE VIEW VW_PROD_CONCIERGE_EVENTS  COPY GRANTS  AS
(
  SELECT
        TYPE,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE  sha2(EMAIL,512)  END AS EMAIL,
        _FIVETRAN_DELETED,
        EXPIRATION	,
        PAYLOAD	,
        CASE_ID ,
        _FIVETRAN_SYNCED	,
        TIMESTAMP

  FROM PROD_CONCIERGE_EVENTS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.DYNAMODB.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.DYNAMODB TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND VIEW ROLEs
CREATE ROLE "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.PROD_LEADS_LEAD_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_LOCATIONS.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
CREATE ROLE "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";

CREATE ROLE "RAW.DYNAMODB.PROD_CONCIERGE_EVENTS.no_pii.view.reader";
CREATE ROLE "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_REVIEWS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."STAGE_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG" TO ROLE   "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."STAGE_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG" TO ROLE  "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."PROD_LEADS_LEAD_ERROR_LOG" TO ROLE  "RAW.DYNAMODB.PROD_LEADS_LEAD_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."PROD_LOCATION_REVIEWS_LOCATIONS" TO ROLE "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_LOCATIONS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."PROD_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG" TO ROLE  "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."PROD_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG" TO ROLE "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."QA_1_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG" TO ROLE "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."DYNAMODB"."QA_1_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG" TO ROLE "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader";

GRANT SELECT ON VIEW "RAW"."DYNAMODB"."VW_PROD_CONCIERGE_EVENTS" TO ROLE "RAW.DYNAMODB.PROD_CONCIERGE_EVENTS.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."DYNAMODB"."VW_PROD_LOCATION_REVIEWS_REVIEWS" TO ROLE "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_REVIEWS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE  "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.STAGE_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.PROD_LEADS_LEAD_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_LOCATIONS.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.PROD_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_CASE_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE  "RAW.DYNAMODB.QA_1_ORTHODONTIC_ORTHODONTIC_ORDER_ERROR_LOG.no_pii.table.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;

GRANT ROLE "RAW.DYNAMODB.PROD_CONCIERGE_EVENTS.no_pii.view.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;
GRANT ROLE "RAW.DYNAMODB.PROD_LOCATION_REVIEWS_REVIEWS.no_pii.view.reader" TO ROLE "RAW.DYNAMODB.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.DYNAMODB.no_pii.reader.role"  TO ROLE DBT_DEV;
GRANT ROLE "RAW.DYNAMODB.no_pii.reader.role"  TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA DYNAMODB;


-- TRANSFORMER ROLE HERE HAS ALL RIGHTS ON THE SCHEMA
show grants on schema DYNAMODB;
-- NOTE TRANSFORMER HAS FULL RIGHTS HERE
SHOW GRANTS ON TABLE RAW.DYNAMODB.PROD_CONCIERGE_EVENTS
SHOW GRANTS ON TABLE RAW.DYNAMODB.PROD_LOCATION_REVIEWS_REVIEWS
SHOW GRANTS ON TABLE RAW.DYNAMODB.PROD_LEADS_LEAD_ERROR_LOG


show grants to ROLE AD_HOC ;
show grants ON ROLE AD_HOC;
SECURITYADMIN
transforming_warehouse.analytics.finance.pii.role

SHOW GRANTS ON TABLE RAW.DYNAMODB.PROD_CONCIERGE_EVENTS