-- UPDATE PLAN
-- 8 TABLES ARE BEING USED BY DBT
-- 4 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 4 PII TABLE-- 4 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_CONTACT_KEY_LKU
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_CLAIM_CODE_LOG
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_REWARD_LOG
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_PREFERENCE_CENTER_DE

--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SHOPIFY_GIFT_CARD_CODES
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_LOG_MASTER
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_REPLY_LOG
--RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_LOB_SENDS_MASTER

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_EXACT_TARGET;

CREATE OR REPLACE VIEW VW_DATA_EXTENSION_CONTACT_KEY_LKU COPY GRANTS  AS
(

  SELECT
        CASE_ID	,
        CASE_NUMBER ,
        CATEGORYID	,
        CONTACT_KEY	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS  EMAIL_ADDRESS,
        MODIFIEDDATE	,
        PHONE	,
        USER_ID	,
        _CUSTOMOBJECTKEY	,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION

  FROM DATA_EXTENSION_CONTACT_KEY_LKU
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

CREATE OR REPLACE VIEW VW_DATA_EXTENSION_GC_CLAIM_CODE_LOG COPY GRANTS  AS
(

  SELECT
        CAMPAIGN	,
        CATEGORYID	,
        CLAIMCODE	,
        CLAIMSTATUS	,
        CONTACT_KEY	,
        DATECLAIMED	,
        DATECREATED	,
        EMAILSTATUS	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS  EMAIL_ADDRESS,
        EXTERNALREFID	,
        GUID	,
        MODIFIEDDATE	,
        ORDER_ID	,
        REFERENCEORDERID	,
        UTID	,
        VALUE	,
        _CUSTOMOBJECTKEY	,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION

  FROM DATA_EXTENSION_GC_CLAIM_CODE_LOG
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

CREATE OR REPLACE VIEW VW_DATA_EXTENSION_GC_REWARD_LOG COPY GRANTS  AS
(

  SELECT
        CAMPAIGN	,
        CATEGORYID	,
        CONTACT_KEY	,
        CREATEDAT	,
        CURRENCYCODE	,
        EMAILSTATUS	,
        EMAILTRIGGER	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS  EMAIL_ADDRESS,
        EXTERNALREFID	,
        GUID	,
        ISRESEND	,
        MODIFIEDDATE	,
        NOTES	,
        ORDER_ID	,
        REFERENCEORDERID	,
        REWARDCODE	,
        REWARDLABEL,
        REWARDNAME	,
        REWARDURL	,
        STATUS	,
        UTID	,
        VALUE	,
        _CUSTOMOBJECTKEY	,
        _SDC_BATCHED_AT ,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION

  FROM DATA_EXTENSION_GC_REWARD_LOG
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

CREATE OR REPLACE VIEW VW_DATA_EXTENSION_PREFERENCE_CENTER_DE COPY GRANTS  AS
(

  SELECT
        CATEGORYID	,
        CLUB_MEMBER_EMAIL_LAST_UPDATE	,
        CLUB_MEMBER_EMAIL_OPT_STATUS	,
        CONTACT_KEY	,
        CUSTOMER_EMAIL_LAST_UPDATE	,
        CUSTOMER_EMAIL_OPT_STATUS	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL_ADDRESS ELSE sha2(EMAIL_ADDRESS,512) END AS  EMAIL_ADDRESS,
        LEAD_EMAIL_LAST_UPDATE	,
        LEAD_EMAIL_OPT_STATUS	,
        MODIFIEDDATE	,
        SHOPIFY_EMAIL_LAST_UPDATE	,
        SHOPIFY_EMAIL_OPT_STATUS	,
        SNOOZE_EMAIL,
        SNOOZE_EMAIL_DATE	,
        TRANSACTIONAL_EMAIL_LAST_UPDATE	,
        TRANSACTIONAL_EMAIL_OPT_STATUS	,
        _CUSTOMOBJECTKEY	,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        REFERAFRIEND_EMAIL_OPT_STATUS	,
        REFERAFRIEND_EMAIL_LAST_UPDATE	,
        TRAYSWITCH_EMAIL_OPT_STATUS	,
        TRAYSWITCH_EMAIL_LAST_UPDATE	,
        LANGUAGE_PREFERENCE	,
        PHONE_NUMBER

  FROM DATA_EXTENSION_PREFERENCE_CENTER_DE
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_EXACT_TARGET TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_CONTACT_KEY_LKU.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_CLAIM_CODE_LOG.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_REWARD_LOG.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_PREFERENCE_CENTER_DE.no_pii.view.reader";

CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SHOPIFY_GIFT_CARD_CODES.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_LOG_MASTER.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_REPLY_LOG.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_LOB_SENDS_MASTER.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_EXACT_TARGET"."VW_DATA_EXTENSION_CONTACT_KEY_LKU" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_CONTACT_KEY_LKU.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_EXACT_TARGET"."VW_DATA_EXTENSION_GC_CLAIM_CODE_LOG" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_CLAIM_CODE_LOG.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_EXACT_TARGET"."VW_DATA_EXTENSION_GC_REWARD_LOG" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_REWARD_LOG.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_EXACT_TARGET"."VW_DATA_EXTENSION_PREFERENCE_CENTER_DE" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_PREFERENCE_CENTER_DE.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."STITCH_EXACT_TARGET"."DATA_EXTENSION_SHOPIFY_GIFT_CARD_CODES" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SHOPIFY_GIFT_CARD_CODES.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_EXACT_TARGET"."DATA_EXTENSION_SMS_LOG_MASTER" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_LOG_MASTER.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_EXACT_TARGET"."DATA_EXTENSION_SMS_REPLY_LOG" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_REPLY_LOG.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_EXACT_TARGET"."DATA_EXTENSION_LOB_SENDS_MASTER" TO ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_LOB_SENDS_MASTER.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_CONTACT_KEY_LKU.no_pii.view.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_CLAIM_CODE_LOG.no_pii.view.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_GC_REWARD_LOG.no_pii.view.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_PREFERENCE_CENTER_DE.no_pii.view.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SHOPIFY_GIFT_CARD_CODES.no_pii.table.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_LOG_MASTER.no_pii.table.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_SMS_REPLY_LOG.no_pii.table.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.DATA_EXTENSION_LOB_SENDS_MASTER.no_pii.table.reader" TO ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_EXACT_TARGET.no_pii.reader.role"    TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_EXACT_TARGET;

show grants on schema STITCH_EXACT_TARGET;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."SILVERPOP_HISTORICAL"."STG_SILVERPOP_EVENTS"
-- TRANSFORMER HAS OWNERSHIP DIRECTLY ON THE TABLE