-- UPDATE PLAN
-- 2 TABLES ARE BEING USED BY DBT
-- 0 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 2 PII TABLE-- 2 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.STITCH_INCONTACT.AGENTS
-- RAW.STITCH_INCONTACT.CDR_PLUS_DISPOSITION_NOTES

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_INCONTACT;

CREATE OR REPLACE VIEW VW_AGENTS COPY GRANTS AS
(

  SELECT
        AGENTID	,
        CASE WHEN PII_ACCESS = TRUE THEN USERNAME ELSE sha2(USERNAME,512) END AS  USERNAME,
        CASE WHEN PII_ACCESS = TRUE THEN FIRSTNAME ELSE sha2(FIRSTNAME,512) END AS  FIRSTNAME,
        MIDDLENAME	,
        CASE WHEN PII_ACCESS = TRUE THEN LASTNAME ELSE sha2(LASTNAME,512) END AS  LASTNAME,
        CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS  EMAILADDRESS,
        ISACTIVE	,
        TEAMID	,
        TEAMNAME	,
        REPORTTOID	,
        CASE WHEN PII_ACCESS = TRUE THEN REPORTTONAME ELSE sha2(REPORTTONAME,512) END AS  REPORTTONAME,
        ISSUPERVISOR	,
        LASTLOGIN	,
        LASTUPDATED ,
        LOCATION	,
        CUSTOM1	,
        CUSTOM2 ,
        CUSTOM3	,
        CUSTOM4	,
        CUSTOM5	,
        INTERNALID	,
        PROFILEID	,
        PROFILENAME	,
        TIMEZONE	,
        COUNTRY	,
        COUNTRYNAME	,
        STATE	,
        CITY	,
        CHATREFUSALTIMEOUT	,
        PHONEREFUSALTIMEOUT ,
        WORKITEMREFUSALTIMEOUT	,
        DEFAULTDIALINGPATTERN	,
        DEFAULTDIALINGPATTERNNAME	,
        USETEAMMAXCONCURRENTCHATS	,
        MAXCONCURRENTCHATS	,
        NOTES	,
        CREATEDATE	,
        INACTIVEDATE	,
        HIREDATE	,
        TERMINATIONDATE	,
        HOURLYCOST	,
        REHIRESTATUS	,
        EMPLOYMENTTYPE	,
        EMPLOYMENTTYPENAME	,
        REFERRAL	,
        ATHOME	,
        HIRINGSOURCE	,
        NTLOGINNAME	,
        SCHEDULENOTIFICATION	,
        CASE WHEN PII_ACCESS = TRUE THEN FEDERATEDID ELSE sha2(FEDERATEDID,512) END AS  FEDERATEDID,
        USETEAMEMAILAUTOPARKINGLIMIT	,
        MAXEMAILAUTOPARKINGLIMIT	,
        SIPUSER	,
        SYSTEMUSER	,
        SYSTEMDOMAIN	,
        CRMUSERNAME	,
        USEAGENTTIMEZONE	,
        TIMEDISPLAYFORMAT	,
        SENDEMAILNOTIFICATIONS	,
        APIKEY	,
        TELEPHONE1	,
        TELEPHONE2	,
        USERTYPE	,
        ISWHATIFAGENT	,
        TIMEZONEOFFSET	,
        REQUESTCONTACT	,
        CHATTHRESHOLD	,
        USETEAMCHATTHRESHOLD	,
        EMAILTHRESHOLD	,
        USETEAMEMAILTHRESHOLD	,
        WORKITEMTHRESHOLD	,
        USETEAMWORKITEMTHRESHOLD	,
        CONTACTAUTOFOCUS	,
        USETEAMCONTACTAUTOFOCUS	,
        USETEAMREQUESTCONTACT	,
        VOICETHRESHOLD	,
        RECORDINGNUMBERS	,
        SUBJECT	,
        ISSUER	,
        ISOPENIDPROFILECOMPLETE

  FROM AGENTS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

CREATE OR REPLACE VIEW VW_CDR_PLUS_DISPOSITION_NOTES COPY GRANTS  AS
(

  SELECT
        CONTACT_ID	,
        MASTER_CONTACT_ID	,
        CONTACT_CODE	,
        MEDIA_NAME	,
        CASE WHEN PII_ACCESS = TRUE THEN CONTACT_NAME ELSE sha2(CONTACT_NAME,512) END AS  CONTACT_NAME,
        CASE WHEN PII_ACCESS = TRUE THEN ANI_DIALNUM ELSE sha2(ANI_DIALNUM,512) END AS  ANI_DIALNUM,
        SKILL_NO	,
        SKILL_NAME	,
        CAMPAIGN_NO	,
        CAMPAIGN_NAME	,
        AGENT_NO	,
        CASE WHEN PII_ACCESS = TRUE THEN AGENT_NAME ELSE sha2(AGENT_NAME,512) END AS  AGENT_NAME,
        TEAM_NO	,
        TEAM_NAME	,
        SLA	,
        START_DATE	,
        START_TIME	,
        PREQUEUE	,
        INQUEUE	,
        AGENT_TIME	,
        POSTQUEUE	,
        ACW_TIME	,
        TOTAL_TIME_PLUS_DISPOSITION	,
        ABANDON_TIME	,
        ROUTING_TIME	,
        ABANDON	,
        CALLBACK_TIME	,
        LOGGED	,
        HOLD_TIME	,
        DISP_CODE	,
        DISP_NAME	,
        DISP_COMMENTS	,
        TAGS

  FROM CDR_PLUS_DISPOSITION_NOTES
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_INCONTACT TO ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_INCONTACT.AGENTS.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_INCONTACT.CDR_PLUS_DISPOSITION_NOTES.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_INCONTACT"."VW_AGENTS" TO ROLE "RAW.STITCH_INCONTACT.AGENTS.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_INCONTACT"."VW_CDR_PLUS_DISPOSITION_NOTES" TO ROLE "RAW.STITCH_INCONTACT.CDR_PLUS_DISPOSITION_NOTES.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_INCONTACT.AGENTS.no_pii.view.reader"TO ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_INCONTACT.CDR_PLUS_DISPOSITION_NOTES.no_pii.view.reader" TO ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_INCONTACT.no_pii.reader.role"    TO ROLE DBT_PROD;

-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_INCONTACT;


show grants on schema STITCH_INCONTACT;
STITCHROLE
TRANSFORMER

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS OWNERSHIP DIRECTLY ON THE TABLE