-- UPDATE PLAN
-- 5 TABLES ARE BEING USED BY DBT
-- 4 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 1 PII TABLE-- 1 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.STITCH_NETSUITE.NETSUITE_TRANSACTION

--RAW.STITCH_NETSUITE.NETSUITE_ACCOUNT
--RAW.STITCH_NETSUITE.NETSUITE_CURRENCY_RATE
--RAW.STITCH_NETSUITE.NETSUITE_CUSTOMRECORD_AI_IMPORTED_INVOICES
--RAW.STITCH_NETSUITE.NETSUITE_LOCATION

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_NETSUITE;

CREATE OR REPLACE VIEW VW_NETSUITE_TRANSACTION COPY GRANTS AS
(

  SELECT
        ACCOUNT	,
        ADDRESS	,
        APPLYLIST	,
        APPROVALSTATUS	,
        BALANCE	,
        CASE WHEN PII_ACCESS = TRUE THEN BILLINGADDRESS
        ELSE
          PARSE_JSON(REPLACE(
                              PARSE_JSON(REPLACE(
                                                    PARSE_JSON(
                                                                REPLACE(
                                                                        BILLINGADDRESS, BILLINGADDRESS:addrText, sha2(BILLINGADDRESS:addrText,512)
                                                                        )
                                                               ) ,
                                                   BILLINGADDRESS:addr1, sha2(BILLINGADDRESS:addr1,512)
                                                  )
                                ),
                              BILLINGADDRESS:addrPhone, sha2(BILLINGADDRESS:addrPhone,512)
                            )

                  )
        END AS BILLINGADDRESS,
        BUILDABLE	,
        COMPONENTLIST	,
        CREATEDDATE	,
        CREATEDFROM	,
        CUSTBODY_PP_ACH_ACCOUNT	,
        CUSTBODY_PP_ACH_IS_ACH	,
        CUSTBODY_PP_APPROVAL_STATUS	,
        CUSTBODY_PP_IS_APPROVED	,
        CUSTBODY_PP_IS_PRINTED	,
        CUSTBODY_PP_NO_PROCESS	,
        CUSTBODY_PP_PAYMENT_METHOD	,
        NETSUITE_TRANSACTION.DEPARTMENT	,
        DUEDATE	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS  EMAIL,
        ENTITY ,
        EXPENSELIST	,
        INTERNALID	,
        ITEM	,
        ITEMLIST	,
        LASTMODIFIEDDATE	,
        LINELIST	,
        LOCATION	,
        MEMO	,
        POSTINGPERIOD	,
        PRINTVOUCHER	,
        QUANTITY	,
        SHIPISRESIDENTIAL	,
        CASE WHEN PII_ACCESS = TRUE THEN SHIPPINGADDRESS
        ELSE
            PARSE_JSON(REPLACE(
                                PARSE_JSON(REPLACE(
                                                      PARSE_JSON(
                                                                  REPLACE(
                                                                          SHIPPINGADDRESS, SHIPPINGADDRESS:addrText, sha2(SHIPPINGADDRESS:addrText,512)
                                                                          )
                                                                 ) ,
                                                     SHIPPINGADDRESS:addr1, sha2(SHIPPINGADDRESS:addr1,512)
                                                    )
                                  ),
                                SHIPPINGADDRESS:addrPhone, sha2(SHIPPINGADDRESS:addrPhone,512)
                              )

                    )
        END AS SHIPPINGADDRESS,
        STATUS	,
        SUBSIDIARY	,
        TERMS	,
        TOACH	,
        TOBEEMAILED	,
        TOBEFAXED	,
        TOBEPRINTED	,
        TOTAL	,
        TRANDATE	,
        TRANID	,
        TRANSACTIONNUMBER	,
        UNITS	,
        USERTOTAL	,
        VOIDJOURNAL	,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        _TYPE	,
        CASHBACKLIST	,
        REVERSALDATE	,
        OTHERLIST	,
        REVERSALENTRY	,
        APPROVED	,
        AMOUNT	,
        COSTCOMPONENTLIST	,
        EXTERNALID	,
        ADJLOCATION	,
        ACCOUNTINGAPPROVAL	,
        SUPERVISORAPPROVAL	,
        COMPLETE	,
        CUSTBODY1	,
        UNITCOST	,
        APPLIED	,
        ESTIMATEDTOTALVALUE	,
        UNAPPLIED	,
        INVENTORYVALUE	,
        CREDITLIST	,
        INVENTORYLIST	,
        TOSUBSIDIARY	,
        MESSAGE	,
        ADVANCE	,
        FAX	,
        EMPLOYEE	,
        TRANSFERLOCATION	,
        NEXTAPPROVER	,
        CUSTBODY_PP_AFN_ERROR	,
        BUILT	,
        CUSTBODY_EDI_PACKAGECOUNT	,
        CUSTBODY_EDI_SHIPDATE	,
        CUSTBODY_EDI_ASNSENT	,
        CUSTBODY_EDI_SHIPTOADDRESSLOCATION	,
        CUSTBODY_EDI_EDIORDER	,
        CUSTBODY_EDI_ASNIFONPOREADY	,
        CUSTBODY_EDI_PO	,
        CUSTBODY_EDI_MASTERBOL	,
        CUSTBODY_ZZ_EDI_BODY_DROPPEDTO3PL	,
        CUSTBODY_EDI_INVOICESENT	,
        CUSTBODY_EDI_MASTER_PO	,
        CUSTBODY_EDI_DATE_EARLIESTDEL	,
        CUSTBODY_ZZ_EDI_BODY_DEPARTMENTNAME	,
        CUSTBODY_EDI_POTYPE	,
        ISMULTISHIPTO	,
        SALESEFFECTIVEDATE	,
        SHIPCOMPLETE	,
        OTHERREFNUM	,
        CUSTBODY_ESC_CREATED_DATE,
        CUSTBODY_EDI_855STATUS	,
        SHIPDATE	,
        SOURCE	,
        PACKAGELIST	,
        BILLADDRESSLIST	,
        CUSTBODY_ZZFOBDESCRIPTION	,
        ACTUALSHIPDATE	,
        CUSTBODY_EDI_DATE_CANCEL	,
        CUSTBODY_EDI_AUTO_INVOICE	,
        CUSTBODY_EDI_TOTWEIGHT,
        CUSTBODY_EDI_INVOICEREADY	,
        CUSTBODY_EDI_ASNSENTDATE	,
        CUSTBODY_EDI_PODATE	,
        CUSTBODY_EDI_INVOICEORDER	,
        CUSTBODY_EDI_CARRIERPRONUMBER	,
        FIRMED,
        CUSTBODY_EDI_DEPT,
        SUBTOTAL	,
        SAVEONAUTHDECLINE	,
        CUSTBODY_EDI_SENTDATE	,
        CUSTBODY_EDI_ASNREADY	,
        CUSTBODY_ESC_LAST_MODIFIED_DATE	,
        CUSTBODY_EDI_865STATUS	,
        CUSTBODY_EDI_INVOICE_TYPE	,
        CUSTBODY_ZZ_EDI_BODY_DROPPEDTO3PLDATE	,
        CUSTBODY_EDI_TOTCARTONS	,
        CUSTBODY_EDI_CARRIERTRANSMETHODCODE	,
        CUSTBODY_EDI_DATE_REQUESTEDDELIVERY	,
        CUSTBODY_EDI_SCAC	,
        CUSTBODY_EDI_BOL	,
        TAXTOTAL	,
        ORDERSTATUS	,
        LINKEDTRACKINGNUMBERS	,
        CUSTBODY_EDI_VENDOR	,
        CUSTBODY_CELIGO_ETAIL_ORDER_FULFILLED	,
        CUSTBODY_CELIGO_ETAIL_CHANNEL	,
        CUSTBODY_CELIGO_AMZIO_ORDER_CANCELED	,
        CUSTBODY_CELIGO_ETAIL_AUTO_BILL_EXP	,
        CUSTBODY_EDI_DATE_REQUESTEDSHIP ,
        CUSTBODY_CELIGO_AMZIO_IS_PRIME	,
        CUSTBODY_CELIGO_AMZMCF_CAN_ORDER_EXP	,
        CUSTBODY_CELIGO_AMZMCF_ORDER_EXPORTED	,
        CUSTBODY_CELIGO_ETAIL_SHIP_TOTAL_VAR	,
        CUSTBODY_CELIGO_ETAIL_ORDER_DATE	,
        ALTSHIPPINGCOST	,
        CUSTBODY_CELIGO_PRE_ORDER_SUBMIT_DATA	,
        CUSTBODY_CELIGO_AMZIO_ACCOUNTS	,
        SHIPMETHOD,
        CUSTBODY_CELIGO_ETAIL_ORDER_TOTAL_VAR	,
        SHIPPINGCOST	,
        SHIPPINGTAXCODE	,
        CUSTBODY_CELIGO_ETAIL_ORDER_ID	,
        CUSTBODY_CELIGO_ETAIL_TAX_TOTAL_VAR	,
        CUSTBODY_CELIGO_ETAIL_DISC_TOTAL_VAR	,
        CUSTBODY_3PL_RELEASE_FLAG	,
        CUSTBODY_3PL_RELEASE_STAT	,
        CUSTBODY_CELIGO_ETAIL_BILL_EXP	,
        CUSTBODY_CELIGO_ETAIL_ORDER_EXPORTED	,
        CUSTBODY_CELIGO_ETAIL_CAN_ORDER_EXP	,
        CUSTBODY_CELIGO_ETAIL_REFUND_EXP	,
        CUSTBODY_CELIGO_ETAIL_RISK_ANALYSIS	,
        CUSTBODY_CELIGO_ETAIL_RISK_RATING	,
        CUSTBODY_CELIGO_SHOPIFY_STORE	,
        PAYMENTMETHOD	,
        CUSTBODY_CELIGO_SHOPIFY_STORE_ID	,
        CUSTBODY_CELIGO_SHOPIFY_ORDER_NO	,
        SHIPPINGTAX1RATE	,
        CUSTBODY_CELIGO_SHOPIFY_DISCOUNTCODE	,
        DISCOUNTTOTAL	,
        DISCOUNTITEM	,
        DISCOUNTRATE	,
        CUSTBODY_RETURN_TRACKING_NUMBER	,
        SHIPGROUPLIST	,
        UNDEPFUNDS ,
        REFUNDCHECK	,
        ARACCT	,
        PAYMENT	,
        PENDING	,
        CUSTOMER	,
        PAYMENTLIST	,
        CUSTBODY_REQ_DEL_DATE	,
        TAXITEM	,
        ISTAXABLE	,
        TAXRATE	,
        CUSTBODY_3PL_ORDERID	,
        EXCHANGERATE	,
        CURRENCY	,
        CURRENCYNAME	,
        TAX2TOTAL	,
        CUSTBODY_SC_ORTHODONTIST_NAME	,
        CUSTBODY_SC_ORDER_NO	,
        CUSTBODY_SCID	,
        CUSTBODY_CELIGO_ORDER_CANCEL_SHOPIFY_2	,
        INTERCOTRANSACTION	,
        INTERCOSTATUS	,
        SHIPTO	,
        EXPCOSTDISCPRINT	,
        TIMEDISCPRINT	,
        ITEMCOSTDISCPRINT	,
        CUSTBODY_ZZ_EDI_BODY_CUSTOMERPICKUPDAT	,
        CUSTBODY_EDI_LASTDELDATE	,
        CUSTBODY_EDI_DATE_LATESTSHIP	,
        CUSTBODY_EDI_DATE_EARLIESTSHIP	,
        SHIPPINGTAX2RATE	,
        PAYMENTHOLD	,
        CUSTBODY_PP_CHECK_STUB_INFO	,
        CUSTBODY_CELIGO_ORDER_CANCEL_SHOPIFY	,
        CUSTBODY_CELIGO_ETAIL_REFUND_ID,
        CUSTBODY_CELIGO_AMZIO_SETTLEMENT_SUMRY	,
        CUSTBODY_CELIGO_AMZIO_SHIP_ADJUST_ID	,
        CUSTBODY_CELIGO_AMZIO_SETTLEMENT_ID	,
        CUSTBODY_CELIGO_AMZIO_ORDER_TRAN_LINK	,
        USEMULTICURRENCY	,
        CLASS	,
        SHIPADDRESSLIST	,
        VATREGNUM ,
        CUSTBODY_SDC_CURRENTAPPROVALLEVEL	,
        CUSTBODY_PR_REQUEST_TYPE	,
        CUSTBODY_SDC_REJECTREASON	,
        CUSTBODY_SDC_ROUTED_ADJUSTMENT	,
        CUSTBODY_SDC_CURRENTLEVEL_THRESHOLD	,
        CUSTBODY_SDC_SOURCE	,
        CUSTBODY_SDC_HENRY_SCHEIN	,
        CUSTBODY_SDC_SHOP_MANAGER_PO	,
        CUSTBODY_SDC_DATE_OPERATIONSLEADSET	,
        CUSTBODY_SDC_SMILESHOP_OPERATIONS_COO	,
        CUSTBODY_SDC_DATE_ORDRPRCSD_HNRYSCHN	,
        CUSTBODY_SDC_SHOP_MANAGER_TO	,
        ISBOOKSPECIFIC	,
        ACCOUNTINGBOOK	,
        CUSTBODY_SDC_REJECTED_REQ	,
        CUSTBODY_SDC_CREATE_BULK_PROCESSING	,
        CUSTBODY_SDC_LAST_APPRVREJ_BY	,
        CUSTBODY_9997_IS_FOR_EP_EFT	,
        CUSTBODY_11724_PAY_BANK_FEES	,
        CUSTBODY_9997_AUTOCASH_ASSERTION_FIELD	,
        CUSTBODY_9997_IS_FOR_EP_DD	,
        CUSTBODY_11187_PREF_ENTITY_BANK	,
        CUSTBODY_CELIGO_AMZIO_SHIP_PLAN_EXPRTD	,
        CUSTBODY_CELIGO_AMZIO_RECEIVED_PLAN	,
        CUSTBODY_CELIGO_AMZIO_SHIP_EXPRTD	,
        CUSTBODY_PP_APN_HAS_CHECK_IMAGES	,
        CUSTBODY_SDC_IS_AMZ_PRIME	,
        CUSTBODY_SDC_SC_ORDER_TYPE	,
        ASSEMBLYITEM	,
        CUSTBODY_SDC_ETAIL_ORDER_ID	,
        CUSTBODY_SDC_SALES_CHANNEL	,
        CUSTBODY_SDC_INTERCOMP_TO_REF	,
        CUSTBODY_SDC_SHIP_TAX_RATE	,
        CUSTBODY_SDC_LOT_NUMBER ,
        CUSTBODY_DSI_MC_USERNAME	,
        CUSTBODY_SDC_SHIPPING_SERVICE	,
        CUSTBODY_SDC_SHIPPING_COST ,
        CUSTBODY_SDC_SHIP_CODE,
        CUSTBODY_SDC_BULK_TRANSACTION_TAG	,
        CUSTBODY_SDC_ORG_SUB ,
        CUSTBODY_SDC_SALES_CHANNEL_REFUND	,
        CUSTBODY_SDC_IFS_REFRENECE	,
        CUSTBODY_SDC_EDI_DEPARTMENT_NUMBER	,
        CUSTBODY_SDC_EDI_PURCHASE_ORDER_TYPE	,
        CUSTBODY_SDC_EDI_MERCHANDISE_TYPE	,
        CUSTBODY_SDC_EDI_MERCHANDISE_ALLOW_AMT	,
        CUSTBODY_SDC_EDI_WAREHOUSE_ALLOW_AMT	,
        CUSTBODY_SDC_EDI_WAREHOUSE_ALLOW_PER	,
        CUSTBODY_SDC_EDI_MERCHANDISE_ALLOW_PER	,
        CUSTBODY_SDC_AMZ_SETT_TRAN	,
        CUSTBODY_SDC_AMZ_SETT_SUM	,
        CUSTBODY_9997_PFA_RECORD	,
        CUSTBODY_SDC_EDI_SHIP_NO_LATER	,
        CUSTBODY_SDC_EDI_DO_NOT_DELIVER_AFTER	,
        CUSTBODY_SDC_EDI_SHIP_NOT_BEFORE

  FROM NETSUITE_TRANSACTION
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_NETSUITE TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_NETSUITE.NETSUITE_TRANSACTION.no_pii.view.reader";

CREATE ROLE "RAW.STITCH_NETSUITE.NETSUITE_ACCOUNT.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_NETSUITE.NETSUITE_CURRENCY_RATE.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_NETSUITE.NETSUITE_CUSTOMRECORD_AI_IMPORTED_INVOICES.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_NETSUITE.NETSUITE_LOCATION.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_NETSUITE"."VW_NETSUITE_TRANSACTION" TO ROLE "RAW.STITCH_NETSUITE.NETSUITE_TRANSACTION.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."STITCH_NETSUITE"."NETSUITE_ACCOUNT" TO ROLE "RAW.STITCH_NETSUITE.NETSUITE_ACCOUNT.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_NETSUITE"."NETSUITE_CURRENCY_RATE" TO ROLE "RAW.STITCH_NETSUITE.NETSUITE_CURRENCY_RATE.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_NETSUITE"."NETSUITE_CUSTOMRECORD_AI_IMPORTED_INVOICES" TO ROLE "RAW.STITCH_NETSUITE.NETSUITE_CUSTOMRECORD_AI_IMPORTED_INVOICES.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_NETSUITE"."NETSUITE_LOCATION" TO ROLE "RAW.STITCH_NETSUITE.NETSUITE_LOCATION.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_NETSUITE.NETSUITE_ACCOUNT.no_pii.table.reader" TO ROLE  "RAW.STITCH_NETSUITE.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_NETSUITE.NETSUITE_TRANSACTION.no_pii.view.reader" TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_NETSUITE.NETSUITE_CURRENCY_RATE.no_pii.table.reader" TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_NETSUITE.NETSUITE_CUSTOMRECORD_AI_IMPORTED_INVOICES.no_pii.table.reader" TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_NETSUITE.NETSUITE_LOCATION.no_pii.table.reader" TO ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role" ;


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role"     TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_NETSUITE.no_pii.reader.role"     TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_NETSUITE;

show grants on schema STITCH_NETSUITE;
STITCH_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."STITCH_NETSUITE"."NETSUITE_TRANSACTION"
-- TRANSFORMER HAS OWNE