-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- 1 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

-- RAW.OUTBRAIN.CAMPAIGN_PERFORMANCE

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA OUTBRAIN;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.OUTBRAIN.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.OUTBRAIN.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.OUTBRAIN TO ROLE "RAW.OUTBRAIN.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.OUTBRAIN.CAMPAIGN_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."OUTBRAIN"."CAMPAIGN_PERFORMANCE" TO ROLE "RAW.OUTBRAIN.CAMPAIGN_PERFORMANCE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.OUTBRAIN.CAMPAIGN_PERFORMANCE.no_pii.table.reader" TO ROLE "RAW.OUTBRAIN.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.OUTBRAIN.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.OUTBRAIN.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA OUTBRAIN

show grants on schema OUTBRAIN;
FIVETRAN_ROLE
TRANSFORMER



show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs