-- UPDATE PLAN
-- 6 TABLES ARE BEING USED BY DBT
-- 4 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 2 PII TABLE-- 2 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.STITCH_STRIPE_AUS.PAYOUT_TRANSACTIONS
--RAW.STITCH_STRIPE_AUS.PAYOUTS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_STRIPE_AUS;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_STRIPE_AUS TO ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_STRIPE_AUS.PAYOUT_TRANSACTIONS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_STRIPE_AUS.PAYOUTS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUT_TRANSACTIONS" TO ROLE "RAW.STITCH_STRIPE_AUS.PAYOUT_TRANSACTIONS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUTS" TO ROLE "RAW.STITCH_STRIPE_AUS.PAYOUTS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_STRIPE_AUS.PAYOUT_TRANSACTIONS.no_pii.table.reader" TO ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_STRIPE_AUS.PAYOUTS.no_pii.table.reader" TO ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_STRIPE_AUS.no_pii.reader.role"    TO ROLE DBT_PROD;

--######################################################

--RAW.STITCH_STRIPE_CA.STRIPE_TRANSFER_TRANSACTIONS
--RAW.STITCH_STRIPE_CA.STRIPE_CHARGES


USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_STRIPE_CA;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_STRIPE_CA TO ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_STRIPE_CA.STRIPE_TRANSFER_TRANSACTIONS.no_pii.table.reader";
CREATE ROLE "RAW.STITCH_STRIPE_CA.STRIPE_CHARGES.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_CA"."STRIPE_TRANSFER_TRANSACTIONS" TO ROLE "RAW.STITCH_STRIPE_CA.STRIPE_TRANSFER_TRANSACTIONS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_CA"."STRIPE_CHARGES" TO ROLE "RAW.STITCH_STRIPE_CA.STRIPE_CHARGES.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_STRIPE_CA.STRIPE_TRANSFER_TRANSACTIONS.no_pii.table.reader" TO ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_STRIPE_CA.STRIPE_CHARGES.no_pii.table.reader" TO ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_STRIPE_CA.no_pii.reader.role"    TO ROLE DBT_PROD;

--######################################################
--######################################################

--RAW.STITCH_STRIPE.STRIPE_CHARGES
--RAW.STITCH_STRIPE.STRIPE_CUSTOMERS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_STRIPE;


CREATE OR REPLACE VIEW VW_STRIPE_CHARGES  COPY GRANTS  AS
(
    SELECT
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        AMOUNT	,
        AMOUNT_REFUNDED	,
        BALANCE_TRANSACTION	,
        CAPTURED	,
        CARD__ADDRESS_CITY	,
        CARD__ADDRESS_COUNTRY	,
        CARD__ADDRESS_LINE1	,
        CARD__ADDRESS_LINE1_CHECK	,
        CARD__ADDRESS_LINE2 ,
        CARD__ADDRESS_STATE	,
        CARD__ADDRESS_ZIP	,
        CARD__ADDRESS_ZIP_CHECK	,
        CARD__BRAND	,
        CARD__COUNTRY	,
        CARD__CUSTOMER	,
        CARD__CVC_CHECK	,
        CARD__EXP_MONTH	,
        CARD__EXP_YEAR	,
        CARD__FINGERPRINT	,
        CARD__FUNDING	,
        CARD__ID	,
        CARD__LAST4	,
        CARD__NAME	,
        CARD__OBJECT	,
        CREATED	,
        CURRENCY	,
        CUSTOMER	,
        DISPUTE__AMOUNT	,
        DISPUTE__BALANCE_TRANSACTION	,
        DISPUTE__CHARGE	,
        DISPUTE__CREATED	,
        DISPUTE__CURRENCY,
        DISPUTE__EVIDENCE_DETAILS__DUE_BY	,
        DISPUTE__EVIDENCE_DETAILS__HAS_EVIDENCE	,
        DISPUTE__EVIDENCE_DETAILS__PAST_DUE ,
        DISPUTE__EVIDENCE_DETAILS__SUBMISSION_COUNT	,
        DISPUTE__EVIDENCE_DUE_BY	,
        DISPUTE__ID	,
        DISPUTE__IS_CHARGE_REFUNDABLE	,
        DISPUTE__LIVEMODE,
        DISPUTE__OBJECT	,
        DISPUTE__REASON	,
        DISPUTE__STATUS	,
        FAILURE_CODE	,
        FAILURE_MESSAGE	,
        FRAUD_DETAILS__STRIPE_REPORT	,
        ID	,
        LIVEMODE	,
        METADATA__ORDER_PAYMENT_UUID	,
        OBJECT	,
        OUTCOME__NETWORK_STATUS	,
        OUTCOME__REASON	,
        OUTCOME__RULE__ACTION	,
        OUTCOME__RULE__ID	,
        OUTCOME__RULE__PREDICATE	,
        OUTCOME__SELLER_MESSAGE	,
        OUTCOME__TYPE	,
        PAID	,
        CASE WHEN PII_ACCESS = TRUE THEN RECEIPT_EMAIL ELSE sha2(RECEIPT_EMAIL,512) END AS RECEIPT_EMAIL,
        RECEIPT_NUMBER	,
        REFUNDED	,
        REFUNDS__HAS_MORE	,
        REFUNDS__OBJECT	,
        REFUNDS__TOTAL_COUNT	,
        REFUNDS__URL	,
        SOURCE__ADDRESS_CITY	,
        SOURCE__ADDRESS_COUNTRY	,
        SOURCE__ADDRESS_LINE1	,
        SOURCE__ADDRESS_LINE1_CHECK	,
        SOURCE__ADDRESS_LINE2	,
        SOURCE__ADDRESS_STATE	,
        SOURCE__ADDRESS_ZIP	,
        SOURCE__ADDRESS_ZIP_CHECK	,
        SOURCE__BRAND	,
        SOURCE__COUNTRY	,
        SOURCE__CUSTOMER	,
        SOURCE__CVC_CHECK	,
        SOURCE__EXP_MONTH	,
        SOURCE__EXP_YEAR	,
        SOURCE__FINGERPRINT	,
        SOURCE__FUNDING	,
        SOURCE__ID	,
        SOURCE__LAST4	,
        SOURCE__NAME	,
        SOURCE__OBJECT	,
        STATEMENT_DESCRIPTION	,
        STATEMENT_DESCRIPTOR	,
        STATUS	,
        SOURCE__TYPE	,
        CARD__TYPE	,
        OUTCOME__RISK_LEVEL	,
        APPLICATION	,
        FRAUD_DETAILS__USER_REPORT	,
        DISPUTE__COVERED_BY_DISPUTE_PROTECTION ,
        DESCRIPTION	,
        REVIEW	,
        DISPUTE__EVIDENCE	,
        CASE WHEN PII_ACCESS = TRUE THEN SOURCE
             WHEN IS_NULL_VALUE(SOURCE:name) THEN SOURCE
             ELSE
                PARSE_JSON(
                    REPLACE(
                            SOURCE, SOURCE:name, sha2(SOURCE:name,512)
                            )
                   )
        END AS SOURCE	,
        CASE WHEN PII_ACCESS = TRUE THEN CARD
             WHEN IS_NULL_VALUE(CARD:name) THEN CARD
             ELSE
                PARSE_JSON(
                    REPLACE(
                            CARD, CARD:name, sha2(CARD:name,512)
                            )
                   )
        END AS CARD	,
        FRAUD_DETAILS	,
        METADATA	,
        REFUNDS	,
        DISPUTE	,
        OUTCOME	,
        APPLICATION_FEE_AMOUNT	,
        RECEIPT_URL	,
        PAYMENT_METHOD_DETAILS	,
        BILLING_DETAILS	,
        PAYMENT_METHOD	,
        PAYMENT_INTENT,
        DISPUTED

  FROM STRIPE_CHARGES
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


--######
--THIS CURRENTLY ISNOT WORKING AND WILL HAVE TO REVISIT

CREATE OR REPLACE VIEW VW_STRIPE_CUSTOMERS  COPY GRANTS  AS
(
    SELECT
        ACCOUNT_BALANCE	,
        CARDS	,
        CREATED	,
        DEFAULT_CARD	,
        DEFAULT_SOURCE	,
        DELINQUENT ,
        CASE WHEN PII_ACCESS = TRUE THEN DESCRIPTION ELSE sha2(DESCRIPTION,512) END AS DESCRIPTION,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL,
        ID	,
        LIVEMODE	,
        METADATA	,
        OBJECT	,
        --PARSE_JSON(
        --            REPLACE(
         ----                  SOURCES, SOURCES:data[0]:name, sha2(SOURCES:data[0]:name,512)
         --                   )
         --          ) AS SOURCES2	,
        SOURCES,
        SUBSCRIPTIONS	,
        _SDC_BATCHED_AT	,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        CURRENCY	,
        INVOICE_PREFIX	,
        SHIPPING	,
        INVOICE_SETTINGS	,
        PREFERRED_LOCALES	,
        TAX_IDS	,
        TAX_EXEMPT	,
        NAME	,
        BALANCE	,
        ADDRESS	,
        PHONE

  FROM STRIPE_CUSTOMERS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_STRIPE.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_STRIPE.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_STRIPE TO ROLE "RAW.STITCH_STRIPE.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_STRIPE.STRIPE_CHARGES.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_STRIPE.STRIPE_CUSTOMERS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_STRIPE"."VW_STRIPE_CHARGES" TO ROLE "RAW.STITCH_STRIPE.STRIPE_CHARGES.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_STRIPE"."VW_STRIPE_CUSTOMERS" TO ROLE "RAW.STITCH_STRIPE.STRIPE_CUSTOMERS.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_STRIPE.STRIPE_CHARGES.no_pii.view.reader" TO ROLE  "RAW.STITCH_STRIPE.no_pii.reader.role" ;
GRANT ROLE "RAW.STITCH_STRIPE.STRIPE_CUSTOMERS.no_pii.view.reader" TO ROLE "RAW.STITCH_STRIPE.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_STRIPE.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_STRIPE.no_pii.reader.role"    TO ROLE DBT_PROD;

-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_STRIPE;

show grants on schema STITCH_STRIPE;
STITCH_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."STITCH_STRIPE"."STRIPE_CHARGES"
-- TRANSFORMER HAS OWNE