-- UPDATE PLAN
-- 14 TABLES ARE BEING USED BY DBT
-- 14 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.MARKETING_UPLOADS.DATAXU_GEOSPEND
--RAW.MARKETING_UPLOADS.MARKETING_CAMPAIGN_LKU
--RAW.MARKETING_UPLOADS.NIELSEN_DMA_CODE_LOOKUP
--RAW.MARKETING_UPLOADS.ORDER_FORECASTS
--RAW.MARKETING_UPLOADS.PANDORA_SPEND
--RAW.MARKETING_UPLOADS.PANDORA_SPEND_2
--RAW.MARKETING_UPLOADS.PODIUM_COMPETITOR_DATA
--RAW.MARKETING_UPLOADS.PODIUM_SDC_SHOPS
--RAW.MARKETING_UPLOADS.SHOPIFY_DISCOUNTS_EXPORT_20190916
--RAW.MARKETING_UPLOADS.SILVERPOP_RECIPIENT_ID_DECODING
--RAW.MARKETING_UPLOADS.SPEND_UPLOADS_FORECAST
--RAW.MARKETING_UPLOADS.SPEND_UPLOADS_KIT_SCAN_FORECAST
--RAW.MARKETING_UPLOADS.YELP_COMPETITOR
--RAW.MARKETING_UPLOADS.YELP_REVIEWS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA MARKETING_UPLOADS;


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.MARKETING_UPLOADS TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.MARKETING_UPLOADS.DATAXU_GEOSPEND.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.MARKETING_CAMPAIGN_LKU.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.NIELSEN_DMA_CODE_LOOKUP.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.ORDER_FORECASTS.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND_2.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.PODIUM_COMPETITOR_DATA.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.PODIUM_SDC_SHOPS.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.SHOPIFY_DISCOUNTS_EXPORT_20190916.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.SILVERPOP_RECIPIENT_ID_DECODING.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_FORECAST.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_KIT_SCAN_FORECAST.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.YELP_COMPETITOR.no_pii.table.reader";
CREATE ROLE "RAW.MARKETING_UPLOADS.YELP_REVIEWS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."DATAXU_GEOSPEND" TO ROLE "RAW.MARKETING_UPLOADS.DATAXU_GEOSPEND.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."MARKETING_CAMPAIGN_LKU" TO ROLE "RAW.MARKETING_UPLOADS.MARKETING_CAMPAIGN_LKU.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."NIELSEN_DMA_CODE_LOOKUP" TO ROLE "RAW.MARKETING_UPLOADS.NIELSEN_DMA_CODE_LOOKUP.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."ORDER_FORECASTS" TO ROLE  "RAW.MARKETING_UPLOADS.ORDER_FORECASTS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."PANDORA_SPEND" TO ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."PANDORA_SPEND_2" TO ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND_2.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."PODIUM_COMPETITOR_DATA" TO ROLE "RAW.MARKETING_UPLOADS.PODIUM_COMPETITOR_DATA.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."PODIUM_SDC_SHOPS" TO ROLE "RAW.MARKETING_UPLOADS.PODIUM_SDC_SHOPS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."SHOPIFY_DISCOUNTS_EXPORT_20190916" TO ROLE "RAW.MARKETING_UPLOADS.SHOPIFY_DISCOUNTS_EXPORT_20190916.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."SILVERPOP_RECIPIENT_ID_DECODING" TO ROLE "RAW.MARKETING_UPLOADS.SILVERPOP_RECIPIENT_ID_DECODING.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."SPEND_UPLOADS_FORECAST" TO ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_FORECAST.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."SPEND_UPLOADS_KIT_SCAN_FORECAST" TO ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_KIT_SCAN_FORECAST.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."YELP_COMPETITOR" TO ROLE "RAW.MARKETING_UPLOADS.YELP_COMPETITOR.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."MARKETING_UPLOADS"."YELP_REVIEWS" TO ROLE "RAW.MARKETING_UPLOADS.YELP_REVIEWS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.MARKETING_UPLOADS.DATAXU_GEOSPEND.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.MARKETING_CAMPAIGN_LKU.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.NIELSEN_DMA_CODE_LOOKUP.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.ORDER_FORECASTS.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.PANDORA_SPEND_2.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.PODIUM_COMPETITOR_DATA.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.PODIUM_SDC_SHOPS.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.SHOPIFY_DISCOUNTS_EXPORT_20190916.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.SILVERPOP_RECIPIENT_ID_DECODING.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_FORECAST.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.SPEND_UPLOADS_KIT_SCAN_FORECAST.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.YELP_COMPETITOR.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";
GRANT ROLE "RAW.MARKETING_UPLOADS.YELP_REVIEWS.no_pii.table.reader" TO ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role";

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.MARKETING_UPLOADS.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA MARKETING_UPLOADS;

show grants on schema MARKETING_UPLOADS;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS SELECTS DIRECTLY ON THE TABLEs