-- UPDATE PLAN
-- 7 TABLES ARE BEING USED BY DBT
-- 4 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 3 PII TABLE-- 2 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES


--RAW.PEOPLE_SUPPORT.CANDIDATE_DATA
--RAW.PEOPLE_SUPPORT.SPARKHIRE
--RAW.PEOPLE_SUPPORT.TEAM_MEMBERS

--RAW.PEOPLE_SUPPORT.CANDIDATE_EXPERIENCE_SURVEY
--RAW.PEOPLE_SUPPORT.JOB_DATA
--RAW.PEOPLE_SUPPORT.LINKEDIN
--RAW.PEOPLE_SUPPORT.ONBOARDING


USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA PEOPLE_SUPPORT;


CREATE OR REPLACE VIEW VW_CANDIDATE_DATA  COPY GRANTS  AS
(
  SELECT
        TA_OWNER,
        HIRING_MANAGER	,
        CANDIDATE_DATA.DEPARTMENT	,
        JOB_TITLE	,
        JOB_ID	,
        INTERNAL_JOB_NAME	,
        JOB_TYPE	,
        AVAILABLE_POSITIONS	,
        PRIORITY	,
        SCOPE	,
        OPENED_DATE	,
        JOB_DATE_CREATED	,
        CITY_STATE_PROVINCE,
        COUNTRY	,
        REASON	,
        JOB_STAGE_NAME	,
        JOB_STAGE_TYPE	,
        FILLED_DATE	,
        RECRUITMENT_TYPE	,
        _CANDIDATES	,
        JOB_OWNER_S_	,
        JOB_NAME	,
        JOB_LAST_MODIFIED	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL,
        DATE_CREATED	,
        CASE WHEN PII_ACCESS = TRUE THEN CANDIDATE_NAME ELSE sha2(CANDIDATE_NAME,512) END AS  CANDIDATE_NAME,
        CASE WHEN PII_ACCESS = TRUE THEN PHONE ELSE sha2(PHONE,512) END AS  PHONE,
        CITY,
        STATE	,
        STAGE_NAME	,
        DISPOSITION	,
        DATE_NEW	,
        DATE_RECRUITER_REVIEW	,
        DATE_INTERVIEW_1	,
        DATE_PHONE_SCREEN_REQUESTED	,
        DATE_INTERVIEW_FINAL	,
        DATE_REFERENCE_CHECK	,
        DATE_JOB_OFFER	,
        DATE_SENT_TO_ONBOARDING	,
        DATE_FUTURE_POTENTIAL	,
        DATE_NOT_CONSIDERED	,
        DATE_NOT_SELECTED	,
        DATE_WITHDRAWN	,
        SOURCE	,
        REFERRED_BY	,
        LAST_MODIFIED	,
        DATE_PHONE_SCREEN_SCHEDULED	,
        DATE_SPARKHIRE	,
        DATE_SUBMITTED_TO_HM	,
        DATE_INTERVIEW_2	,
        DATE_CONSIDERED_ON_ANOTHER_JOB	,
        DATE_OFFER_DECLINED	,
        DATE_DO_NOT_PURSE	,
        TEAM	,
        UNIQUE_SYSTEM_ID	,
        DATE_VIDEO_INTERVIEW

  FROM CANDIDATE_DATA
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

CREATE OR REPLACE VIEW VW_SPARKHIRE  COPY GRANTS  AS
(
  SELECT
        CASE WHEN PII_ACCESS = TRUE THEN CANDIDATE_NAME ELSE sha2(CANDIDATE_NAME,512) END AS  CANDIDATE_NAME,
        CASE WHEN PII_ACCESS = TRUE THEN CANDIDATE_EMAIL ELSE sha2(CANDIDATE_EMAIL,512) END AS  CANDIDATE_EMAIL,
        JOB,
        JOB_LOCATION	,
        STATUS	,
        TYPE	,
        RATING	,
        SCHEDULED_AT	,
        ACCEPTED_AT	,
        COMPLETED_AT	,
        CREATED_AT	,
        CREATED_BY	,
        CREATED_BY_EMAIL

  FROM SPARKHIRE
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

CREATE OR REPLACE VIEW VW_TEAM_MEMBERS COPY GRANTS  AS
(
  SELECT
        TEAM_MEMBER_NUMBER	,
        CASE WHEN PII_ACCESS = TRUE THEN TEAM_MEMBER_NAME ELSE sha2(TEAM_MEMBER_NAME,512) END AS  TEAM_MEMBER_NAME,
        JOB_TITLE	,
        LOCATION	,
        COUNTRY	,
        TEAM	,
        BUSINESS_UNIT	,
        LEADER_NAME	,
        HIRE_DATE	,
        TERMINATION_DATE	,
        TERMINATION_REASON	,
        TERMINATION_TYPE

  FROM TEAM_MEMBERS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.PEOPLE_SUPPORT TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_DATA.no_pii.view.reader";
CREATE ROLE "RAW.PEOPLE_SUPPORT.SPARKHIRE.no_pii.view.reader";
CREATE ROLE "RAW.PEOPLE_SUPPORT.TEAM_MEMBERS.no_pii.view.reader";

CREATE ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_EXPERIENCE_SURVEY.no_pii.table.reader";
CREATE ROLE "RAW.PEOPLE_SUPPORT.JOB_DATA.no_pii.table.reader";
CREATE ROLE "RAW.PEOPLE_SUPPORT.LINKEDIN.no_pii.table.reader";
CREATE ROLE "RAW.PEOPLE_SUPPORT.ONBOARDING.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."PEOPLE_SUPPORT"."VW_CANDIDATE_DATA" TO ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_DATA.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."PEOPLE_SUPPORT"."VW_SPARKHIRE" TO ROLE "RAW.PEOPLE_SUPPORT.SPARKHIRE.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."PEOPLE_SUPPORT"."VW_TEAM_MEMBERS" TO ROLE "RAW.PEOPLE_SUPPORT.TEAM_MEMBERS.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."PEOPLE_SUPPORT"."CANDIDATE_EXPERIENCE_SURVEY" TO ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_EXPERIENCE_SURVEY.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."PEOPLE_SUPPORT"."JOB_DATA" TO ROLE "RAW.PEOPLE_SUPPORT.JOB_DATA.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."PEOPLE_SUPPORT"."LINKEDIN" TO ROLE "RAW.PEOPLE_SUPPORT.LINKEDIN.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."PEOPLE_SUPPORT"."ONBOARDING" TO ROLE "RAW.PEOPLE_SUPPORT.ONBOARDING.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_DATA.no_pii.view.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT ROLE "RAW.PEOPLE_SUPPORT.SPARKHIRE.no_pii.view.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT ROLE "RAW.PEOPLE_SUPPORT.TEAM_MEMBERS.no_pii.view.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;

GRANT ROLE "RAW.PEOPLE_SUPPORT.CANDIDATE_EXPERIENCE_SURVEY.no_pii.table.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT ROLE "RAW.PEOPLE_SUPPORT.JOB_DATA.no_pii.table.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT ROLE "RAW.PEOPLE_SUPPORT.LINKEDIN.no_pii.table.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;
GRANT ROLE "RAW.PEOPLE_SUPPORT.ONBOARDING.no_pii.table.reader" TO ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role"   TO ROLE DBT_DEV;
GRANT ROLE "RAW.PEOPLE_SUPPORT.no_pii.reader.role"   TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA PEOPLE_SUPPORT;

show grants on schema PEOPLE_SUPPORT;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
RAW.PEOPLE_SUPPORT.CANDIDATE_DATA
-- TRANSFORMER HAS SELECTS deletes and updates DIRECTLY ON THE TABLEs

