-- UPDATE PLAN
-- 3 TABLES ARE BEING USED BY DBT
-- 1 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 2 PII TABLE-- 2 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.STITCH_PODIUM.INVITES
--RAW.STITCH_PODIUM.REVIEWS

--RAW.STITCH_PODIUM.LOCATIONS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA STITCH_PODIUM;

CREATE OR REPLACE VIEW VW_INVITES  COPY GRANTS  AS
(
    SELECT
        CREATEDAT	,
        CUSTOMERID	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS  EMAIL,
        ID	,
        LASTINVITATIONSENT	,
        LOCATIONID	,
        ORGANIZATIONID	,
        CASE WHEN PII_ACCESS = TRUE THEN PHONENUMBER ELSE sha2(PHONENUMBER,512) END AS  PHONENUMBER,
        REVIEWPAGEURL	,
        TEST	,
        UPDATEDAT	,
        USERID	,
        _SDC_BATCHED_AT ,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        UID

  FROM INVITES
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

CREATE OR REPLACE VIEW VW_REVIEWS COPY GRANTS  AS
(
    SELECT
        CASE WHEN PII_ACCESS = TRUE THEN AUTHOR ELSE sha2(AUTHOR,512) END AS  AUTHOR,
        CREATEDAT	,
        ID	,
        LOCATIONID ,
        PUBLISHDATE	,
        RATING	,
        REVIEWBODY	,
        SITENAME	,
        SITEREVIEWID	,
        UPDATEDAT	,
        _SDC_BATCHED_AT ,
        _SDC_RECEIVED_AT	,
        _SDC_SEQUENCE	,
        _SDC_TABLE_VERSION	,
        REVIEWINVITATIONID	,
        AUTHORID

  FROM REVIEWS
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.STITCH_PODIUM.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.STITCH_PODIUM.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.STITCH_PODIUM TO ROLE "RAW.STITCH_PODIUM.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.STITCH_PODIUM.INVITES.no_pii.view.reader";
CREATE ROLE "RAW.STITCH_PODIUM.REVIEWS.no_pii.view.reader";

CREATE ROLE "RAW.STITCH_PODIUM.LOCATIONS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON VIEW "RAW"."STITCH_PODIUM"."VW_INVITES" TO ROLE "RAW.STITCH_PODIUM.INVITES.no_pii.view.reader";
GRANT SELECT ON VIEW "RAW"."STITCH_PODIUM"."VW_REVIEWS" TO ROLE "RAW.STITCH_PODIUM.REVIEWS.no_pii.view.reader";

GRANT SELECT ON TABLE "RAW"."STITCH_PODIUM"."LOCATIONS" TO ROLE "RAW.STITCH_PODIUM.LOCATIONS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.STITCH_PODIUM.INVITES.no_pii.view.reader" TO ROLE  "RAW.STITCH_PODIUM.no_pii.reader.role";
GRANT ROLE "RAW.STITCH_PODIUM.REVIEWS.no_pii.view.reader" TO ROLE "RAW.STITCH_PODIUM.no_pii.reader.role";
GRANT ROLE "RAW.STITCH_PODIUM.LOCATIONS.no_pii.table.reader" TO ROLE "RAW.STITCH_PODIUM.no_pii.reader.role";


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.STITCH_PODIUM.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.STITCH_PODIUM.no_pii.reader.role"    TO ROLE DBT_PROD;


-------############################################################


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA STITCH_PODIUM;

show grants on schema STITCH_PODIUM;
STITCH_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
"RAW"."STITCH_NETSUITE"."NETSUITE_TRANSACTION"
-- TRANSFORMER HAS OWNE