-- UPDATE PLAN
-- 9 TABLES ARE BEING USED BY DBT
-- 9 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE-- 0 VIEWS NEEDED
-- ADD THE  read ROLES TO THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.SMILESHOP_COSTS.SMILESHOP_P_AND_L

--RAW.SMILESHOP_INFO.CVS_LOCATIONS
--RAW.SMILESHOP_INFO.CVS_LOCATIONS_FOR_LOOKER_1_25_19
--RAW.SMILESHOP_INFO.CVS_POTENTIAL_MC_LOCATIONS_12_27_18
--RAW.SMILESHOP_INFO.SMILESHOP_ITEROS_REGIONS_DISTRICTS
--RAW.SMILESHOP_INFO.TYPEFORM_SURVEY_RESULTS
--RAW.SMILESHOP_INFO.WALGREENS_LOCATIONS
--RAW.SMILESHOP_INFO.WG_TEST_LOCATIONS_FOR_LOOKER
--RAW.SMILESHOP_INFO.WMT_CAN_ON_QC_OPTIONS

USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE RAW;
USE SCHEMA SMILESHOP_COSTS;


USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.SMILESHOP_COSTS TO ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.SMILESHOP_COSTS.SMILESHOP_P_AND_L.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."SMILESHOP_COSTS"."SMILESHOP_P_AND_L" TO ROLE "RAW.SMILESHOP_COSTS.SMILESHOP_P_AND_L.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.SMILESHOP_COSTS.SMILESHOP_P_AND_L.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role"     TO ROLE DBT_DEV;
GRANT ROLE "RAW.SMILESHOP_COSTS.no_pii.reader.role"     TO ROLE DBT_PROD;


-------############################################################
USE DATABASE RAW;
USE SCHEMA SMILESHOP_COSTS;

USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.SMILESHOP_INFO TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS_FOR_LOOKER_1_25_19.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.CVS_POTENTIAL_MC_LOCATIONS_12_27_18.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.SMILESHOP_ITEROS_REGIONS_DISTRICTS.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.TYPEFORM_SURVEY_RESULTS.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.WALGREENS_LOCATIONS.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.WG_TEST_LOCATIONS_FOR_LOOKER.no_pii.table.reader";
CREATE ROLE "RAW.SMILESHOP_INFO.WMT_CAN_ON_QC_OPTIONS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."CVS_LOCATIONS" TO ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."CVS_LOCATIONS_FOR_LOOKER_1_25_19" TO ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS_FOR_LOOKER_1_25_19.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."CVS_POTENTIAL_MC_LOCATIONS_12_27_18" TO ROLE "RAW.SMILESHOP_INFO.CVS_POTENTIAL_MC_LOCATIONS_12_27_18.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."SMILESHOP_ITEROS_REGIONS_DISTRICTS" TO ROLE "RAW.SMILESHOP_INFO.SMILESHOP_ITEROS_REGIONS_DISTRICTS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."TYPEFORM_SURVEY_RESULTS" TO ROLE "RAW.SMILESHOP_INFO.TYPEFORM_SURVEY_RESULTS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."WALGREENS_LOCATIONS" TO ROLE "RAW.SMILESHOP_INFO.WALGREENS_LOCATIONS.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."WG_TEST_LOCATIONS_FOR_LOOKER" TO ROLE "RAW.SMILESHOP_INFO.WG_TEST_LOCATIONS_FOR_LOOKER.no_pii.table.reader";
GRANT SELECT ON TABLE "RAW"."SMILESHOP_INFO"."WMT_CAN_ON_QC_OPTIONS" TO ROLE "RAW.SMILESHOP_INFO.WMT_CAN_ON_QC_OPTIONS.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.CVS_LOCATIONS_FOR_LOOKER_1_25_19.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.CVS_POTENTIAL_MC_LOCATIONS_12_27_18.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.SMILESHOP_ITEROS_REGIONS_DISTRICTS.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.TYPEFORM_SURVEY_RESULTS.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.WALGREENS_LOCATIONS.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.WG_TEST_LOCATIONS_FOR_LOOKER.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;
GRANT ROLE "RAW.SMILESHOP_INFO.WMT_CAN_ON_QC_OPTIONS.no_pii.table.reader" TO ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role" ;

-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role"    TO ROLE DBT_DEV;
GRANT ROLE "RAW.SMILESHOP_INFO.no_pii.reader.role"    TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
USE SCHEMA SMILESHOP_COST;
USE SCHEMA SMILESHOP_INFO;

show grants on schema SMILESHOP_INFO;
FIVETRAN_ROLE
TRANSFORMER


show grants to ROLE FIVETRAN_ROLE ;
show grants ON ROLE FIVETRAN_ROLE;

SHOW GRANTS ON TABLE
-- TRANSFORMER HAS OWNERSHIP DIRECTLY ON THE TABLE