-- UPDATE PLAN
-- 1 TABLES ARE BEING USED BY DBT
-- 1 NO_PII TABLES - CREATE THE INDIVIDUAL READ ROLES FOR THESE
-- 0 PII TABLE - CREATE THE INDIVIDUAL READ ROLE FOR THIS
-- ADD THE 1 TABLES  THE NO_PII GROUP ROLE
-- ADD THE NO_PII GROUP ROLE TO BOTH DBT ROLES

--RAW.AIRFLOW_FINANCE.SMILEPAY_INTEREST_SCHEDULE

USE DATABASE RAW;
USE SCHEMA AIRFLOW_FINANCE;
USE ROLE SECURITYADMIN;

-- CREATE THE GROUP ROLES
CREATE ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role" ;

-- ADD PERMISIONS
GRANT USAGE ON DATABASE RAW TO ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role" ;
GRANT USAGE ON SCHEMA RAW.AIRFLOW_FINANCE TO ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role" ;

-- CREATE THE INDIVIDUAL TABLE ROLES AND ONE VIEW ROLE
CREATE ROLE "RAW.AIRFLOW_FINANCE.SMILEPAY_INTEREST_SCHEDULE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO THIER TABLES/VIEW
GRANT SELECT ON TABLE "RAW"."AIRFLOW_FINANCE"."SMILEPAY_INTEREST_SCHEDULE" TO ROLE "RAW.AIRFLOW_FINANCE.SMILEPAY_INTEREST_SCHEDULE.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GrOUP ROLES
GRANT ROLE  "RAW.AIRFLOW_FINANCE.SMILEPAY_INTEREST_SCHEDULE.no_pii.table.reader" TO ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role";


-- ADD GROUP ROLES TO THE DBT ROLE
GRANT ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "RAW.AIRFLOW_FINANCE.no_pii.reader.role" TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

USE WAREHOUSE TRANSFORMING_WAREHOUSE;
USE DATABASE RAW;
show grants on schema AIRFLOW_FINANCE;
