
-- We need to remove the public role select permission on the below tables
-- There is a good chance that at least some if these tables are being using by the analytics team/transformer role
-- But actually only have access cause of the select on public role
-- SO the temp fix here is
-- 1.  GIve transformer select access to the below tables
-- 2.  Remove public
-- 3 . Eventually transformer will be dreprecated and replaced by the dbt roles

USE ROLE SECURITYADMIN;


-- IDENTIFY THE TABLES

-- THESE 4 TABLES HAVE SELECT GIVEN TO PUBLIC ROLE
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_AUS"."CHARGES";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_AUS"."BALANCE_TRANSACTIONS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUTS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUT_TRANSACTIONS";

-- THESE 6 TABLES HAVE SELECT GIVEN TO PUBLIC ROLE
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."CHARGES";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."BALANCE_TRANSACTIONS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUTS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUT_TRANSACTIONS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."EVENTS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_GBR"."_SDC_REJECTED";

-- THESE 6 TABLES HAVE SELECT GIVEN TO PUBLIC ROLE
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."CHARGES";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."BALANCE_TRANSACTIONS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUTS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUT_TRANSACTIONS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."EVENTS";
SHOW GRANTS ON TABLE "RAW"."STITCH_STRIPE_NZL"."_SDC_REJECTED";



-- REMOVE PUBLIC ADD TRANSFORMER

------- STRIPE AUS
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."CHARGES" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."BALANCE_TRANSACTIONS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUTS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUT_TRANSACTIONS" TO ROLE TRANSFORMER;

REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."CHARGES" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."BALANCE_TRANSACTIONS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUTS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_AUS"."PAYOUT_TRANSACTIONS" FROM ROLE PUBLIC;

------ STRIPE GBR
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."CHARGES" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."BALANCE_TRANSACTIONS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUTS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUT_TRANSACTIONS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."EVENTS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."_SDC_REJECTED" TO ROLE TRANSFORMER;

REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."CHARGES" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."BALANCE_TRANSACTIONS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUTS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."PAYOUT_TRANSACTIONS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."EVENTS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_GBR"."_SDC_REJECTED" FROM ROLE PUBLIC;

------ STRIPE NZL
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."CHARGES" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."BALANCE_TRANSACTIONS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUTS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUT_TRANSACTIONS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."EVENTS" TO ROLE TRANSFORMER;
GRANT SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."_SDC_REJECTED" TO ROLE TRANSFORMER;

REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."CHARGES" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."BALANCE_TRANSACTIONS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUTS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."PAYOUT_TRANSACTIONS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."EVENTS" FROM ROLE PUBLIC;
REVOKE SELECT ON TABLE "RAW"."STITCH_STRIPE_NZL"."_SDC_REJECTED" FROM ROLE PUBLIC;

