-- UPDATE PLAN
-- ADD TO DBT ROLES
-- CREATE THE ONE PII VIEW FOR SUBSCRIBERS
-- SELECT * FROM SUBSCRIBERS_PII ORDER BY ATTRIBUTES  LIMIT 100000

-- I DONT THINK THE OTHER 3 TABLES NEED MASKING OR SHOULD BE CONSIDERED PII
--SELECT * FROM SENDS_PII LIMIT 1000
--SELECT * FROM EVENTS_PII LIMIT 1000
--SELECT * FROM LIST_SUBSCRIBERS_PII LIMIT 1000

-- SO REMOVE THESE FROM PII GROUP ROLE AND MOVE TO NO-PII GROUP ROLE


--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE MARKETING;
USE SCHEMA EXACTTARGET;

-- ONLY HALF MASK WHILE STILL RUNNING UNDER TRANSFORMER
CREATE OR REPLACE VIEW VW_SUBSCRIBERS_PII AS
(
  SELECT
        CLIENT_ID ,
        PARTNERKEY	,
        CREATEDDATE	,
        ID	,
        OBJECTID	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS EMAILADDRESS,
        ATTRIBUTES	,
        SUBSCRIBERKEY	,
        STATUS	,
        EMAILTYPEPREFERENCE	,
        UNSUBSCRIBEDDATE

  FROM SUBSCRIBERS_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;
CREATE ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";

GRANT USAGE ON SCHEMA "MARKETING"."EXACTTARGET" TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";
GRANT USAGE ON DATABASE MARKETING TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";


-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "MARKETING.EXACTTARGET.SENDS_PII.no_pii.table.reader";
CREATE ROLE "MARKETING.EXACTTARGET.EVENTS_PII.no_pii.table.reader";
CREATE ROLE "MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.no_pii.table.reader";
CREATE ROLE "MARKETING.EXACTTARGET.SUBSCRIBERS_PII.no_pii.view.reader";


--ADD THE INVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "MARKETING"."EXACTTARGET"."SENDS_PII" TO ROLE "MARKETING.EXACTTARGET.SENDS_PII.no_pii.table.reader";
GRANT SELECT ON TABLE "MARKETING"."EXACTTARGET"."EVENTS_PII" TO ROLE "MARKETING.EXACTTARGET.EVENTS_PII.no_pii.table.reader";
GRANT SELECT ON TABLE "MARKETING"."EXACTTARGET"."LIST_SUBSCRIBERS_PII" TO ROLE "MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.no_pii.table.reader";
GRANT SELECT ON VIEW  "MARKETING"."EXACTTARGET"."VW_SUBSCRIBERS_PII" TO ROLE  "MARKETING.EXACTTARGET.SUBSCRIBERS_PII.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GROUP ROLES
GRANT ROLE "MARKETING.EXACTTARGET.SENDS_PII.no_pii.table.reader" TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";
GRANT ROLE "MARKETING.EXACTTARGET.EVENTS_PII.no_pii.table.reader" TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";
GRANT ROLE "MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.no_pii.table.reader" TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";
GRANT ROLE "MARKETING.EXACTTARGET.SUBSCRIBERS_PII.no_pii.view.reader" TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";

-- REMOVE THE PII ROLES
REVOKE ROLE  "MARKETING.EXACTTARGET.EVENTS_PII.pii.table.reader" FROM ROLE "MARKETING.EXACTTARGET.pii.reader.role";
REVOKE ROLE  "MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.pii.table.reader" FROM ROLE "MARKETING.EXACTTARGET.pii.reader.role";
REVOKE ROLE  "MARKETING.EXACTTARGET.SENDS_PII.pii.table.reader" FROM ROLE "MARKETING.EXACTTARGET.pii.reader.role";


-- TODO - NEVER RAN THESE 3 CAUSE I WAS SCARED
--DROP THE PII ROLES --
DROP ROLE "MARKETING.EXACTTARGET.EVENTS_PII.pii.table.reader";
DROP ROLE "MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.pii.table.reader"
DROP ROLE "MARKETING.EXACTTARGET.SENDS_PII.pii.table.reader";

-- ADD TO OIUR DBT ROLES
GRANT ROLE "MARKETING.EXACTTARGET.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "MARKETING.EXACTTARGET.no_pii.reader.role" TO ROLE DBT_PROD;

-- THIS TO LEAVE THIS SETUP AS IT WAS FOR THIS ROLE
GRANT ROLE "MARKETING.EXACTTARGET.no_pii.reader.role" TO ROLE "TRANSFORMING_WAREHOUSE.ANALYTICS.MARKETING.PII.ROLE";
GRANT ROLE "MARKETING.EXACTTARGET.no_pii.reader.role" TO ROLE "MARKETING.EXACTTARGET.pii.service.role"


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA EXACTTARGET;


SHOW GRANTS TO ROLE "MARKETING.EXACTTARGET.pii.reader.role";

-- THESE 3 SHOULD BE NO_PII
"MARKETING.EXACTTARGET.EVENTS_PII.pii.table.reader"
"MARKETING.EXACTTARGET.LIST_SUBSCRIBERS_PII.pii.table.reader"
"MARKETING.EXACTTARGET.SENDS_PII.pii.table.reader"
-- THIS ONE IS PII (EMAIL)
"MARKETING.EXACTTARGET.SUBSCRIBERS_PII.pii.table.reader"

-- no no-pii reader
SHOW GRANTS TO ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";


SHOW GRANTS ON ROLE "MARKETING.EXACTTARGET.pii.reader.role";
ACCOUNTADMIN
TRANSFORMING_WAREHOUSE.ANALYTICS.MARKETING.PII.ROLE


SHOW GRANTS ON ROLE "MARKETING.EXACTTARGET.no_pii.reader.role";
SHOW GRANTS ON ROLE  "MARKETING.EXACTTARGET.EVENTS_PII.pii.table.reader";