
--  SCRIPT TO RUN ONCE PII VIEW IS SET UP
--  THE PII READER ROLES WILL BE DROPPED FROM DBT ONCE THE PII VIEW IS CREATED
--  THE VIEW READER ROLE WILL BE GROUPED UNDER THE NO-PII ROLE
--  REVOKE ROLE "RAW.ADHOC_TABLES.pii.reader.role" FROM ROLE DBT_DEV;
--  REVOKE ROLE "RAW.ADHOC_TABLES.pii.reader.role" FROM ROLE DBT_PROD;

-- GIVE READ ACCESS TO AIRFLOW ROLE (VIA THE SERVICE ROLE)
USE ROLE SECURITYADMIN;
GRANT ROLE "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.pii.reader.role" to role "AIRFLOW_WAREHOUSE.HRIS_DATA.ICIMS.pii.service.role"

--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE WAREHOUSE AIRFLOW_WAREHOUSE;
USE DATABASE HRIS_DATA;
USE SCHEMA ICIMS;


CREATE OR REPLACE VIEW "HRIS_DATA"."ICIMS"."VW_CANDIDATE_WORKFLOW_PII" COPY GRANTS AS
(

SELECT
      CASE WHEN PII_ACCESS = TRUE THEN RECRUITING_WORKFLOW_PROFILE_PERSON_FULL_NAME_FIRST_LAST_LABEL ELSE sha2(RECRUITING_WORKFLOW_PROFILE_PERSON_FULL_NAME_FIRST_LAST_LABEL,512) END AS RECRUITING_WORKFLOW_PROFILE_PERSON_FULL_NAME_FIRST_LAST_LABEL	,
      UPDATED_DATE	,
      SUBMITTAL_ID	,
      PERSON_SYSTEM_ID	,
      JOB_SYSTEM_ID	,
      STATUS	,
      BIN	,
      SUBMITTAL_REJECTION_NOTE_MESSAGE_HTML	,
      APPLICATION_DATE	,
      DATE_FIRST_PLACED_IN_BIN_HR_RECRUITER_REVIEW	,
      DATE_FIRST_PLACED_IN_BIN_HIRING_MANAGER_REVIEW	,
      DATE_FIRST_PLACED_IN_BIN_HIRED	,
      PERSON_START_DATE	,
      PERSON_EMPLOYEE_NUM	,
      PERSON_HIRE_DATE	,
      PERSON_SOURCE	,
      PERSON_SOURCE_CHANNEL	,
      SOURCE_PERSON_FULL_NAME_FIRST_LAST	,
      SOURCE	,
      SOURCE_CHANNEL	,
      NUM_CURRENTLY_IN_STATUS_HIRED_HIRED	,
      DATE_FIRST_PLACED_IN_STATUS_HIRING_MANAGER_REVIEW_INTERVIEWED_NOT_SELECTED	,
      DATE_FIRST_PLACED_IN_STATUS_HIRING_MANAGER_REVIEW_REVIEWED_NOT_SELECTED	,
      DATE_FIRST_PLACED_IN_STATUS_HR_RECRUITER_REVIEW_INTERVIEWED_NOT_SELECTED	,
      DATE_FIRST_PLACED_IN_STATUS_HR_RECRUITER_REVIEW_REVIEWED_NOT_SELECTED	,
      DATE_FIRST_PLACED_IN_STATUS_OFFER_OFFER_DECLINED_REJECTED	,
      DATE_FIRST_PLACED_IN_STATUS_OFFER_OFFER_RESCINDED	,
      JOB_VACANCY_REASON,
      "DATE_LAST_PLACED_IN_BIN_HIRED",
	  "DATE_FIRST_PLACED_IN_STATUS_HIRED_SENT_TO_ULTIPRO",
	  "DATE_FIRST_PLACED_IN_STATUS_ONBOARD_ON_LAUNCHED",
	  "DATE_FIRST_PLACED_IN_BIN_NEW_SUBMISSIONS",
	  "DATE_FIRST_PLACED_IN_STATUS_OFFER_OFFER_WIZARD",
	  "DATE_FIRST_PLACED_IN_BIN_OFFER",
	  "SOURCE_NAME",
	  "PROPOSED_START_DATE",
	  "DATE_FIRST_PLACED_IN_STATUS_HIRING_LEADER_SCREENING_SUBMITTED_TO_HM",
	  "DATE_FIRST_PLACED_IN_STATUS_HIRING_LEADER_SCREENING_INTERVIEW_SCHEDULED",
	  "DATE_FIRST_PLACED_IN_STATUS_HIRING_LEADER_SCREENING_INTERVIEW_SCHEDULED_IN_PERSON",
	  "PERSON_UPDATED_AUDIT_TIMESTAMP",
	  "DATE_FIRST_PLACED_IN_STATUS_HIRING_LEADER_SCREENING_DECISION_PENDING",
	  "DATE_FIRST_PLACED_IN_BIN_ONBOARD",
	  "JOB_JOB_POSTING_CATEGORY",
	  CASE WHEN PII_ACCESS = TRUE THEN "OFFER_AMOUNT_BASE" ELSE NULL END AS "OFFER_AMOUNT_BASE",
	  "CURRENT_RELOCATION",
	  CASE WHEN PII_ACCESS = TRUE THEN "SIGN_ON_BONUS" ELSE NULL END AS "SIGN_ON_BONUS",
	  CASE WHEN PII_ACCESS = TRUE THEN "INITIAL_ANNUAL_BONUS" ELSE NULL END AS "INITIAL_ANNUAL_BONUS",
	  "DATE_FIRST_PLACED_IN_STATUS_TA_SCREENING_PHONE_INTERVIEW_REQUESTED",
	  "DATE_FIRST_PLACED_IN_STATUS_TA_SCREENING_VIDEO_INTERVIEW_SCHEDULED",
	  "DATE_FIRST_PLACED_IN_STATUS_TA_SCREENING_REVIEWED_NOT_SELECTED",
	  "DATE_FIRST_PLACED_IN_STATUS_NEW_SUBMISSIONS_NOT_CONSIDERED_FUTURE_POTENTIAL",
      _SF_INSERTEDDATETIME,
      _ETL_FILENAME

FROM CANDIDATE_WORKFLOW_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

-------------------------------------------


CREATE OR REPLACE VIEW "HRIS_DATA"."ICIMS"."VW_JOBS_PII" COPY GRANTS AS
(

SELECT
      JOB_ID	,
      CREATED_DATE	,
      JOB_FOLDER	,
      UPDATED_DATE	,
      EXTERNAL_JOB_TITLE	,
      INTERNAL_JOB_TITLE	,
      HIRING_MANAGER_FULL_NAME_FIRST_LAST	,
      LOCATION_NAME_LINKED	,
      LOCATION_CITY	,
      LOCATION_STATE_PROVINCE	,
      LOCATION_POSTAL_CODE	,
      RECRUITER_FULL_NAME_FIRST_LAST	,
      BUSINESS_UNIT,
      HIRE_TYPE	,
      JOB_CODE	,
      TEAM	,
      JOB_TYPE	,
      LOCATION_EXTERNAL_ID	,
      NUM_OF_DAYS_SINCE_FIRST_APPROVED	,
      DAYS_TO_FILL	,
      NUM_OF_DAYS_IN_PENDING_APPROVAL	,
      DATE_FIRST_PLACED_IN_APPROVED	,
      DAYS_TO_APPROVE	,
      DATE_FIRST_PLACED_IN_CLOSED_FILLED	,
      DATE_FIRST_PLACED_IN_CLOSED_NOT_FILLED	,
      NUM_OF_OPENINGS,
      NUM_OF_OPENINGS_REMAINING,
      DATE_LAST_PLACED_IN_APPROVED ,
	  DATE_FIRST_PLACED_IN_HOLD ,
	  LOCATION_COUNTRY ,
	  SUBTEAM ,
      TALENT_ACQ_COORDINATOR_FULL_NAME_FIRST_LAST ,
      HR_BUSINESS_PARTNER_FULL_NAME_FIRST_LAST ,
      TARGETED_JOB_START_DATE ,
      BASE_MIN ,
      BASE_MIDPOINT ,
      BASE_MAX ,
      HOURLY_BASE_MIN ,
      HOURLY_BASE_MIDPOINT ,
      HOURLY_BASE_MAX ,
      AGENCY_MIN ,
      AGENCY_MAX ,
      LTI_MTIP ,
      PENSION_STOCK ,
      ANNUAL_BONUS_MIN ,
      ANNUAL_BONUS_MAX ,
      COMPONENT_COMPANY_NAME ,
      SCOPE ,
      REFERRAL_PROGRAM_TYPE ,
      INTERNAL_PAYOUT_TIME_FRAME_DAYS ,
      INTERNAL_BONUS_AMOUNT ,
      RELOCATION_MAX ,
      SIGN_ON_BONUS_MIN ,
      SIGN_ON_BONUS_MAX ,
      TOTAL_NUM_OF_CANDIDATES,
      _SF_INSERTEDDATETIME	,
      _ETL_FILENAME

FROM JOBS_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

-------------------------------------------


-------------------------------------------


CREATE OR REPLACE VIEW "HRIS_DATA"."ICIMS"."VW_PERSONS_PII" COPY GRANTS AS
(

SELECT
      CASE WHEN PII_ACCESS = TRUE THEN FULL_NAME_FIRST_LAST ELSE sha2(FULL_NAME_FIRST_LAST,512) END AS FULL_NAME_FIRST_LAST	,
      SYSTEM_ID	,
      CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL,
      CASE WHEN PII_ACCESS = TRUE THEN DEFAULT_PHONES_NUMBER ELSE sha2(DEFAULT_PHONES_NUMBER,512) END AS DEFAULT_PHONES_NUMBER,
      CREATED_DATE	,
      UPDATED_DATE	,
      CASE WHEN PII_ACCESS = TRUE THEN DEFAULT_ADDRESSES_ADDRESS ELSE sha2(DEFAULT_ADDRESSES_ADDRESS,512) END AS DEFAULT_ADDRESSES_ADDRESS,
      CASE WHEN PII_ACCESS = TRUE THEN DEFAULT_ADDRESSES_ADDRESS_2 ELSE sha2(DEFAULT_ADDRESSES_ADDRESS_2,512) END AS DEFAULT_ADDRESSES_ADDRESS_2,
      DEFAULT_ADDRESSES_CITY,
      DEFAULT_ADDRESSES_POSTAL_CODE,
      DEFAULT_ADDRESSES_STATE_PROVINCE_FULL_NAME,
      DEFAULT_ADDRESSES_COUNTRY_FULL_NAME	,
      SOURCE	,
      SOURCE_CHANNEL	,
      SOURCE_PORTAL	,
      GENDER	,
      RACE	,
      PROMOTION_TRANSFER_DATE,
	  SOURCE_SPECIFICS,
	  SOURCE_PERSON_FULL_NAME_FIRST_LAST,
	  PERSON_FOLDER,
      _SF_INSERTEDDATETIME	,
      _ETL_FILENAME

FROM PERSONS_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


------ ADD ROLES
-- 1. FOR THE PII OR SENSITIVE DATA WE CREATED VIEW FOR.. CREATE A NEW NO_PII READER ROLE AND GROUP ROLE
-- 2. FOR THE TABLE THAT DO NOT HAVE PII OR SENISITIVE DATA - USE THE CURRENT READER ROE AND ADD THOSE TO THE GROUP ROLE

-- Create the group role
CREATE ROLE "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role";


-- individual view readers

-- VW_CANDIDATES_WORKFLOW_PII
CREATE ROLE "HRIS_DATA.ICIMS.CANDIDATE_WORKFLOW_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ICIMS"."VW_CANDIDATE_WORKFLOW_PII" to role "HRIS_DATA.ICIMS.CANDIDATE_WORKFLOW_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ICIMS.CANDIDATE_WORKFLOW_PII.no_pii.view.reader";
grant usage on schema "ICIMS" to role "HRIS_DATA.ICIMS.CANDIDATE_WORKFLOW_PII.no_pii.view.reader";
grant role "HRIS_DATA.ICIMS.CANDIDATE_WORKFLOW_PII.no_pii.view.reader" to role "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role";

-- VW_JOBS_PII
CREATE ROLE "HRIS_DATA.ICIMS.JOBS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ICIMS"."VW_JOBS_PII" to role "HRIS_DATA.ICIMS.JOBS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ICIMS.JOBS_PII.no_pii.view.reader";
grant usage on schema "ICIMS" to role "HRIS_DATA.ICIMS.JOBS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ICIMS.JOBS_PII.no_pii.view.reader" to role "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role";


-- VW_PERSONS_PII
CREATE ROLE "HRIS_DATA.ICIMS.VW_PERSONS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ICIMS"."VW_PERSONS_PII" to role "HRIS_DATA.ICIMS.VW_PERSONS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ICIMS.VW_PERSONS_PII.no_pii.view.reader";
grant usage on schema "ICIMS" to role "HRIS_DATA.ICIMS.VW_PERSONS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ICIMS.VW_PERSONS_PII.no_pii.view.reader" to role "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role";


-- ADD TABLES THAT DO NOT HAVE PII OR SENSITIVE INFORMATION (THE ONES WE DID NOT CREATE VIEWS FOR)
-- NONE


GRANT ROLE "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role" TO ROLE DBT_DEV;
--TEMP UNTIL QE UNHOOK TRANSFORMER
GRANT ROLE DBT_DEV TO ROLE TRANSFORMER;

SHOW GRANTS TO ROLE DBT_DEV

------------------------


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################



--REVOKE SELECT ON VIEW  "HRIS_DATA"."ULTIPRO"."VW_TIME_MANAGEMENT_TIME_PII" FROM ROLE DBT_DEV


--TESTING
SELECT * FROM VW_CANDIDATES_WORKFLOW_PII LIMIT 10;
SELECT * FROM VW_JOBS_PII   LIMIT 10;
SELECT * FROM VW_PERSONS_PII   LIMIT 10;


SHOW GRANTS TO ROLE "TRANSFORMING_WAREHOUSE.HRIS_DATA.ICIMS.no_pii.reader.role";
SHOW GRANTS ON TABLE CANDIDATE_WORKFLOW_PII;
SHOW GRANTS ON VIEW VW_CANDIDATE_WORKFLOW_PII;

-- TABLES WE DID NOT CREATE VIEW FOR
-- GET CURRENT READER
-- none

