language: ruby

services:
  - docker

before_install:
- docker build -f Dockerfile.dev --tag airflow/sdc .
- docker ps -a
- docker run -it -p 8080:8080 airflow/sdc bash

script:
- bundle exec airflow/sdc bash