sudo: required

services:
  - docker

branches:
  only:
    - master
    
script:
- docker build -f Dockerfile.dev --tag airflow/sdc .
#- docker run -it -p 8080:8080 airflow/sdc webserver


after_script:
  - docker images

