CREATE TABLE "FINANCE"."HFD"."DOCD_AND_ACTIVATED"
(

    "DOCDON" VARCHAR,
    "ACTIVATEDON" VARCHAR,
    "PATIENTID" VARCHAR,
    "INVOICETOTAL" VARCHAR,
    "TOTALDOWNPAYMENT" VARCHAR,
    "FINANCEAMOUNT" VARCHAR,
    "BEGINNINGPRINCIPALAMOUNT" VARCHAR,
    "DOCSTAMPTAX" VARCHAR,
    "STATUS" VARCHAR,
    "HFD_ID" VARCHAR,
    "EMAIL" VARCHAR,
    "CUSTOMERNAME" VARCHAR,
    "PROVIDERID" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
