CREATE TABLE "FINANCE"."HFD"."AGING"
(

    "CONFPROCEDUREDATE" VARCHAR,
    "DOCDON" VARCHAR,
    "CONFDATEYM" VARCHAR,
    "ENDOFMONTH" VARCHAR,
    "ISPREVMONTH" VARCHAR,
    "ENDINGBALANCE" VARCHAR,
    "DAYSPASTDUE" VARCHAR,
    "HFD_ID" VARCHAR,
    "PROVIDERID" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
