CREATE TABLE "FINANCE"."HFD"."PAYMENT_REPORT"
(

    "HFDID" VARCHAR,
    "PATIENTID" VARCHAR,
    "AMOUNTTOPROVGROSS" VARCHAR,
    "PRINCIPALAMOUNT" VARCHAR,
    "INTERESTAMOUNT" VARCHAR,
    "CREDITCARDFEE" VARCHAR,
    "RETENTIONFEE" VARCHAR,
    "AMOUNTTOPROVNET" VARCHAR,
    "CUSTOMERPAIDDATE" VARCHAR,
    "PROVIDERPAIDDATE" VARCHAR,
    "MONTHLYPAYMENTMETHOD" VARCHAR,
    "TRANSACTIONTYPE" VARCHAR,
    "PAYMENTSOURCE" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
