CREATE TABLE "FINANCE"."HFD"."CUSTOMER_ADJUSTED_TERM_LENGTHS"
(
    "PROCEDUREID" VARCHAR,
    "INITIAL_TERM_LENGTH" FLOAT,
    "FIRSTPAYMENTDATE" DATETIME,
    "UPDATED_TERM_LENGTH" FLOAT,
    "SELECTED_TERM_LENGTH" FLOAT,
    "REFINANCE_DATE" DATETIME,
    "NUMBER_OF_PAYMENTS_PAID" FLOAT,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);