CREATE TABLE "FINANCE"."HFD"."OPEN_APPS"
(

    "HFD_ID" VARCHAR,
    "PATIENTID" VARCHAR,
    "CUSTOMERNAME" VARCHAR,
    "PERSONRECEIVINGSERVICENAME" VARCHAR,
    "SUBMITTEDON" VARCHAR,
    "CREATEDON" VARCHAR,
    "STATUS" VARCHAR,
    "PROVIDERID" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
