CREATE TABLE "FINANCE"."HFD"."ON_HOLD_ACCOUNTS"
(

    "HFDID" VARCHAR,
    "PATIENTID" VARCHAR,
    "PROVIDERID" VARCHAR,
    "PAYMENTSTATUS" VARCHAR,
    "DETAILSTATUS" VARCHAR,
    "EMAIL" VARCHAR,
    "PRIMARYPHONE" VARCHAR,
    "HOLDDATE" VARCHAR,
    "DAYSONHOLD" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
