CREATE TABLE "FINANCE"."HFD"."FAILED_ACTIVATIONS"
(
	"APPLICATIONID" INT,
	"PROVIDERID" INT,
	"APPSTATUS" VARCHAR,
	"LOGGED" VARCHAR,
	"STATUSCODE" VARCHAR,
	"ISACTIVATED" VARCHAR,
	"ERRORCODE" VARCHAR,
	"ERRORMESSAGE" VARCHAR,
	"_ETL_FILENAME" VARCHAR,
	"_SF_INSERTEDDATETIME" DATETIME
);