CREATE TABLE "FINANCE"."HFD"."AMORTIZATION"
(

    "HFDID" VARCHAR,
    "PATIENTID" VARCHAR,
    "DOCDONYM" VARCHAR,
    "DUEDATE" VARCHAR,
    "PRINCIPALAMOUNT" VARCHAR,
    "INTEREST" VARCHAR,
    "TOTALPAYMENTAMOUNT" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
