CREATE TABLE "FINANCE"."HFD"."ARRANGEMENTS"
(
	"HFDID" INT,
	"PAYMENTSTATUS" VARCHAR,
	"DETAILSTATUS" VARCHAR,
	"EMAIL" VARCHAR,
	"PHONE" VARCHAR,
	"DATEARRANGMENTMADE" DATETIME,
	"_ETL_FILENAME" VARCHAR,
	"_SF_INSERTEDDATETIME" DATETIME
);