CREATE TABLE "FINANCE"."HFD"."PAYMENT_REPORT_SUBMITTED_FUNDS_CA"
(

    "HFDID" VARCHAR,
    "PATIENTID" VARCHAR,
    "AMOUNTTOPROVGROSS" VARCHAR,
    "APPLYTOPRINCIPAL" VARCHAR,
    "APPLYTOINTEREST" VARCHAR,
    "COST" VARCHAR,
    "RETENTIONFEE" VARCHAR,
    "NETAMOUNTTOPROVIDER" VARCHAR,
    "CUSTOMERPAIDDATE" VARCHAR,
    "PROVIDERPAIDDATE" VARCHAR,
    "TRANSACTIONTYPE" VARCHAR,
    "PAYMENTSOURCE" VARCHAR,
    "PAYMENTMETHOD" VARCHAR,
    "ACCOUNTINGCODE" VARCHAR,
    "MERCHANT" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
