CREATE TABLE "FINANCE"."HFD"."INVALID_CARD_ACCOUNTS"
(

    "HFDID" VARCHAR,
    "EMAIL" VARCHAR,
    "HASVALIDPMTMTH" VARCHAR,
    "INVALIDMTHD" VARCHAR,
    "CARDTYPE" VARCHAR,
    "PRINCIPALBALANCE" VARCHAR,
    "FEEBALANCE" VARCHAR,
    "PORTALACCT" VARCHAR,
    "MISSEDPMTS" VARCHAR,
    "PAYMENTSTATUS" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
