CREATE TABLE "FINANCE"."HFD"."COMMUNICATIONS"
(

    "HFD_ID" VARCHAR,
    "PATIENTID" VARCHAR,
    "EMAIL_TOTAL" VARCHAR,
    "EMAIL__PAYMENT_FAILED" FLOAT,
    "EMAIL__DELINQUENCY_REMINDER" FLOAT,
    "EMAIL__PAYMENT_REMINDER" FLOAT,
    "TEXT_TOTAL" FLOAT,
    "LETTER_TOTAL" FLOAT,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME

);
