CREATE TABLE "FINANCE"."HFD"."MISSED_AND_MANUAL_PAYMENTS"
(
    "TRANSACTIONDATE" DATETIME,
    "APPLICATIONID" VARCHAR,
    "AMOUNT" FLOAT,
    "TYPE" VARCHAR,
    "MERCHANT" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);