CREATE TABLE "FINANCE"."HFD"."PAYMENTS_DUE_BILLED_RECEIVED"
(
	"HFDID" INT,
	"ACTIVATEDON" DATETIME,
	"ACTIVATEDYM" VARCHAR,
	"PAYMENTSTATUS" VARCHAR,
	"DUECOUNT" INT,
	"DUEAMOUNT" FLOAT,
	"DUEDATE" DATETIME,
	"ATTEMPTDATE" VARCHAR,
	"BILLEDCOUNT" INT,
	"BILLEDAMT" VARCHAR,
	"RECVDCOUNT" INT,
	"RECVDPMTS" FLOAT,
	"MERCHANT" VARCHAR,
	"_ETL_FILENAME" VARCHAR,
	"_SF_INSERTEDDATETIME" DATETIME
);