CREATE TABLE "FINANCE"."HFD"."CUSTOMERS_WITHOUT_HFD_ACCOUNT"
(
    "APPLICATIONID" VARCHAR,
    "EMAIL" VARCHAR,
    "ACTIVATEDON" DATETIME,
    "PAYMENTSTATUS" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);