CREATE TABLE "FINANCE"."HFD"."CUSTOMER_DISPUTES"
(
    "HFDID" VARCHAR,
    "PROVIDERID" VARCHAR,
    "PAYMENTSTATUS" VARCHAR,
    "ACTIVATEDON" VARCHAR,
    "DISPUTEDATE" VARCHAR,
    "EMAIL" VARCHAR,
    "PRIMARYPHONE" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);