CREATE TABLE "FINANCE"."HFD"."DAILY_DUNNING_DETAIL"
(
	"HFDID" INT,
	"ADJUSTMENTDATE" DATETIME,
	"ADJUSTMENTAMOUNT" FLOAT,
	"PROVIDERID" INT,
	"_ETL_FILENAME" VARCHAR,
	"_SF_INSERTEDDATETIME" DATETIME
);
