CREATE TABLE "FINANCE"."HFD"."CUSTOMERS_LAST_FOUR"
(
    "APPLICATIONID" VARCHAR,
    "PROVIDERID" VARCHAR,
    "LAST4" VARCHAR,
    "EXPIRATIONDATE" VARCHAR,
    "TYPE" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);