CREATE TABLE "FINANCE"."HFD"."CUSTOMERS_USING_PORTAL"
(
    "APPLICATIONID" VARCHAR,
    "ACCOUNTCREATEDDATE" DATETIME,
    "LASTACCESSEDDATE" DATETIME,
    "PAYMENTSTATUS" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);