CREATE TABLE "FINANCE"."HFD"."FEE_MAXIMUMS"
(
	"STATE" VARCHAR,
	"STARTDATE" VARCHAR,
	"AMOUNT" VARCHAR,
	"ISPERCENT" VARCHAR,
	"PERCENT" VARCHAR,
	"TYPE" VARCHAR,
	"COUNTRY" VARCHAR,
	"_ETL_FILENAME" VARCHAR,
	"_SF_INSERTEDDATETIME" DATETIME
);