CREATE TABLE "FINANCE"."HFD"."CUSTOMER_CARD_INFO"
(
    "PROVIDERID" VARCHAR,
    "PROCEDUREID" VARCHAR,
    "CUSTOMERNAME" VARCHAR,
    "CUSTOMEREMAIL" VARCHAR,
    "CARDBRAND" VARCHAR,
    "UPDATEDDATE" VARCHAR,
    "ADDEDDATE" VARCHAR,
    "BILLINGSTREET" VARCHAR,
    "BILLINGCITY" VARCHAR,
    "BILLINGSTATE" VARCHAR,
    "BILLINGPOSTALCODE" VARCHAR,
    "BILLINGCOUNTRY" VARCHAR,
    "EXPIREMONTH" VARCHAR,
    "EXPIREYEAR" VARCHAR,
    "CARDTYPE" VARCHAR,
    "_ETL_FILENAME" VARCHAR,
    "_SF_INSERTEDDATETIME" DATETIME
);