-- UPDATE PLAN
-- CREAQE THE 3 INDIIDUAL TABLE ROLES (NO_PII)
-- ADD THESE ROLES TO THE NO-PII GROUP ROLE
-- REMOVE SELECT FROM GROUP ROLE
-- ADD TO DBT ROLES
-- NO VIEWS NEEDED HERE


--- SENSITVE INFORMATION TABLES
USE DATABASE FINANCE;
USE SCHEMA HFD;

USE ROLE SECURITYADMIN;

-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "FINANCE.HFD.DAILY_CHARGES.no_pii.table.reader";
CREATE ROLE "FINANCE.HFD.PM_DATA_TAPE.no_pii.table.reader";
CREATE ROLE "FINANCE.HFD.JPM_DATA_TAPE_MONTHLY.no_pii.table.reader";

--ADD THE INVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "FINANCE"."HFD"."DAILY_CHARGES" TO ROLE "FINANCE.HFD.DAILY_CHARGES.no_pii.table.reader";
GRANT SELECT ON TABLE "FINANCE"."HFD"."JPM_DATA_TAPE" TO ROLE "FINANCE.HFD.PM_DATA_TAPE.no_pii.table.reader";
GRANT SELECT ON TABLE "FINANCE"."HFD"."JPM_DATA_TAPE_MONTHLY" TO ROLE  "FINANCE.HFD.JPM_DATA_TAPE_MONTHLY.no_pii.table.reader";


-- ADD THE INVIDUAL ROLES TO ITS GEOUP ROLES
GRANT ROLE "FINANCE.HFD.DAILY_CHARGES.no_pii.table.reader" TO ROLE "FINANCE.HFD.no_pii.reader.role";
GRANT ROLE "FINANCE.HFD.PM_DATA_TAPE.no_pii.table.reader" TO ROLE "FINANCE.HFD.no_pii.reader.role";
GRANT ROLE "FINANCE.HFD.JPM_DATA_TAPE_MONTHLY.no_pii.table.reader" TO ROLE "FINANCE.HFD.no_pii.reader.role";


-- REMOVE SELECT PRIVILEGE DIRECTLY TO THE GROUP ROLE
REVOKE SELECT ON TABLE "FINANCE"."HFD"."DAILY_CHARGES" FROM ROLE "FINANCE.HFD.no_pii.reader.role";
REVOKE SELECT ON TABLE "FINANCE"."HFD"."JPM_DATA_TAPE"  FROM ROLE "FINANCE.HFD.no_pii.reader.role";
REVOKE SELECT ON TABLE "FINANCE"."HFD"."JPM_DATA_TAPE_MONTHLY" FROM ROLE "FINANCE.HFD.no_pii.reader.role";


GRANT ROLE "FINANCE.HFD.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "FINANCE.HFD.no_pii.reader.role" TO ROLE DBT_PROD;

-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA HFD;

SHOW GRANTS TO ROLE "FINANCE.HFD.pii.reader.role";
-- NO TABLES
SHOW GRANTS TO ROLE "FINANCE.HFD.no_pii.reader.role";
-- SE3LECT PERMISSIONS ON THESE TABLES
FINANCE.HFD.DAILY_CHARGES
FINANCE.HFD.JPM_DATA_TAPE
FINANCE.HFD.JPM_DATA_TAPE_MONTHLY


SHOW GRANTS ON ROLE "FINANCE.HFD.pii.reader.role";
--NONE
SHOW GRANTS ON  ROLE "FINANCE.HFD.no_pii.reader.role";
FINANCE.HFD.no_pii.service.role

SHOW GRANTS ON ROLE "FINANCE.HFD.no_pii.service.role"
AIRFLOW SERVICE
SECURITY ADMIN