-- UPDATE PLAN
-- CREAQE THE 2 INDIIDUAL TABLE ROLES (NO_PII)
-- ADD THESE ROLES TO THE NO-PII GROUP ROLE
-- REMOVE SELECT FROM GROUP ROLE
-- ADD TO DBT ROLES
-- NO VIEWS NEEDED HERE


--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE MARKETING;
USE SCHEMA NEUSTAR;


USE ROLE SECURITYADMIN;

-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "MARKETING.NEUSTAR.FACT_FUNNEL.no_pii.table.reader";
CREATE ROLE "MARKETING.NEUSTAR.etl_files_loaded.no_pii.table.reader";

--ADD THE INDVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "MARKETING"."NEUSTAR"."FACT_FUNNEL" TO ROLE "MARKETING.NEUSTAR.FACT_FUNNEL.no_pii.table.reader";
GRANT SELECT ON TABLE "MARKETING"."NEUSTAR"."etl_files_loaded" TO ROLE "MARKETING.NEUSTAR.etl_files_loaded.no_pii.table.reader";

-- ADD THE INDVIDUAL ROLES TO ITS GEOUP ROLES
GRANT ROLE "MARKETING.NEUSTAR.FACT_FUNNEL.no_pii.table.reader" TO ROLE "MARKETING.NEUSTAR.no_pii.reader.role";
GRANT ROLE "MARKETING.NEUSTAR.etl_files_loaded.no_pii.table.reader" TO ROLE "MARKETING.NEUSTAR.no_pii.reader.role";

-- REMOVE SELECT PRIVILEGE DIRECTLY TO THE GROUP ROLE
REVOKE SELECT ON TABLE "MARKETING"."NEUSTAR"."FACT_FUNNEL"  FROM ROLE "MARKETING.NEUSTAR.no_pii.reader.role";
REVOKE SELECT ON TABLE "MARKETING"."NEUSTAR"."etl_files_loaded"  FROM ROLE "MARKETING.NEUSTAR.no_pii.reader.role";

-- GRANT TO DBT
GRANT ROLE  "MARKETING.NEUSTAR.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE  "MARKETING.NEUSTAR.no_pii.reader.role" TO ROLE DBT_PROD;




-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA NEUSTAR;


SHOW GRANTS TO ROLE "MARKETING.NEUSTAR.no_pii.reader.role"
MARKETING.NEUSTAR."etl_files_loaded"
MARKETING.NEUSTAR.FACT_FUNNEL

-- NO PII READER ROLE
SHOW GRANTS TO ROLE "MARKETING.NEUSTAR.pii.reader.role"


SHOW GRANTS ON ROLE "MARKETING.NEUSTAR.no_pii.reader.role"
ACCOUNTADMIN
TRANSFORMER