CREATE OR REPLACE VIEW "WEB_DATA"."SHOPIFY"."VW_ORDERS" COPY GRANTS AS (

SELECT

    "ID" AS "ORDER_ID",
  	"NAME" AS "ORDER_NAME",
  	"ORDER_NUMBER",
  	"ORDER_STATUS_URL",
  	customer:id AS CUSTOMER_ID,
  	"LANDING_SITE"
  	"NOTE",
  	"APP_ID",
  	"BUYER_ACCEPTS_MARKETING",
  	"CLOSED_AT",
  	"CONFIRMED",
  	CASE WHEN PII_ACCESS = TRUE THEN "CONTACT_EMAIL" ELSE sha2("CONTACT_EMAIL", 512) END AS "CONTACT_EMAIL",
  	"CREATED_AT",
  	"CURRENCY",
  	CASE WHEN PII_ACCESS = TRUE THEN "EMAIL" ELSE sha2("EMAIL", 512) END AS "EMAIL",
  	"FINANCIAL_STATUS",
  	"FULFILLMENT_STATUS",
  	"GATEWAY",
  	"LOCATION_ID",
    CASE WHEN PII_ACCESS = TRUE THEN "PHONE" ELSE sha2("PHONE", 512) END AS "PHONE",
  	"PROCESSED_AT",
  	"PROCESSING_METHOD",
    "SOURCE_NAME",  	
    "SUBTOTAL_PRICE",
  	"TAGS",
  	"TAXES_INCLUDED",
  	"TEST",
  	"TOKEN",
  	"DISCOUNT_CODES",
  	"TOTAL_DISCOUNTS",
  	"TOTAL_LINE_ITEMS_PRICE",
  	"TOTAL_PRICE",
  	"TOTAL_PRICE_USD",
  	"TOTAL_TAX",
  	"TOTAL_WEIGHT",
  	"UPDATED_AT",
  	"CHECKOUT_ID",
  	"CART_TOKEN",
  	"CANCELLED_AT",
  	"CANCEL_REASON",
  	client_details:accept_language::string AS "ACCEPT_LANGUAGE",
  	client_details:browser_height::number AS "BROWSER_HEIGHT",
  	client_details:browser_width::number AS "BROWSER_WIDTH",
  	CASE WHEN PII_ACCESS = TRUE THEN client_details:browser_ip::string ELSE NULL END AS "BROWSER_IP",
  	client_details:session_hash::string AS "SESSION_HASH",
  	client_details:user_agent::string AS "USER_AGENT",

  	payment_details:avs_result_code::string AS "PAYMENT_DETAILS__AVS_RESULT_CODE",
  	CASE WHEN PII_ACCESS = TRUE THEN payment_details:credit_card_bin::string ELSE NULL END AS "PAYMENT_DETAILS__CREDIT_CARD_BIN",
  	payment_details:credit_card_company::string AS "PAYMENT_DETAILS__CREDIT_CARD_COMPANY",
  	payment_details:cvv_result_cod::string AS "PAYMENT_DETAILS__CVV_RESULT_CODE",

    CASE WHEN PII_ACCESS = TRUE THEN billing_address:address1::string else sha2(billing_address:address1::string, 512) END AS "BILLING_ADDRESS__ADDRESS1",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:address2::string else sha2(billing_address:address2::string, 512) END AS "BILLING_ADDRESS__ADDRESS2",
    billing_address:city::string AS "BILLING_ADDRESS__CITY",
    billing_address:country::string AS "BILLING_ADDRESS__COUNTRY",
    billing_address:country_code::string AS "BILLING_ADDRESS__COUNTRY_CODE",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:first_name::string else sha2(billing_address:first_name::string, 512) END AS "BILLING_ADDRESS__FIRST_NAME",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:last_name::string else sha2(billing_address:last_name::string, 512) END AS "BILLING_ADDRESS__LAST_NAME",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:latitude::float ELSE NULL END AS "BILLING_ADDRESS__LATITUDE",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:longitude::float ELSE NULL END AS "BILLING_ADDRESS__LONGITUDE",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:name::string else sha2(billing_address:name::string, 512) end AS "BILLING_ADDRESS__NAME",
    CASE WHEN PII_ACCESS = TRUE THEN billing_address:phone::string else sha2(billing_address:phone::string, 512) END AS "BILLING_ADDRESS__PHONE",
    billing_address:province::string AS "BILLING_ADDRESS__PROVINCE",
    billing_address:province_code::string AS "BILLING_ADDRESS__PROVINCE_CODE",
    billing_address:zip::string AS "BILLING_ADDRESS__ZIP",
    
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:address1::string else sha2(shipping_address:address1::string, 512) END AS "SHIPPING_ADDRESS__ADDRESS1",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:address2::string else sha2(shipping_address:address2::string, 512) END AS "SHIPPING_ADDRESS__ADDRESS2",
    shipping_address:city::string AS "SHIPPING_ADDRESS__CITY",
    shipping_address:country::string AS "SHIPPING_ADDRESS__COUNTRY",
    shipping_address:country_code::string AS "SHIPPING_ADDRESS__COUNTRY_CODE",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:first_name::string else sha2(shipping_address:first_name::string, 512) END AS "SHIPPING_ADDRESS__FIRST_NAME",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:last_name::string else sha2(shipping_address:last_name::string, 512) END AS "SHIPPING_ADDRESS__LAST_NAME",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:latitude::float ELSE NULL END AS "SHIPPING_ADDRESS__LATITUDE",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:longitude::float ELSE NULL END AS "SHIPPING_ADDRESS__LONGITUDE",
    CASE WHEN PII_ACCESS = TRUE THEN Shipping_address:name::string else sha2(shipping_address:name::string, 512) END AS "SHIPPING_ADDRESS__NAME",
    CASE WHEN PII_ACCESS = TRUE THEN shipping_address:phone::string else sha2(shipping_address:phone::string, 512) END AS "SHIPPING_ADDRESS__PHONE",
    shipping_address:province::string AS "SHIPPING_ADDRESS__PROVINCE",
    shipping_address:province_code::string AS "SHIPPING_ADDRESS__PROVINCE_CODE",
    shipping_address:zip::string AS "SHIPPING_ADDRESS__ZIP"

FROM "RAW"."STITCH_SHOPIFY_NEW"."ORDERS"
LEFT JOIN "DATAENG_UTILS"."MAPPINGS"."PII_MAPPINGS" PII ON PII.ROLE = CURRENT_ROLE()

);