create table "TIME_MANAGEMENT_TIMESHEET"
(
    "ID"                   int,
    "EMPLOYEEID"           int,
    "STARTS"               datetime,
    "ENDS"                 datetime,
    "MISSPUNCH"            int,
    "TARDY"                int,
    "SCHHR"                float,
    "REGHR"                float,
    "OT1"                  float,
    "OT2"                  float,
    "OT3"                  float,
    "OT4"                  float,
    "OT5"                  float,
    "PAYAMT"               float,
    "SUBMIT"               boolean,
    "APPROVE"              boolean,
    "SYSUPDATE"            datetime,
    "EARLYIN"              int,
    "GRACEIN"              int,
    "EARLYOUT"             int,
    "LATEOUT"              int,
    "LONGMEAL"             int,
    "SHORTMEAL"            int,
    "LONGBREAK"            int,
    "SHORTBREAK"           int,
    "ABSENCES"             int,
    "DAYAPPROVE"           varchar,
    "STATUS"               int,
    "AUTOMEAL"             int,
    "EARLYOUTG"            int,
    "NOMEAL"               int,
    "OVERTIME"             float,
    "SHORTWKDAY"           int,
    "APPPUNCH"             float,
    "AUTHOT"               float,
    "PAIDBRK"              int,
    "MLPREMCNT"            int,
    "MLPREMWAV"            int,
    "BKPREMCNT"            int,
    "BKPREMWAV"            int,
    "_SF_INSERTEDDATETIME" datetime

);
