create table "TIME_MANAGEMENT_SHIFT"
(
    "ID"                   int,
    "SHIFTNUM"             float,
    "DESCRIPTION"          varchar,
    "SHIFTTYPE"            float,
    "SHIFTCYC"             float,
    "DAYSCYCLE"            float,
    "CYCLEREF"             varchar,
    "DAYSTART"             varchar,
    "DAYEND"               varchar,
    "LUNCHMET"             float,
    "AUTOLUNCH"            boolean,
    "OPENLUNCH"            float,
    "LUNCH1HR"             float,
    "LUNCH2HR"             float,
    "LUNCH3HR"             float,
    "LUNCH4HR"             float,
    "LUNCH1DED"            float,
    "LUNCH2DED"            float,
    "LUNCH3DED"            float,
    "LUNCH4DED"            float,
    "BREAKWIN"             float,
    "NLBONUS"              boolean,
    "NLBONUSMN"            float,
    "NLMUSTWORK"           float,
    "BRKMETHOD"            float,
    "BRKPAYMIN"            float,
    "BRKLIMIT"             float,
    "MEALPYMIN"            float,
    "ENDLUNCH"             float,
    "SCHEDMEAL"            boolean,
    "DEDWINDOW"            boolean,
    "CREATEMEALOUT"        boolean,
    "CREATEMEALOUTHOURS"   float,
    "ABSDEDWIN"            boolean,
    "DYNWKONLY"            boolean,
    "NOSPLIT"              boolean,
    "HASREIMAFTER"         boolean,
    "REIMAFTER"            float,
    "MEALOUT"              int,
    "_SF_INSERTEDDATETIME" datetime

);
