-- UPDATE PLAN
-- CREAQE THE INDIIDUAL TABLE/VIEW ROLES
-- ADD THESE ROLES TO THEIR RESPECTIVE GROUP ROLE
-- REMOVE SELECT FROM GROUP ROLE
-- ADD TO DBT ROLES
-- 2 VIEWS NEEDED HERE FOR THE PII TABLES
-- REMOVE ASSIGNING NO PII READER TO PII READER


--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE MARKETING;
USE SCHEMA PODIUM;


CREATE OR REPLACE VIEW VW_INVITES_PII  COPY GRANTS  AS
(
  SELECT
      ID	,
      UID	,
      CASE WHEN PII_ACCESS = TRUE THEN PHONENUMBER ELSE sha2(PHONENUMBER,512) END AS PHONENUMBER,
      LASTINVITATIONSENT	,
      ORGANIZATIONID	,
      CREATEDAT	,
      UPDATEDAT	,
      REVIEWPAGEURL	,
      USERID	,
      TEST	,
      LOCATIONID	,
      CUSTOMERID	,
      CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL,
      _SF_INSERTEDDATETIME

  FROM INVITES_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

CREATE OR REPLACE VIEW VW_REVIEWS_PII  COPY GRANTS  AS
(
  SELECT
        ID	,
        SITEREVIEWID	,
        SITENAME	,
        AUTHORID	,
        REVIEWBODY	,
        RATING	 ,
        PUBLISHDATE	,
        REVIEWURL	,
        LOCATIONID	,
        CASE WHEN PII_ACCESS = TRUE THEN AUTHOR ELSE sha2(AUTHOR,512) END AS AUTHOR,
        CREATEDAT	,
        UPDATEDAT	,
        REVIEWINVITATIONID	,
        REVIEWINVITATIONUID	,
        _SF_INSERTEDDATETIME

  FROM REVIEWS_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


USE ROLE SECURITYADMIN;


-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "MARKETING.PODIUM.INVITES_PII.no_pii.view.reader";
CREATE ROLE "MARKETING.PODIUM.REVIEWS_PII.no_pii.view.reader";

CREATE ROLE "MARKETING.PODIUM.LOCATIONS.no_pii.table.reader";


--ADD THE INVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "MARKETING"."PODIUM"."LOCATIONS" TO ROLE   "MARKETING.PODIUM.LOCATIONS.no_pii.table.reader";

-- ADD TO VIEWS
GRANT SELECT ON VIEW "MARKETING"."PODIUM"."VW_INVITES_PII" TO ROLE "MARKETING.PODIUM.INVITES_PII.no_pii.view.reader";
GRANT SELECT ON VIEW "MARKETING"."PODIUM"."VW_REVIEWS_PII" TO ROLE "MARKETING.PODIUM.REVIEWS_PII.no_pii.view.reader";

-- ADD THE INVIDUAL ROLES TO ITS GROUP ROLES
GRANT ROLE "MARKETING.PODIUM.LOCATIONS.no_pii.table.reader"  TO ROLE "MARKETING.PODIUM.no_pii.reader.role";
GRANT ROLE "MARKETING.PODIUM.INVITES_PII.no_pii.view.reader" TO ROLE "MARKETING.PODIUM.no_pii.reader.role";
GRANT ROLE "MARKETING.PODIUM.REVIEWS_PII.no_pii.view.reader" TO ROLE "MARKETING.PODIUM.no_pii.reader.role";

-- REMOVE THE NO PII GROUP ROKE FROM THE PII ROLE  SONCE TRANSFORMER CAN USE BOTH ROLES ANYWAYS
REVOKE  ROLE "MARKETING.PODIUM.no_pii.reader.role" FROM ROLE  "MARKETING.PODIUM.pii.reader.role";

-- ADD TO DBT ROLES
GRANT ROLE "MARKETING.PODIUM.no_pii.reader.role" TO USE ROLE TRANSFORMER;
GRANT ROLE "MARKETING.PODIUM.no_pii.reader.role" TO ROLE DBT_PROD;

-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA PODIUM;


SHOW GRANTS TO ROLE "MARKETING.PODIUM.pii.reader.role"
MARKETING.PODIUM.INVITES_PII
MARKETING.PODIUM.REVIEWS_PII

SHOW GRANTS TO ROLE "MARKETING.PODIUM.no_pii.reader.role"
MARKETING.PODIUM.LOCATIONS

SHOW GRANTS ON ROLE  "MARKETING.PODIUM.pii.reader.role"
SECURITYADMIN
TRANSFORMER

SHOW GRANTS ON ROLE  "MARKETING.PODIUM.no_pii.reader.role"
MARKETING.PODIUM.pii.reader.role
SECURITYADMIN
TRANSFORMER