-- UPDATE PLAN
-- CREAQE THE 3 INDIIDUAL TABLE ROLES (NO_PII)
-- ADD THESE ROLES TO THE NO-PII GROUP ROLE
-- REMOVE SELECT FROM GROUP ROLE
-- ADD TO DBT ROLES
-- NO VIEWS NEEDED HERE


--- SENSITVE INFORMATION TABLES
USE DATABASE LOGISTICS;
USE SCHEMA BARRETT;

USE ROLE SECURITYADMIN;

-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "LOGISTICS.BARRETT.INBOUND_EVENTS.no_pii.table.reader";
CREATE ROLE "LOGISTICS.BARRETT.OUTBOUND_EVENTS.no_pii.table.reader";
CREATE ROLE "LOGISTICS.BARRETT.TRACKING.no_pii.table.reader";

--ADD THE INVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "LOGISTICS"."BARRETT"."INBOUND_EVENTS" TO ROLE "LOGISTICS.BARRETT.INBOUND_EVENTS.no_pii.table.reader";
GRANT SELECT ON TABLE "LOGISTICS"."BARRETT"."OUTBOUND_EVENTS" TO ROLE "LOGISTICS.BARRETT.OUTBOUND_EVENTS.no_pii.table.reader";
GRANT SELECT ON TABLE "LOGISTICS"."BARRETT"."TRACKING" TO ROLE "LOGISTICS.BARRETT.TRACKING.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GEOUP ROLES
GRANT ROLE "LOGISTICS.BARRETT.INBOUND_EVENTS.no_pii.table.reader" TO ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
GRANT ROLE "LOGISTICS.BARRETT.OUTBOUND_EVENTS.no_pii.table.reader" TO ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
GRANT ROLE "LOGISTICS.BARRETT.TRACKING.no_pii.table.reader" TO ROLE "LOGISTICS.BARRETT.no_pii.reader.role";

-- REMOVE SELECT PRIVILEGE DIRECTLY TO THE GROUP ROLE
REVOKE SELECT ON TABLE "LOGISTICS"."BARRETT"."INBOUND_EVENTS" FROM ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
REVOKE SELECT ON TABLE "LOGISTICS"."BARRETT"."OUTBOUND_EVENTS"  FROM ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
REVOKE SELECT ON TABLE "LOGISTICS"."BARRETT"."TRACKING"  FROM ROLE "LOGISTICS.BARRETT.no_pii.reader.role";

GRANT ROLE "LOGISTICS.BARRETT.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "LOGISTICS.BARRETT.no_pii.reader.role" TO ROLE DBT_PROD;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA BARRETT;

SHOW GRANTS TO ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
-- SE3LECT PERMISSIONS ON THESE TABLES
LOGISTICS.BARRETT.ETL_FILES_LOADED
LOGISTICS.BARRETT.INBOUND_EVENTS
LOGISTICS.BARRETT.OUTBOUND_EVENTS
LOGISTICS.BARRETT.TRACKING

SHOW GRANTS ON ROLE "LOGISTICS.BARRETT.no_pii.reader.role";
SECURITY ADMIN
TRANSFORMER