--  CREATE THE MAPPING TABLE
USE ROLE AIRFLOW_SERVICE_ROLE;
USE WAREHOUSE AIRFLOW_WAREHOUSE;
USE DATABASE DATAENG_UTILS;
USE SCHEMA MAPPINGS;

CREATE OR REPLACE TABLE PII_MAPPINGS (
  DEPARTMENT varchar,
  ROLE varchar,
  PII_ACCESS number
);

--CREATE OUR TWO ROLES PII ACCESS RECORDS
insert into PII_MAPPINGS(DEPARTMENT, ROLE, PII_ACCESS) values
 ('ANAYLTICS', 'TRANSFORMER', 0)
,('ANAYLTICS', 'DBT_PROD',1)
,('ANAYLTICS', 'DBT_DEV', 0);

SELECT *
FROM  PII_MAPPINGS;


USE ROLE SECURITYADMIN;
-- GIVE FULL RIGHTS TO OUR SCHEDULER ROLES
GRANT USAGE ON DATABASE DATAENG_UTILS TO ROLE AIRFLOW_SERVICE_ROLE;
GRANT USAGE ON SCHEMA DATAENG_UTILS.MAPPINGS TO ROLE AIRFLOW_SERVICE_ROLE;
GRANT SELECT ON TABLE DATAENG_UTILS.MAPPINGS.PII_MAPPINGS TO ROLE AIRFLOW_SERVICE_ROLE;

-- GIVE FULL RIGHTS TO OUR SCHEDULER ROLES
GRANT USAGE ON DATABASE DATAENG_UTILS TO ROLE LAB_SCHEDULER_SERVICE_ROLE;
GRANT USAGE ON SCHEMA  DATAENG_UTILS.MAPPINGS  TO ROLE LAB_SCHEDULER_SERVICE_ROLE;
GRANT SELECT ON TABLE DATAENG_UTILS.MAPPINGS.PII_MAPPINGS TO ROLE LAB_SCHEDULER_SERVICE_ROLE;

-- GRANTS TO TRANSFORMER OF THE ROLE DBT VIEWS  WILL USE
GRANT USAGE ON DATABASE DATAENG_UTILS TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA DATAENG_UTILS.MAPPINGS TO  ROLE TRANSFORMER;
GRANT SELECT ON TABLE  DATAENG_UTILS.MAPPINGS.PII_MAPPINGS TO  ROLE TRANSFORMER;
