--1 . CREATE THE DBT ROLES -
USE ROLE SECURITYADMIN -- OR ACCOUNTADMIN
CREATE ROLE DBT_PROD;
CREATE ROLE DBT_DEV;


-- plus anyone else here .. ideally a group that all data engs are in
GRANT ROLE DBT_PROD TO USER GLENBRAZIL;
GRANT ROLE DBT_DEV TO USER GLENBRAZIL;

GRANT USAGE ON WAREHOUSE TRANSFORMING_WAREHOUSE TO ROLE  DBT_PROD;
GRANT USAGE ON WAREHOUSE TRANSFORMING_WAREHOUSE TO ROLE  DBT_DEV;