
-- MASKING
-- CASE WHEN PII_ACCESS = TRUE THEN LAST_NAME ELSE  REPLACE(LAST_NAME, LEFT(LAST_NAME,3),'XXX_')END AS LAST_NAME,

--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE WAREHOUSE AIRFLOW_WAREHOUSE;
USE DATABASE HRIS_DATA;
USE SCHEMA ULTIPRO;

---


CREATE OR REPLACE VIEW VW_COMPENSATION_DETAILS_PII COPY GRANTS AS
(

SELECT
    EMPLOYEEID	,
    COMPANYID	,
    CASE WHEN PII_ACCESS = TRUE THEN ANNUALSALARY ELSE -9.99 END AS ANNUALSALARY,
    CASE WHEN PII_ACCESS = TRUE THEN HOURLYPAYRATE ELSE -9.99 END AS HOURLYPAYRATE,
    CASE WHEN PII_ACCESS = TRUE THEN WEEKLYPAYRATE ELSE -9.99 END AS WEEKLYPAYRATE,
    CASE WHEN PII_ACCESS = TRUE THEN PAYPERIODPAYRATE ELSE -9.99 END AS  PAYPERIODPAYRATE,
    CURRENCYCODE	,
    OTHERRATE1	,
    OTHERRATE2	,
    OTHERRATE3	,
    OTHERRATE4	,
    PAYGROUPDESCRIPTION	,
    PIECEPAYRATE	,
    PRIMARYJOBCODE	,
    JOBSALARYGRADE	,
    JOBCHANGEREASONCODE	,
    JOBGROUPCODE	,
    JOBTITLE	,
    DATEINJOB	,
    DATELASTPAID	,
    DATELASTWORKED	,
    DATEOFLASTSALARYREVIEW	,
    DATEOFNEXTSALAYRREVIEW	,
    ISAUTOALLOCATED	,
    ISAUTOPAID	,
    ISSEASONALWORKER	,
    ISHIGHLYCOMPENSATED	,
    ISMULTIPLEJOB	,
    PAYGROUPCODE	,
    PAYPERIOD	,
    PAYSCALECODE	,
    SALARYORHOURLYCODE	,
    FULLTIMEORPARTTIMECODE	,
    SCHEDULEDFULLTIMEEQUIVALENCY	,
    SCHEDULEDPERIODWORKHOURS	,
    SCHEDULEDANNUALWORKHOURS	,
    WEEKLYHOURS	,
    PRIMARYSHIFTCODE	,
    PRIMARYSHIFTGROUPCODE	,
    DATEPAIDTHRU	,
    EMPLSTATUS	,
    DISTRIBUTIONCENTERCODE	,
    NUMBEROFPAYMENTS	,
    AVGPAYRATECURPER	,
    BONUSTOTALHRS	,
    BONUSTOTALOTHRS	,
    TOTALANNSALARY	,
    PERFORMANCEREVIEWRATING	,
    PERFORMANCEREVIEWTYPE	,
    _SF_INSERTEDDATETIME

FROM COMPENSATION_DETAILS_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

------------------------

CREATE OR REPLACE VIEW VW_EMPLOYEE_CHANGES_PII COPY GRANTS AS
(

 SELECT
    CASE WHEN PII_ACCESS = TRUE THEN FIRSTNAME ELSE sha2(FIRSTNAME,512) END AS FIRSTNAME	,
    CASE WHEN PII_ACCESS = TRUE THEN LASTNAME ELSE sha2(LASTNAME,512) END AS LASTNAME	,
    CASE WHEN PII_ACCESS = TRUE THEN PREFERREDNAME ELSE sha2(PREFERREDNAME,512) END AS PREFERREDNAME	,
    CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS EMAILADDRESS	,
    COUNTRYCODE	,
    LANGUAGECODE	,
    EMPLOYEENUMBER	,
    EMPLOYEEID	,
    PERSONID	,
    USERINTEGRATIONKEY	,
    COMPANYNAME	,
    COMPANYID	,
    SUPERVISORID	,
    SALARYORHOURLY	,
    FULLTIMEORPARTTIME	,
    ISACTIVE	,
    WORKLOCATIONCODE	,
    JOBCODE	,
    PROJECTCODE	,
    ORGLEVEL1CODE	,
    ORGLEVEL2CODE	,
    ORGLEVEL3CODE	,
    ORGLEVEL4CODE	,
    CASE WHEN PII_ACCESS = TRUE THEN MIDDLENAME ELSE sha2(MIDDLENAME,512) END AS MIDDLENAME	,
    CASE WHEN PII_ACCESS = TRUE THEN WORKPHONE ELSE sha2(WORKPHONE,512) END AS WORKPHONE	,
    CASE WHEN PII_ACCESS = TRUE THEN HOMEPHONE ELSE sha2(HOMEPHONE,512) END AS HOMEPHONE	,
    CASE WHEN PII_ACCESS = TRUE THEN EMPLOYEEADDRESS1 ELSE sha2(EMPLOYEEADDRESS1,512) END AS EMPLOYEEADDRESS1	,
    CASE WHEN PII_ACCESS = TRUE THEN EMPLOYEEADDRESS2 ELSE sha2(EMPLOYEEADDRESS2,512) END AS EMPLOYEEADDRESS2	,
    CITY	,
    STATE,
    ZIPCODE	,
    TERMINATIONDATE	,
    HIREDATE	,
    CASE WHEN PII_ACCESS = TRUE THEN SUPERVISORNAME ELSE sha2(SUPERVISORNAME,512) END AS SUPERVISORNAME	,
    PREFIX	,
    SUFFIX	,
    CASE WHEN PII_ACCESS = TRUE THEN ALTERNATEEMAILADDRESS ELSE sha2(ALTERNATEEMAILADDRESS,512) END AS ALTERNATEEMAILADDRESS,
    GENDER	,
    DATEINJOB	,
    DATEOFLASTHIRE	,
    EMPLSTATUSSTARTDATE	,
    EMPLOYEETYPE	,
    EMPLOYEESTATUS	,
    JOBGROUPCODE	,
    ALTERNATEJOBTITLE

 FROM EMPLOYEE_CHANGES_PII
 LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

------------------------------

--DROP VIEW VW_EMPLOYEE_DETAILS_PII

CREATE OR REPLACE VIEW VW_EMPLOYMENT_DETAILS_PII  COPY GRANTS AS
(

 SELECT
          COMPANYID	,
          COMPANYCODE	,
          COMPANYNAME	,
          EMPLOYEEID	,
          JOBDESCRIPTION	,
          PAYGROUPDESCRIPTION	,
          PRIMARYJOBCODE	,
          ORGLEVEL1CODE	,
          ORGLEVEL2CODE	,
          ORGLEVEL3CODE	,
          ORGLEVEL4CODE	,
          ORIGINALHIREDATE	,
          LASTHIREDATE	,
          FULLTIMEORPARTTIMECODE	,
          PRIMARYWORKLOCATIONCODE	,
          LANGUAGECODE	,
          PRIMARYPROJECTCODE	,
          WORKPHONENUMBER	,
          WORKPHONEEXTENSION	,
          WORKPHONECOUNTRY	,
          DATEINJOB	,
          DATELASTWORKED	,
          DATEOFBENEFITSENIORITY	,
          DATEOFSENIORITY	,
          DEDUCTIONGROUPCODE	,
          EARNINGGROUPCODE	,
          EMPLOYEETYPECODE	,
          EMPLOYEESTATUSCODE	,
          EMPLOYEENUMBER	,
          JOBCHANGEREASONCODE	,
          JOBTITLE	,
          LEAVEREASONCODE	,
          SUPERVISORID	,
          SUPERVISORFIRSTNAME	,
          SUPERVISORLASTNAME	,
          AUTOALLOCATE	,
          CLOCKCODE	,
          DATELASTPAYDATEPAID	,
          CASE WHEN PII_ACCESS = TRUE THEN DATEOFEARLYRETIREMENT ELSE '2099-01-01' END AS  DATEOFEARLYRETIREMENT	,
          DATEOFLOCALUNION	,
          DATEOFNATIONALUNION	,
          CASE WHEN PII_ACCESS = TRUE THEN DATEOFRETIREMENT ELSE '2099-01-01' END AS  DATEOFRETIREMENT	,
          DATEOFSUSPENSION	,
          DATEOFTERMINATION	,
          DATEPAIDTHRU	,
          STATUSSTARTDATE	,
          HIRESOURCE	,
          ISAUTOALLOCATED	,
          ISAUTOPAID	,
          ISMULTIPLEJOB	,
          JOBGROUPCODE	,
          MAILSTOP	,
          OKTOREHIRE	,
          PAYGROUP	,
          PAYPERIOD	,
          PLANNEDLEAVEREASON	,
          POSITIONCODE	,
          SALARYORHOURLY	,
          SCHEDULEDANNUALHRS	,
          SCHEDULEDFTE ,
          SCHEDULEDWORKHRS	,
          SHIFT	,
          SHIFTGROUP	,
          CASE WHEN PII_ACCESS = TRUE THEN TERMREASON ELSE sha2(TERMREASON,512) END AS TERMREASON	,
          CASE WHEN PII_ACCESS = TRUE THEN TERMINATIONREASONDESCRIPTION ELSE sha2(TERMINATIONREASONDESCRIPTION,512) END AS TERMINATIONREASONDESCRIPTION,
          TERMTYPE	,
          TIMECLOCKID	,
          UNIONLOCAL	,
          UNIONNATIONAL	,
          WEEKLYHOURS	,
          DATETIMECREATED	,
          DATETIMECHANGED	,
          _SF_INSERTEDDATETIME

 FROM EMPLOYMENT_DETAILS_PII
 LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);
-------------------------------
CREATE OR REPLACE VIEW VW_RAAS_ACHIEVERS_AUDIT_PII  COPY GRANTS AS
(

  SELECT
    CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS EMAILADDRESS	,
    EMPLOYEENUMBER	,
    FIRSTNAME	,
    LASTNAME	,
    CASE WHEN PII_ACCESS = TRUE THEN SUPERVISOREMAIL ELSE sha2(SUPERVISOREMAIL,512) END AS SUPERVISOREMAIL	,
    LANGUAGECODE	,
    COUNTRY ,
    ORIGINALHIREDATE	,
    JOBTITLE	,
    ORGLEVEL1	,
    LOCATION	,
    LOCATIONCODE	,
    COMPANYCODE	,
    REPORTDATE	,
    REPORTKEY	,
    _SF_INSERTEDDATETIME

  FROM RAAS_ACHIEVERS_AUDIT_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);


--------------------
CREATE OR REPLACE VIEW VW_RESTAPI_COMPENSATION_DETAILS_PII COPY GRANTS AS
(

  SELECT
      EMPLOYEEID	,
      COMPANYID	,
      CASE WHEN PII_ACCESS = TRUE THEN ANNUALSALARY ELSE -9.99 END AS ANNUALSALARY,
      CASE WHEN PII_ACCESS = TRUE THEN HOURLYPAYRATE ELSE -9.99 END AS HOURLYPAYRATE,
      CASE WHEN PII_ACCESS = TRUE THEN WEEKLYPAYRATE ELSE -9.99 END AS WEEKLYPAYRATE,
      CASE WHEN PII_ACCESS = TRUE THEN PAYPERIODPAYRATE ELSE -9.99 END AS PAYPERIODPAYRATE,
      CURRENCYCODE	,
      OTHERRATE1	,
      OTHERRATE2	,
      OTHERRATE3	,
      OTHERRATE4	,
      PAYGROUPDESCRIPTION	,
      PIECEPAYRATE	,
      PRIMARYJOBCODE	,
      JOBSALARYGRADE	,
      JOBCHANGEREASONCODE	,
      JOBGROUPCODE	,
      JOBTITLE	,
      DATEINJOB	,
      DATELASTPAID	,
      DATELASTWORKED	,
      DATEOFLASTSALARYREVIEW	,
      DATEOFNEXTSALAYRREVIEW	,
      ISAUTOALLOCATED	,
      ISAUTOPAID	,
      ISSEASONALWORKER	,
      ISHIGHLYCOMPENSATED	,
      ISMULTIPLEJOB	,
      PAYGROUPCODE	,
      PAYPERIOD	,
      PAYSCALECODE	,
      SALARYORHOURLYCODE	,
      FULLTIMEORPARTTIMECODE	,
      SCHEDULEDFULLTIMEEQUIVALENCY	,
      SCHEDULEDPERIODWORKHOURS	,
      SCHEDULEDANNUALWORKHOURS	,
      WEEKLYHOURS	,
      PRIMARYSHIFTCODE	,
      PRIMARYSHIFTGROUPCODE	,
      DATEPAIDTHRU	,
      EMPLSTATUS	,
      DISTRIBUTIONCENTERCODE	,
      NUMBEROFPAYMENTS	,
      AVGPAYRATECURPER	,
      BONUSTOTALHRS	,
      BONUSTOTALOTHRS	,
      CASE WHEN PII_ACCESS = TRUE THEN TOTALANNSALARY ELSE -9.99 END AS TOTALANNSALARY,
      PERFORMANCEREVIEWRATING	,
      PERFORMANCEREVIEWTYPE ,
      _SF_INSERTEDDATETIME

  FROM RESTAPI_COMPENSATION_DETAILS_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);



--------------------



CREATE OR REPLACE VIEW VW_RESTAPI_EMPLOYEE_CHANGES_PII COPY GRANTS AS
(

  SELECT
        FIRSTNAME	,
        LASTNAME	,
        PREFERREDNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS EMAILADDRESS	,
        COUNTRYCODE	,
        LANGUAGECODE	,
        EMPLOYEENUMBER	,
        EMPLOYEEID	,
        PERSONID	,
        USERINTEGRATIONKEY	,
        COMPANYNAME	,
        COMPANYID	,
        SUPERVISORID	,
        SALARYORHOURLY	,
        FULLTIMEORPARTTIME	,
        ISACTIVE	,
        WORKLOCATIONCODE	,
        JOBCODE	,
        PROJECTCODE	,
        ORGLEVEL1CODE	,
        ORGLEVEL2CODE	,
        ORGLEVEL3CODE	,
        ORGLEVEL4CODE	,
        MIDDLENAME	,
        CASE WHEN PII_ACCESS = TRUE THEN WORKPHONE ELSE sha2(WORKPHONE,512) END AS WORKPHONE	,
        CASE WHEN PII_ACCESS = TRUE THEN HOMEPHONE ELSE sha2(HOMEPHONE,512) END AS HOMEPHONE	,
        CASE WHEN PII_ACCESS = TRUE THEN EMPLOYEEADDRESS1 ELSE sha2(EMPLOYEEADDRESS1,512) END AS EMPLOYEEADDRESS1	,
        CASE WHEN PII_ACCESS = TRUE THEN EMPLOYEEADDRESS2 ELSE sha2(EMPLOYEEADDRESS2,512) END AS EMPLOYEEADDRESS2	,
        CITY	,
        STATE,
        ZIPCODE	,
        TERMINATIONDATE	,
        HIREDATE	,
        SUPERVISORNAME	,
        PREFIX	,
        SUFFIX	,
        CASE WHEN PII_ACCESS = TRUE THEN ALTERNATEEMAILADDRESS ELSE sha2(ALTERNATEEMAILADDRESS,512) END AS ALTERNATEEMAILADDRESS	,
        GENDER	,
        DATEINJOB	,
        DATEOFLASTHIRE	,
        EMPLSTATUSSTARTDATE	,
        EMPLOYEETYPE	,
        EMPLOYEESTATUS	,
        JOBGROUPCODE	,
        ALTERNATEJOBTITLE

  FROM RESTAPI_EMPLOYEE_CHANGES_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);
--------------------

--------------------

CREATE OR REPLACE VIEW VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII COPY GRANTS AS
(

  SELECT
        CASE WHEN PII_ACCESS = TRUE THEN ANNUALSALARY ELSE -9.99 END AS ANNUALSALARY,
        COMPANYID	,
        DATETIMECREATED	,
        EMPLOYEEID	,
        EMPLOYEETYPE	,
        EMPLOYEESTATUS	,
        FLSACATEGORY	,
        FULLTIMEORPARTTIME	,
        CASE WHEN PII_ACCESS = TRUE THEN HOURLYPAYRATE ELSE -9.99 END AS HOURLYPAYRATE,
        ISJOBCHANGE	,
        ISORGCHANGE	,
        ISOUTSIDEGUIDELINES	,
        ISOUTSIDERANGE,
        ISPROMOTION	,
        ISRATECHANGE	,
        ISSYSTEM	,
        ISTRANSFER	,
        JOBCODE	,
        CASE WHEN PII_ACCESS = TRUE THEN JOBDESCRIPTION ELSE sha2(JOBDESCRIPTION,512) END AS JOBDESCRIPTION	,
        JOBEFFECTIVEDATE	,
        JOBGROUPCODE	,
        LOCATIONCODE	,
        ORGLEVEL1CODE	,
        ORGLEVEL2CODE	,
        ORGLEVEL3CODE	,
        ORGLEVEL4CODE	,
        OTHERRATE1	,
        OTHERRATE2	,
        OTHERRATE3	,
        OTHERRATE4	,
        PAYGROUPCODE	,
        PAYPERIODCODE	,
        PAYSCALECODE	,
        PERCENTCHANGE	,
        CASE WHEN PII_ACCESS = TRUE THEN PERIODPAYRATE ELSE -9.99 END AS PERIODPAYRATE,
        PIECEPAYRATE	,
        POSITIONCODE	,
        REASONCODE	,
        SALARYGRADE	,
        SALARYORHOURLY	,
        SCHEDULEDANNUALHOURS	,
        SCHEDULEDFULLTIMEEQUIVALENCY	,
        SCHEDULEDWORKHOURS	,
        SHIFTCODE	,
        SHIFTGROUPCODE	,
        STEPNUMBER	,
        SUPERVISORID	,
        SUPERVISORNAMEFIRST	,
        SUPERVISORNAMELAST	,
        SUPERVISORNAMESUFFIX	,
        SUPERVISORNOTINLIST	,
        SYSTEMID	,
        UNIONNATIONAL	,
        USEPAYSCALES,
        CASE WHEN PII_ACCESS = TRUE THEN WEEKLYPAYRATE ELSE -9.99 END AS WEEKLYPAYRATE,
        NOTES	,
        HOMECOMPANYID	,
        INTEGRATIONEFFECTIVEDATE	,
        PROJECTCODE	,
        NUMBEROFPAYMENTS	,
        WEEKLYHOURS,
        ISVIEWABLEBYEMPLOYEE	,
        CREATEDBYUSERID	,
        CASE WHEN PII_ACCESS = TRUE THEN JOBTITLE ELSE sha2(JOBTITLE,512) END AS JOBTITLE	,
        _SF_INSERTEDDATETIME

  FROM RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


--------------------
-- RESTAPI_EMPLOYMENT_DETAILS_PII --  NOT SEEING ANY SENSITIVE INFO HERE
--------------------

CREATE OR REPLACE VIEW VW_RESTAPI_PERSON_DETAILS_PII COPY GRANTS AS
(

  SELECT
        ADDITIONALNAME1 ,
        ADDITIONALNAME2	,
        ADDRESSID	,
        ADDRESSISONTAXBOUNDARY	,
        ADDRESSLATITUDE	,
        COBRAEXPORT	,
        COBRAISACTIVE	,
        COBRAREASON	,
        COBRASTATUS	,
        COBRASTATUSDATE	,
        COMMUNITYBROADCASTSMSCODE	,
        CONSENTELECTRONICW2	,
        CONSENTELECTRONICW2PR	,
        DATEDECEASED	,
        DATEOFCOBRAEVENT	,
        DATEOFCOBRAEXPORT	,
        DATEOFCOBRALETTER	,
        DATEOFI9EXPIRATION,
        DATETIMECHANGED	,
        DATETIMECREATED	,
        DISABILITYTYPE	,
        ETHNICDESCRIPTION	,
        CASE WHEN PII_ACCESS = TRUE THEN FORMERNAME ELSE sha2(FORMERNAME,512) END AS FORMERNAME	,
        HEALTHBLOODTYPE	,
        HEALTHEYES	,
        HEALTHHAIR	,
        HEALTHHEIGHTFEET	,
        HEALTHHEIGHTINCHES ,
        HEALTHLASTDONATEDATE	,
        HEALTHWEIGHT	,
        I9ALIENNUMBER	,
        I9DOCA	,
        I9DOCB	,
        I9DOCC	 ,
        I9VERIFIED	,
        I9VISATYPE	,
        I9WORKAUTH	,
        ISDISABLED	,
        ISMULTIPAYGROUP	,
        ISSMOKER	,
        MILITARYSERVICE	,
        MILITARYBRANCHSERVED	,
        MILITARYERA	,
        MILITARYISDISABLEDVET	,
        MILITARYISOTHELIGVET	,
        MILITARYISOTHELIGVETBASIS	,
        MILITARYISACTIVEWARTIMEVET ,
        NAMEFORMER	,
        ORIGINCOUNTRY	,
        ORIGINLOCATION	,
        W2ISDECEASED	,
        COBRANOTES	,
        ADDRESSSMS	,
        MILITARYSEPARATIONDATE	,
        HOMEPHONEISPRIVATE	,
        SMSAPPROVALS	,
        SMSPAYNOTIFICATION	,
        I9VISAEXPIRATIONDATE	,
        MILITARYISMEDALVET	,
        LASTNAMENOTSAMEASSSCARD	,
        CHKCASHINGINSTCODE	,
        NATIONALITY1	,
        NATIONALITY2	,
        NATIONALITY3	,
        PERSONID	,
        EMPLOYEEID	,
        COMPANYID	,
        CASE WHEN PII_ACCESS = TRUE THEN USERNAME ELSE sha2(USERNAME,512) END AS USERNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN FIRSTNAME ELSE sha2(FIRSTNAME,512) END AS FIRSTNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN MIDDLENAME ELSE sha2(MIDDLENAME,512) END AS MIDDLENAME	,
        CASE WHEN PII_ACCESS = TRUE THEN LASTNAME ELSE sha2(LASTNAME,512) END AS LASTNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN PREFERREDNAME ELSE sha2(PREFERREDNAME,512) END AS PREFERREDNAME	,
        NAMEPREFIXCODE ,
        NAMESUFIXCODE	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESS ELSE sha2(EMAILADDRESS,512) END AS EMAILADDRESS	,
        CASE WHEN PII_ACCESS = TRUE THEN EMAILADDRESSALTERNATE ELSE sha2(EMAILADDRESSALTERNATE,512) END AS EMAILADDRESSALTERNATE	,
        CASE WHEN PII_ACCESS = TRUE THEN HOMEPHONE ELSE sha2(HOMEPHONE,512) END AS HOMEPHONE	,
        HOMEPHONECOUNTRY	,
        CASE WHEN PII_ACCESS = TRUE THEN ADDRESSLINE1 ELSE sha2(ADDRESSLINE1,512) END AS ADDRESSLINE1	,
        CASE WHEN PII_ACCESS = TRUE THEN ADDRESSLINE2 ELSE sha2(ADDRESSLINE2,512) END AS ADDRESSLINE2	,
        ADDRESSCITY	,
        ADDRESSSTATE	,
        ADDRESSZIPCODE	,
        ADDRESSCOUNTRY	,
        ADDRESSCOUNTY	,
        CASE WHEN PII_ACCESS = TRUE THEN DATEOFBIRTH ELSE '2099-01-01' END AS  DATEOFBIRTH	,
        GENDER	,
        ETHNICIDCODE	,
        MARITALSTATUSCODE	,
        SSNISSUPPRESSED	,
        _SF_INSERTEDDATETIME

  FROM RESTAPI_PERSON_DETAILS_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

--------------------
--------------------
-- RESTAPI_PTO_PLANS_PII --  NOT SEEING ANY SENSITIVE INFO HERE
--------------------"HRIS_DATA"."ULTIPRO"."SERVICE_EMPLOYEE_COMPENSATION_PII"
----

CREATE OR REPLACE VIEW VW_SERVICE_EMPLOYEE_COMPENSATION_PII  COPY GRANTS AS
(

SELECT
        CASE WHEN PII_ACCESS = TRUE THEN FIRSTNAME ELSE sha2(FIRSTNAME,512) END AS FIRSTNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN LASTNAME ELSE sha2(LASTNAME,512) END AS LASTNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN ANNUAL ELSE -9.99 END AS ANNUAL,
        EFFECTIVEDATE	,
        COMPANYCODE ,
        EMPLOYEENUMBER	,
        CASE WHEN PII_ACCESS = TRUE THEN HOURLY ELSE -9.99 END AS HOURLY,
        PAYFREQUENCY ,
        PAYGROUP	,
        PERCENTCHANGE	,
        CASE WHEN PII_ACCESS = TRUE THEN PERIOD ELSE -9.99 END AS PERIOD,
        RATECHANGETYPE	,
        REASONCODE	,
        SCHEDULEDHOURS ,
        CASE WHEN PII_ACCESS = TRUE THEN WEEKLY ELSE -9.99 END AS WEEKLY,
        _SF_INSERTEDDATETIME

FROM SERVICE_EMPLOYEE_COMPENSATION_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);

--------

CREATE OR REPLACE VIEW VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII  COPY GRANTS AS
(

SELECT
      CASE WHEN PII_ACCESS = TRUE THEN FIRSTNAME ELSE sha2(FIRSTNAME,512) END AS FIRSTNAME	,
      CASE WHEN PII_ACCESS = TRUE THEN LASTNAME ELSE sha2(LASTNAME,512) END AS LASTNAME	,
      ARREARSSUSPENDEDFROM	,
      ARREARSSUSPENDEDTO	,
      BENESENIORITY	,
      DECEASED ,
      DECEASEDDATE	,
      CASE WHEN PII_ACCESS = TRUE THEN EARLYRETIREMENT ELSE '2099-01-01' END AS  EARLYRETIREMENT	,
      COMPANYCODE	,
      EMPLOYEENUMBER	,
      EMPLOYMENTSTATUS	,
      FMLA_CODE	,
      HCSOENDDATE	,
      HCSONOTCOVERED	,
      HCSOSTARTDATE	,
      JOB	 ,
      JOBSTART	,
      LASTHIRE	,
      LASTPERFREVIEW	,
      LASTSALARYREVIEW ,
      LEAVEREASON	,
      NEXTPERFREVIEW	,
      NEXTSALARYREVIEW	,
      ORIGINALHIRE	,
      PTOSUSPENDEDFROM	,
      PTOSUSPENDEDTO	,
      PAYAUTOMATICALLY	,
      PAYSUSPENDEDFROM	,
      PAYSUSPENDEDTO	,
      ROEISSUEREASON	,
      CASE WHEN PII_ACCESS = TRUE THEN REGULARRETIREMENT ELSE '2099-01-01' END AS  REGULARRETIREMENT	,
      SENIORITY	 ,
      STATUSANTICIPATEDEND	,
      STATUSSTARTDATE	,
      WEEKS	,
      _SF_INSERTEDDATETIME,
      pii.*

  FROM SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

-------------

CREATE OR REPLACE VIEW VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII COPY GRANTS AS

(

SELECT
        COMPANYCODE	,
        EMPLOYEENUMBER	,
        FIRSTNAME	,
        LASTNAME	,
        ACCRUALS	,
        CASE WHEN PII_ACCESS = TRUE THEN ADDRESSLINE1 ELSE sha2(ADDRESSLINE1,512) END AS ADDRESSLINE1	,
        CASE WHEN PII_ACCESS = TRUE THEN ADDRESSLINE2 ELSE sha2(ADDRESSLINE2,512) END AS ADDRESSLINE2	,
        CITY	,
        COMPANYADDRESSCITY	,
        COMPANYADDRESSCOUNTRY	,
        COMPANYADDRESSCOUNTY	,
        COMPANYADDRESSLINE1	,
        COMPANYADDRESSLINE2	,
        COMPANYADDRESSPOSTALCODE	,
        COMPANYADDRESSSTATEORPROVINCE	,
        COMPANYNAME	,
        COMPANYPHONE	,
        COMPANYPHONEEXT	,
        COUNTRY	 ,
        CASE WHEN PII_ACCESS = TRUE THEN DEDUCTIONSCURRENT ELSE -9.99 END AS DEDUCTIONSCURRENT,
        CASE WHEN PII_ACCESS = TRUE THEN DEDUCTIONSYTD ELSE -9.99 END AS DEDUCTIONSYTD,
        DEDUCTIONS	,
        DOCUMENT	,
        CASE WHEN PII_ACCESS = TRUE THEN EARNINGS ELSE -9.99 END AS EARNINGS,
        EMPLOYEEIDENTIFIER	,
        FEDERALADDITIONALAMOUNTWITHHELD	,
        FEDERALALLOWANCESCLAIMED	,
        FEDERALFILINGSTATUS ,
        CASE WHEN PII_ACCESS = TRUE THEN  FEDERALTAXABLEWAGESCURRENT ELSE -9.99 END AS  FEDERALTAXABLEWAGESCURRENT,
        CASE WHEN PII_ACCESS = TRUE THEN  FEDERALTAXABLEWAGESYTD ELSE -9.99 END AS  FEDERALTAXABLEWAGESYTD,
        CASE WHEN PII_ACCESS = TRUE THEN  FULLNAME ELSE sha2(FULLNAME,512) END AS FULLNAME	,
        CASE WHEN PII_ACCESS = TRUE THEN  GROSSWAGESCURRENT ELSE -9.99 END AS  GROSSWAGESCURRENT,
        CASE WHEN PII_ACCESS = TRUE THEN  GROSSWAGESYTD ELSE -9.99 END AS  GROSSWAGESYTD,
        JOB	,
        LOCATION	,
        CASE WHEN PII_ACCESS = TRUE THEN  NETPAYCURRENT ELSE -9.99 END AS  NETPAYCURRENT,
        CASE WHEN PII_ACCESS = TRUE THEN  NETPAYYTD ELSE -9.99 END AS  NETPAYYTD,
        --NETPAY:Amount	, --json
        PARSE_JSON(regexp_replace(NETPAY,'[0-9]',9)) AS NETPAY,
        ORGLEVEL1	,
        ORGLEVEL2	,
        ORGLEVEL3	,
        ORGLEVEL4	,
        PAYDATE,
        PAYFREQUENCY	,
        PAYGROUP	,
        PAYIDENTIFIER	,
        CASE WHEN PII_ACCESS = TRUE THEN  PAYRATE ELSE -9.99 END AS  PAYRATE,
        PERIODENDDATE	,
        PERIODSTARTDATE ,
        POSTALCODE	,
        RESIDENTSTATEALLOWANCESCLAIMED	,
        RESIDENTSTATEFILINGSTATUS ,
        CASE WHEN PII_ACCESS = TRUE THEN  SSN ELSE sha2(SSN,512) END AS SSN	,
        STATEORPROVINCE ,
        CASE WHEN PII_ACCESS = TRUE THEN  TAXESCURRENT ELSE -9.99 END AS  TAXESCURRENT,
        CASE WHEN PII_ACCESS = TRUE THEN  TAXESYTD ELSE -9.99 END AS  TAXESYTD,
        WORKSTATEALLOWANCESCLAIMED	,
        WORKSTATEFILINGSTATUS	,
        _SF_INSERTEDDATETIME

FROM SERVICE_EMPLOYEE_PAY_STATEMENT_PII
LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()

);


-----------------------
CREATE OR REPLACE VIEW VW_TIME_MANAGEMENT_EMPLOYEE_PII COPY GRANTS AS

(

SELECT
      ID	,
      EMPID	,
      CARDNUM	,
      SUPID ,
      SUPNAME	,
      FIRSTNAME	,
      LASTNAME	,
      ACTIVE	,
      CASE WHEN PII_ACCESS = TRUE THEN EMAIL ELSE sha2(EMAIL,512) END AS EMAIL	,
      CASE WHEN PII_ACCESS = TRUE THEN BIRTHDATE ELSE '2099-01-01' END AS  BIRTHDATE	,
      HIREDATE	,
      PAYMETHOD	,
      PAYTYPE	,
      HOLIRULE	,
      PAYCATE	,
      PAYGROUPID	,
      LOCATIONID	,
      JOBID	,
      PROJECTID	,
      ORGLEVEL1ID	,
      ORGLEVEL2ID	,
      ORGLEVEL3ID	,
      ORGLEVEL4ID	,
      PAYPOLICYID	,
      SHIFTID	,
      ACCESSGROUPID ,
      _SF_INSERTEDDATETIME

  FROM TIME_MANAGEMENT_EMPLOYEE_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);
-------------------------------


CREATE OR REPLACE VIEW VW_TIME_MANAGEMENT_TIME_PII COPY GRANTS AS

(

SELECT
        ID	,
        EMPID	,
        WORKDATE	,
        PAYCODEID	,
        PAYCODEEXP	,
        INORG	,
        OUTORG	,
        "IN"	,
        "OUT"	,
        INEXP	,
        OUTEXP	,
        SHIFTEXP	,
        SCHHRS	,
        REGHR	,
        OVERT1	,
        OVERT2	,
        OVERT3	,
        OVERT4 ,
        OVERT5	,
        CASE WHEN PII_ACCESS = TRUE THEN  REGPAY ELSE -9.99 END AS  REGPAY,
        OT1PAY	,
        OT2PAY	,
        OT3PAY	,
        OT4PAY ,
        OT5PAY	,
        CASE WHEN PII_ACCESS = TRUE THEN  WEEKREG ELSE -9.99 END AS  WEEKREG,
        WEEKOT1	,
        WEEKOT2	,
        WEEKOT3	,
        WEEKOT4	,
        WEEKOT5	,
        REASONID	,
        PAYGROUPID	,
        LOCATIONID	,
        JOBID	,
        PROJECTID	,
        ORGLEVEL1ID	,
        ORGLEVEL2ID	,
        ORGLEVEL3ID	,
        ORGLEVEL4ID	,
        PERIODTH	,
        SITEIN	,
        SITEOUT	,
        QUANGOOD	,
        QUANSCRAP	,
        BEGSCHED	,
        ENDSCHED	,
        STATUS	,
        ADJUSTMENTDATE	,
        INROUNDED	,
        OUTROUNDED	,
        _SF_INSERTEDDATETIME

  FROM TIME_MANAGEMENT_TIME_PII
  LEFT JOIN DATAENG_UTILS.MAPPINGS.PII_MAPPINGS PII ON PII.ROLE = CURRENT_ROLE()
);

-- TESTING
SELECT * FROM  DATAENG_UTILS.MAPPINGS.PII_MAPPINGS ;

SELECT * FROM  VW_COMPENSATION_DETAILS_PII LIMIT 10;
SELECT * FROM  VW_EMPLOYEE_CHANGES_PII LIMIT 10;
SELECT * FROM  VW_EMPLOYMENT_DETAILS_PII LIMIT 10;
SELECT * FROM  VW_RAAS_ACHIEVERS_AUDIT_PII LIMIT 10;
SELECT * FROM  VW_RESTAPI_COMPENSATION_DETAILS_PII LIMIT 10;
SELECT * FROM  VW_RESTAPI_EMPLOYEE_CHANGES_PII LIMIT 10;
SELECT * FROM  VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII LIMIT 10;
SELECT * FROM  VW_RESTAPI_PERSON_DETAILS_PII LIMIT 10;
SELECT * FROM  VW_SERVICE_EMPLOYEE_COMPENSATION_PII  LIMIT 10;
SELECT * FROM  VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII LIMIT 10;
SELECT * FROM  VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII LIMIT 10;
SELECT * FROM  VW_TIME_MANAGEMENT_EMPLOYEE_PII LIMIT 10;
SELECT * FROM  VW_TIME_MANAGEMENT_TIME_PII LIMIT 10;


------ ADD ROLES
-- 1. FOR THE PII OR SENSITIVE DATA WE CREATED VIEW FOR.. CREATE A NEW NO_PII READER ROLE AND GROUP ROLE
-- 2. FOR THE TABLE THAT DO NOT HAVE PII OR SENISITIVE DATA - USE THE CURRENT READER ROE AND ADD THOSE TO THE GROUP ROLE

USE ROLE SECURITYADMIN;
-- group role for all view readers
CREATE ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- individual view readers

-- VW_COMPENSATION_DETAILS_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_COMPENSATION_DETAILS_PII" to role "HRIS_DATA.ULTIPRO.VW_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role  "HRIS_DATA.ULTIPRO.VW_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role "HRIS_DATA.ULTIPRO.VW_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_COMPENSATION_DETAILS_PII.no_pii.view.reader"to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_EMPLOYEE_CHANGES_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_EMPLOYEE_CHANGES_PII" to role "HRIS_DATA.ULTIPRO.VW_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role  "HRIS_DATA.ULTIPRO.VW_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role "HRIS_DATA.ULTIPRO.VW_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_EMPLOYEE_CHANGES_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_EMPLOYMENT_DETAILS_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_EMPLOYMENT_DETAILS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_EMPLOYMENT_DETAILS_PII" to role "HRIS_DATA.ULTIPRO.VW_EMPLOYMENT_DETAILS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_EMPLOYMENT_DETAILS_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role "HRIS_DATA.ULTIPRO.VW_EMPLOYMENT_DETAILS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_EMPLOYMENT_DETAILS_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_RAAS_ACHIEVERS_AUDIT_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_RAAS_ACHIEVERS_AUDIT_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_RAAS_ACHIEVERS_AUDIT_PII" to role  "HRIS_DATA.ULTIPRO.VW_RAAS_ACHIEVERS_AUDIT_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role  "HRIS_DATA.ULTIPRO.VW_RAAS_ACHIEVERS_AUDIT_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_RAAS_ACHIEVERS_AUDIT_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_RAAS_ACHIEVERS_AUDIT_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_RESTAPI_COMPENSATION_DETAILS_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_RESTAPI_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_RESTAPI_COMPENSATION_DETAILS_PII" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_RESTAPI_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_COMPENSATION_DETAILS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_RESTAPI_COMPENSATION_DETAILS_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_RESTAPI_EMPLOYEE_CHANGES_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_RESTAPI_EMPLOYEE_CHANGES_PII" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_CHANGES_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_CHANGES_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII" to role "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role   "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.no_pii.view.reader";
grant role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_RESTAPI_PERSON_DETAILS_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_RESTAPI_PERSON_DETAILS_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_RESTAPI_PERSON_DETAILS_PII" to role "HRIS_DATA.ULTIPRO.VW_RESTAPI_PERSON_DETAILS_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_PERSON_DETAILS_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_RESTAPI_PERSON_DETAILS_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_RESTAPI_PERSON_DETAILS_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- SERVICE_EMPLOYEE_COMPENSATION_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_SERVICE_EMPLOYEE_COMPENSATION_PII" to role "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII" to role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII" to role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role  "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_TIME_MANAGEMENT_EMPLOYEE_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_EMPLOYEE_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_TIME_MANAGEMENT_EMPLOYEE_PII" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_EMPLOYEE_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_EMPLOYEE_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_EMPLOYEE_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_EMPLOYEE_PII.no_pii.view.reader" to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";

-- VW_TIME_MANAGEMENT_TIME_PII
CREATE ROLE "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_TIME_PII.no_pii.view.reader";
grant select on view "HRIS_DATA"."ULTIPRO"."VW_TIME_MANAGEMENT_TIME_PII" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_TIME_PII.no_pii.view.reader";
grant usage on database "HRIS_DATA" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_TIME_PII.no_pii.view.reader";
grant usage on schema "ULTIPRO" to role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_TIME_PII.no_pii.view.reader";
grant role "HRIS_DATA.ULTIPRO.VW_TIME_MANAGEMENT_TIME_PII.no_pii.view.reader"to role "HRIS_DATA.ULTIPRO.no_pii.reader.role";


-- ADD TABLES THAT DO NOT HAVE PII OR SENSITIVE INFORMATION (THE ONES WE DID NOT CREATE VIEWS FOR)
GRANT ROLE "HRIS_DATA.ULTIPRO.RESTAPI_PTO_PLANS_PII.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_ACCESS_GROUPS.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_JOB.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_LOCATION.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_ORG_LEVEL_1.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_ORG_LEVEL_2.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_ORG_LEVEL_3.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_ORG_LEVEL_4.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_PROJECT.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_REASON.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_SCHEDULE.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_SCHEDULE_REQUEST.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_SHIFT.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_SHIFTDET.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_TIMESHEET.pii.table.reader" TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_PAYCODE.pii.table.reader"  TO  ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_PAYGROUP.pii.table.reader" TO ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";
GRANT ROLE "HRIS_DATA.ULTIPRO.RESTAPI_EMPLOYMENT_DETAILS_PII.pii.table.reader" TO ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role";

GRANT ROLE "HRIS_DATA.ULTIPRO.no_pii.reader.role" TO ROLE DBT_DEV;
--TEMP UNTIL QE UNHOOK TRANSFORMER
GRANT ROLE DBT_DEV TO ROLE TRANSFORMER;


-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

ADD ISSUE
RENAME THE ROLES THAT ARE NOT PII/SENSITIVE DATE TO SHOW NO-PII CONVENTION
OR DROP AND RECREATE AND ROLES ADDING BACK THE MAPPING

-- OPTIONAL
-- GRANT THE SELECT THAT WERE ON THE TABLE TO THE NEW VIEWS IF WE WANT TO ADD VIES TO PII READER AS WELL
PUUPOSELY BREAK HERE.. DONT RUN THESE UNLESS NEEDED
GRANT SELECT ON VW_COMPENSATION_DETAILS_PII TO "AIRFLOW_WAREHOUSE.HRIS_DATA.ULTIPRO.COMPENSATION_DETAILS_PII.pii.table.reader";
GRANT SELECT ON VW_EMPLOYEE_CHANGES_PII TO "AIRFLOW_WAREHOUSE.HRIS_DATA.ULTIPRO.EMPLOYEE_CHANGES_PII.pii.table.reader";
GRANT SELECT ON VW_EMPLOYMENT_DETAILS_PII TO "AIRFLOW_WAREHOUSE.HRIS_DATA.ULTIPRO.EMPLOYMENT_DETAILS_PII.pii.table.reader";
GRANT SELECT ON VW_RAAS_ACHIEVERS_AUDIT_PII TO "HRIS_DATA.ULTIPRO.RAAS_ACHIEVERS_AUDIT_PII.pii.table.reader";
GRANT SELECT ON VW_RESTAPI_COMPENSATION_DETAILS_PII TO "HRIS_DATA.ULTIPRO.RESTAPI_COMPENSATION_DETAILS_PII.pii.table.reader";
GRANT SELECT ON VW_RESTAPI_EMPLOYEE_CHANGES_PII TO "HRIS_DATA.ULTIPRO.RESTAPI_EMPLOYEE_CHANGES_PII.pii.table.reader";
GRANT SELECT ON VW_RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII TO "HRIS_DATA.ULTIPRO.RESTAPI_EMPLOYEE_JOB_HISTORY_DETAILS_PII.pii.table.reader";
GRANT SELECT ON VW_RESTAPI_PERSON_DETAILS_PII TO "HRIS_DATA.ULTIPRO.RESTAPI_PERSON_DETAILS_PII.pii.table.reader";
GRANT SELECT ON VW_SERVICE_EMPLOYEE_COMPENSATION_PII TO "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_COMPENSATION_PII.pii.table.reader";
GRANT SELECT ON VW_SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII TO "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII.pii.table.reader";
GRANT SELECT ON VW_SERVICE_EMPLOYEE_PAY_STATEMENT_PII TO "HRIS_DATA.ULTIPRO.SERVICE_EMPLOYEE_PAY_STATEMENT_PII.pii.table.reader";
GRANT SELECT ON VW_TIME_MANAGEMENT_EMPLOYEE_PII TO "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_EMPLOYEE_PII.pii.table.reader";
GRANT SELECT ON VW_TIME_MANAGEMENT_TIME_PII TO OLE "HRIS_DATA.ULTIPRO.TIME_MANAGEMENT_TIME_PII.pii.table.reader";

-- TABLES WE DID NOT CREATE VIEW FOR
-- GET CURRENT READER
SHOW GRANTS ON TABLE RESTAPI_PTO_PLANS_PII;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_ACCESS_GROUPS;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_JOB;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_LOCATION;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_ORG_LEVEL_1;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_ORG_LEVEL_2;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_ORG_LEVEL_3;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_ORG_LEVEL_4;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_PAYCODE;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_PAYGROUP;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_PROJECT;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_REASON;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_SCHEDULE;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_SCHEDULE_REQUEST;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_SHIFT;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_SHIFTDET;
SHOW GRANTS ON TABLE TIME_MANAGEMENT_TIMESHEET;



-- TEST AND JUNK STUFF
show grants to role "transforming_warehouse.analytics.finance.pii.role";
--has this granted to it.. and transformer is granted to this role
-- so this role currently has read access to all tables because of the below

show grants ON role "HRIS_DATA.ULTIPRO.pii.reader.role";

show grants to role "HRIS_DATA.ULTIPRO.no_pii.reader.role" --New one
show grants ON role "HRIS_DATA.ULTIPRO.no_pii.reader.role" --New one
--this role has all ultipro individual table reader toles

--example of individual table reader role
show grants to role  "HRIS_DATA.ULTIPRO.RAAS_ACHIEVERS_AUDIT_PII.pii.table.reader"
--has this granted to it
