-- UPDATE PLAN
-- CREAQE THE 1 INDIIDUAL TABLE ROLES (NO_PII)
-- ADD THESE ROLES TO THE NO-PII GROUP ROLE
-- REMOVE SELECT FROM GROUP ROLE
-- ADD TO DBT ROLES
-- NO VIEWS NEEDED HERE

--- SENSITVE INFORMATION TABLES
USE ROLE AIRFLOW_SERVICE_ROLE;
USE DATABASE MARKETING;
USE SCHEMA LOGIC_PLUM;

USE ROLE SECURITYADMIN;

-- CREATE THE INDIVIDUAL TABLE ROLES
CREATE ROLE "MARKETING.LOGIC_PLUM.BOOK_TO_SHOW_SCORES.no_pii.table.reader";

--ADD THE INVIDUAL ROLES OT THEIR TABLE
GRANT SELECT ON TABLE "MARKETING"."LOGIC_PLUM"."BOOK_TO_SHOW_SCORES" TO ROLE "MARKETING.LOGIC_PLUM.BOOK_TO_SHOW_SCORES.no_pii.table.reader";

-- ADD THE INVIDUAL ROLES TO ITS GEOUP ROLES
GRANT ROLE"MARKETING.LOGIC_PLUM.BOOK_TO_SHOW_SCORES.no_pii.table.reader" TO ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role";

-- REMOVE SELECT PRIVILEGE DIRECTLY TO THE GROUP ROLE
REVOKE SELECT ON TABLE "MARKETING"."LOGIC_PLUM"."BOOK_TO_SHOW_SCORES"  FROM ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role";

-- SHOULD BE OK TO REVOKE CAUSE OF THIS
-- GRANT TO TRANSFOMER (TEMP) UNTIL WE CHANGED TO DBT ROLES
--GRANT ROLE  DBT_DEV TO ROLE TRANSFORMER;
--GRANT ROLE  DBT_PROD TO ROLE TRANSFORMER;

-- GRANT TO DBT
GRANT ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role" TO ROLE DBT_DEV;
GRANT ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role" TO ROLE DBT_PROD;

-- GRANT TO TRANSFOMER (TEMP) UNTIL WE CHANGED TO DBT ROLES
GRANT ROLE  DBT_DEV TO ROLE TRANSFORMER;
GRANT ROLE  DBT_PROD TO ROLE TRANSFORMER;
-------############################################################

-- TEST AND JUNK STUFF BELOW ----------------------------

------###############################################################

SHOW GRANTS ON SCHEMA LOGIC_PLUM;


SHOW GRANTS TO ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role"
MARKETING.LOGIC_PLUM.BOOK_TO_SHOW_SCORES

-- NO PII READER ROLE
SHOW GRANTS TO ROLE "MARKETING.LOGIC_PLUM.pii.reader.role"


SHOW GRANTS ON ROLE "MARKETING.LOGIC_PLUM.no_pii.reader.role"
SECURITYADMIN
TRANSFORMER