create table "SERVICE_EMPLOYEE_EMPLOYMENT_INFORMATION_PII"
(
    "FIRSTNAME"            varchar,
    "LASTNAME"             varchar,
    "ARREARSSUSPENDEDFROM" datetime,
    "ARREARSSUSPENDEDTO"   datetime,
    "BENESENIORITY"        datetime,
    "DECEASED"             boolean,
    "DECEASEDDATE"         datetime,
    "EARLYRETIREMENT"      datetime,
    "COMPANYCODE"          varchar,
    "EMPLOYEENUMBER"       int,
    "EMPLOYMENTSTATUS"     varchar,
    "FMLA_CODE"            varchar,
    "HCSOENDDATE"          datetime,
    "HCSONOTCOVERED"       boolean,
    "HCSOSTARTDATE"        datetime,
    "JOB"                  varchar,
    "JOBSTART"             datetime,
    "LASTHIRE"             datetime,
    "LASTPERFREVIEW"       datetime,
    "LASTSALARYREVIEW"     datetime,
    "LEAVEREASON"          varchar,
    "NEXTPERFREVIEW"       datetime,
    "NEXTSALARYREVIEW"     datetime,
    "ORIGINALHIRE"         datetime,
    "PTOSUSPENDEDFROM"     datetime,
    "PTOSUSPENDEDTO"       datetime,
    "PAYAUTOMATICALLY"     boolean,
    "PAYSUSPENDEDFROM"     datetime,
    "PAYSUSPENDEDTO"       datetime,
    "ROEISSUEREASON"       boolean,
    "REGULARRETIREMENT"    datetime,
    "SENIORITY"            datetime,
    "STATUSANTICIPATEDEND" datetime,
    "STATUSSTARTDATE"      datetime,
    "WEEKS"                float,
    "_SF_INSERTEDDATETIME" datetime

);
