
CREATE OR REPLACE VIEW "MEDICAL_DATA"."TRUEVAULT"."VW_DENTAL_HEALTH_QUESTIONNAIRE_VIEW_1" COPY GRANTS AS (

    SELECT
        "CASE_NUMBER",
        "DATE_CREATED",
        UPPER("CUSTOMER_STATE") as "CUSTOMER_STATE",
        UPPER("HAS_RADIOGRAPH") as "RESULT"

    FROM "MEDICAL_DATA"."TRUEVAULT"."FACT_DENTAL_HEALTH_QUESTIONNAIRE_PII"

);