CREATE OR REPLACE VIEW "LOGISTICS"."TNT"."VW_TRACKING_EVENTS" COPY GRANTS AS
(
SELECT
	"DEPOT",
	"CONSIGNMENT",
	"STATUS",
	"STATUS_CAPTURE",
	"STATUS_AVAILABILITY",
	CASE WHEN PII_ACCESS = TRUE THEN "ADDITIONAL_INFORMATION" ELSE sha2("ADDITIONAL_INFORMATION", 512) END AS "ADDITIONAL_INFORMATION",
	CASE WHEN PII_ACCESS = TRUE THEN "RECEIVER" ELSE sha2("RECEIVER", 512) END AS "RECEIVER",
	"CNM_ITEMS",
	"STATUS_ITEMS",
	CASE WHEN PII_ACCESS = TRUE THEN "RECEIVER_POSTCODE" ELSE sha2("RECEIVER_POSTCODE", 512) END AS "RECEIVER_POSTCODE",
	CASE WHEN PII_ACCESS = TRUE THEN "RECEIVER_SUBURB" ELSE sha2("RECEIVER_SUBURB", 512) END AS "RECEIVER_SUBURB",
	"CUSTOMER_REFERENCE",
	"_ETL_FILENAME",
	"_SF_INSERTEDDATETIME"
 FROM "LOGISTICS"."TNT"."TRACKING_EVENTS"
 LEFT JOIN "DATAENG_UTILS"."MAPPINGS"."PII_MAPPINGS" PII ON PII.ROLE = CURRENT_ROLE()
);